### PR TITLE
WI #1785 Allow leading and/or trailing spaces in REPLACE placeholders

### LINKED ISSUE #1785: Bug in tag/placeholder replacing
**Describe the bug**
When the source text to replace when executing a REPLACE statement or a COPY WITH REPLACING statement starts or end with a space, the TypeCobol parser fails to identify the text and does not perform the replace operation.
Note that the bug is present when the additional space is either in the tag or in the text to be replaced.

**To Reproduce**
(Type)Cobol code that cause the bug : (if any)
```cobol
       identification division.
       program-id. TCOMFL02.
       data division.
       working-storage section.
      
       REPLACE ==:tag:== BY ==name1==.
       01 var-:tag: PIC X.
       REPLACE ==:tag:== BY ==name2==.
       01 var-: tag: PIC X.
       REPLACE ==:tag:== BY ==name3==.
       01 var-:tag : PIC X.
      
       REPLACE ==: tag:== BY ==name4==.
       01 var-:tag: PIC X.
       REPLACE ==: tag:== BY ==name5==.
       01 var-: tag: PIC X.
       REPLACE ==: tag:== BY ==name6==.
       01 var-:tag : PIC X.
      
       REPLACE ==:tag :== BY ==name7==.
       01 var-:tag: PIC X.
       REPLACE ==:tag :== BY ==name8==.
       01 var-: tag: PIC X.
       REPLACE ==:tag :== BY ==name9==.
       01 var-:tag : PIC X.
      
       procedure division.
           display var-name1
           display var-name2
           display var-name3
           display var-name4
           display var-name5
           display var-name6
           display var-name7
           display var-name8
           display var-name9
           goback
           .
       end program TCOMFL02.
```

**Expected behavior**
The replace operation should take palcec normally and produce the variables `var1-name1`, `var2-name2`, `var3-name3` and  `var4-name4`.

### PR DESCRIPTION
**Pull request by fm-117**
Fixes #1785

### CODE REVIEW

File: TypeCobol/Compiler/Preprocessor/ReplaceTokensLinesIterator.cs [hunk 1]
```diff
@@ -427,31 +428,17 @@ private Token CreateReplacedTokens(Token originalToken, ReplaceOperation replace
...
-                                ? tokenText.Substring(0, indexOfPartToReplace)
-                                : string.Empty) +
-                            replacementPart +
-                            (indexOfPartToReplace + partToReplace.Length < tokenText.Length
-                                ? tokenText.Substring(indexOfPartToReplace + partToReplace.Length)
-                                : string.Empty);
-                        startIndex = indexOfPartToReplace + replacementPart.Length;
-                    }
+
                     // TO DO use Replace(String, String, StringComparison) overload, available in .NET 5
```
Comment (smedilol) [inline TypeCobol/Compiler/Preprocessor/ReplaceTokensLinesIterator.cs:436]: This TODO can be removed now ?

**Review by smedilol — CHANGES_REQUESTED** [review]

File: TypeCobol/Compiler/Preprocessor/ReplaceTokensLinesIterator.cs (hunk 1 above)
Comment (fm-117) [reply TypeCobol/Compiler/Preprocessor/ReplaceTokensLinesIterator.cs:436]: 300px-Well_Yes,_But_Actually_No
Here I use the `Regex.Replace` for the ignore case option but this is not a regular expression replace because `normalizedPartToReplace` is not a pattern but a plain string. `string.Replace` with StringComparison argument (introduced with .NET 5) is more appropriate.

Comment (smedilol) [reply TypeCobol/Compiler/Preprocessor/ReplaceTokensLinesIterator.cs:436]: Ok ;)

**Review by smedilol — DISMISSED** [review]

File: TypeCobol.Test/Parser/Programs/Cobol85/Replace.rdz.cbl [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+           display name10-var
+           display var-name11
+           display name12varname12
+           display var-name13
+           display name14-var
+           display var-name15
+           display name16varname16
+           goback
+           .
+       end program TCOMFL02.
```
Comment (rooksdo) [inline TypeCobol.Test/Parser/Programs/Cobol85/Replace.rdz.cbl:61]: OK for these test. What about with multiple spaces ? For example with
```cob
REPLACE ==:   tag    :== BY ==name1==.
01 var-:  tag   : PIC X.
```

Comment (fm-117) [reply TypeCobol.Test/Parser/Programs/Cobol85/Replace.rdz.cbl:65]: Yes it works. The Regex matches multiple spaces, I've added your test in 72c1c9962754fd3508d4ee94d20af580f2ca12a1.

**Review by rooksdo — APPROVED** [review]

**Review by smedilol — APPROVED** [review]

**Review by mayanje — APPROVED** [review]
