### PR TITLE
WI 1710 Check duplicate paragraph names with semantic data owner

### LINKED ISSUE #1710: Compile error on programs with 2 paragraphs with the same name on procedure division
Programs with 2 paragraphs with the same name on different sections on procedure division provides a compiler error on TypeCobol but no erros on z/OS compiler.

This is a sample of a program to reproduce the error:

000100 IDENTIFICATION DIVISION.
000200 PROGRAM-ID. TESTSEC.
002100*
002200 ENVIRONMENT DIVISION.
002300 CONFIGURATION SECTION.
002600 DATA DIVISION.
002700 WORKING-STORAGE SECTION.
002800 77   V1   PIC 9 VALUE 1.
002900 77   V2   PIC 9 VALUE 2.
013900 PROCEDURE DIVISION.
015100*
015500 BA010-INICIO.
015600
015700      PERFORM SD011-ENTER.
015800      GOBACK.
015900
043900 SD011-ENTER SECTION.
043910 DD011-ENTER.
044000*
044100        MOVE V1 TO V2.
045400*
045500 DD119-EXIT.      EXIT.
045600*
045700 SD110-ENTER2 SECTION.
045800*-----------------------------------------------------*
045900 DD110-ENTER1.
046000*
046100        MOVE V2 TO V1.
047000*
047100 DD119-EXIT.      EXIT.
047110*
047111 DD110-ENTER2.
047112*
047120        PERFORM DD110-ENTER1 THRU DD119-EXIT.
047200*

```
and/or steps to reproduce the behavior:
1. compile the above sample program

**Expected behavior**
Consider that paragraph names should be unique inside a section but not on whole procedure, and it can be referenced as described on "References to PROCEDURE DIVISION names " chapter of  on [Enterprise COBOL for z/OS Language Reference](https://github.com/TypeCobolTeam/TypeCobol/blob/develop/TypeCobol/Documentation/Reference/IBM%20Enterprise%20Cobol%205.1%20for%20zOS%20-%20Language%20Reference.pdf)

The following attachment contains z/OS compiler output:
z/OS compiler output: [compzos.zip](https://github.com/TypeCobolTeam/TypeCobol/files/4416122/compzos.zip)

### PR DESCRIPTION
**Pull request by rooksdo**
Closes #1710

### CODE REVIEW

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs [hunk 1]
```diff
@@ -937,8 +937,11 @@ public static (SymbolType, Node) ResolveTargetSectionOrParagraph(Node callerNode
 
         private static void Check<T>(string nodeTypeName, T node, [NotNull] IList<T> found) where T : Node
         {
-            if (found.Count > 1)
+            //Check for duplicate declaration within the same owner
```
Comment (fm-117) [inline TypeCobol/Compiler/Diagnostics/CrossChecker.cs:940]: Maybe add another comment to explain what we compare when `T` is a paragraph (Owner is either a Program or a Section) vs when `T` is a section (Owner is Program).

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs [hunk 2]
```diff
@@ -937,8 +937,11 @@ public static (SymbolType, Node) ResolveTargetSectionOrParagraph(Node callerNode
...
+            if (found.Count(p => p.SemanticData.Owner.Equals(node.SemanticData.Owner)) > 1)
```
Comment (fm-117) [inline TypeCobol/Compiler/Diagnostics/CrossChecker.cs:941]: Also you can use operator `==` instead of Equals, this is more usual in C#.

**Comment by smedilol** [comment]
Issue #1710 is also about perform paragraph in different section.
See example, in the issue:
`PERFORM DD110-ENTER1 THRU DD119-EXIT.`

**Comment by fm-117** [comment]
I re-read the issue discussion and I agree with @smedilol: we should not modify the test on the found list but rather change the `SymbolTable.GetParagraph` method. The method should accept a `SymbolReference` argument instead of `string` and perform resolution while being aware of sections. This is much needed to factorize the code of section/paragraph resolution between CFG and CrossCompleteChecker.

**Comment by rooksdo** [comment]
> 
> 
> I re-read the issue discussion and I agree with @smedilol: we should not modify the test on the found list but rather change the `SymbolTable.GetParagraph` method. The method should accept a `SymbolReference` argument instead of `string` and perform resolution while being aware of sections. This is much needed to factorize the code of section/paragraph resolution between CFG and CrossCompleteChecker.

SymbolReference is not available when checking paragraph/declaration but I this solution will be implemented when checking `Perform Thru` declaration.

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs [hunk 3]
```diff
@@ -932,13 +932,25 @@ public static (SymbolType, Node) ResolveTargetSectionOrParagraph(Node callerNode
...
 
         private static void Check<T>(string nodeTypeName, T node, [NotNull] IList<T> found) where T : Node
         {
-            if (found.Count > 1)
-                DiagnosticUtils.AddError(node, nodeTypeName + " \'" + node.Name + "\' already declared");
+            //Check for duplicate declaration within the same owner
+            if (found.Count(p => p.SemanticData.Owner == node.SemanticData.Owner) > 1)
+            {
+                //Paragraphs can't have the same name within the same section
+                if (node is Paragraph)
```
[the remark this answers is not in the document]
Comment (rooksdo) [reply TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: Done => now using SemanticData.Kind to evaluate the node type.

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs [hunk 4]
```diff
@@ -932,13 +932,25 @@ public static (SymbolType, Node) ResolveTargetSectionOrParagraph(Node callerNode
...
-            IList<Paragraph> GetParagraphs() => callerNode.SymbolTable.GetParagraph(target.Name);
+            IList<Paragraph> GetParagraphs() => callerNode.SymbolTable.GetParagraph(target);
         }
 
         private static void Check<T>(string nodeTypeName, T node, [NotNull] IList<T> found) where T : Node
         {
-            if (found.Count > 1)
-                DiagnosticUtils.AddError(node, nodeTypeName + " \'" + node.Name + "\' already declared");
+            //Check for duplicate declaration within the same owner
+            if (found.Count(p => p.SemanticData.Owner == node.SemanticData.Owner) > 1)
```
[the remark this answers is not in the document]
Comment (rooksdo) [reply TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: Ok, resolution logic has changed in order to take into account the scope (procedure division or section) in which the perform statement is declared.

File: TypeCobol/Compiler/CodeModel/SymbolTable.cs [hunk 5]
```diff
@@ -734,10 +734,29 @@ internal void AddParagraph(Paragraph paragraph)
...
+                //Check if paragraph is qualified to filter the list
+                if (parRef.IsQualifiedReference)
+                {
+                    //Get section name
+                    var sectionName = ((QualifiedSymbolReference)parRef).Head.Name;
+                    //Check if there are any sections named sectionName
+                    if (Sections.TryGetValue(sectionName, out var sections))
+                    {
+                        //Return all paragraphs declared in a section named sectionName
+                        return values.Where(p => sections.Contains(p.Parent)).ToList(); //.ToList so the caller cannot modify our stored list
```
[the remark this answers is not in the document]
Comment (rooksdo) [reply TypeCobol/Compiler/CodeModel/SymbolTable.cs]: Ok, resolution logic has changed in order to take into account the scope (procedure division or section) in which the perform statement is declared.

File: TypeCobol.Test/Parser/Programs/Cobol85/ParagraphSection.rdz.cbl [hunk 6]
```diff
@@ -39,4 +39,30 @@
...
+           continue
+           .
+      *KO PAR01 is already declared
+       PAR01.
+           continue
+           .
+
+       SEC02 SECTION.
+
+       PAR01.
```
[the remark this answers is not in the document]
Comment (rooksdo) [reply TypeCobol.Test/Parser/Programs/Cobol85/ParagraphSection.rdz.cbl]: Ok, "OK" and "KO" statements are now all explicits in test input file.

File: TypeCobol/Compiler/CodeModel/SymbolTable.cs [hunk 7]
```diff
@@ -734,10 +734,25 @@ internal void AddParagraph(Paragraph paragraph)
             Add(Paragraphs, paragraph);
         }
 
-        public IList<Paragraph> GetParagraph(string name)
+        public IList<Paragraph> GetParagraph(SymbolReference parRef)
         {
-            Paragraphs.TryGetValue(name, out var values);
-            if (values != null) return values.ToList();  //.ToList so the caller cannot modify our stored list
+            //Retrieve all paragraphs having the same name as parRef
+            if (Paragraphs.TryGetValue(parRef.NameLiteral.Value, out var values))
```
Comment (fm-117) [inline TypeCobol/Compiler/CodeModel/SymbolTable.cs:740]: `parRef.Name`

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs [hunk 8]
```diff
@@ -12,6 +12,7 @@
 using TypeCobol.Compiler.Directives;
 using TypeCobol.Compiler.Scanner;
 using TypeCobol.Compiler.Symbols;
+using String = System.String;
```
Comment (fm-117) [inline TypeCobol/Compiler/Diagnostics/CrossChecker.cs:15]: Other using directives have not changed so this is certainly not needed. In any case if `String` is ambiguous, you can (and should 😄) use `string` keyword.

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs [hunk 9]
```diff
@@ -23,6 +24,7 @@ public CrossCompleteChecker([NotNull]TypeCobolOptions compilerOptions)
         }
 
         private readonly TypeCobolOptions _compilerOptions;
+        private Node _currentNodeScope;
```
Comment (fm-117) [inline TypeCobol/Compiler/Diagnostics/CrossChecker.cs:27]: Ok I'm not a huge fan of the name because to actually understand what this field refers to, you have to read the code where it is used. How about replacing that with a reference to the current section ? It would be null when the paragraph is declared directly in procedure division and set to the current section in `Visit(Section)` method like you did. Storing the `procedure division` node does not give anything and `private Node _currentSection` is clearer.

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs [hunk 10]
```diff
@@ -932,14 +972,11 @@ public static (SymbolType, Node) ResolveTargetSectionOrParagraph(Node callerNode
 
             IList<Section> GetSections() => callerNode.SymbolTable.GetSection(target.Name);
 
-            IList<Paragraph> GetParagraphs() => callerNode.SymbolTable.GetParagraph(target.Name);
+            IList<Paragraph> GetParagraphs() => callerNode.SymbolTable.GetParagraph(target);
         }
 
-        private static void Check<T>(string nodeTypeName, T node, [NotNull] IList<T> found) where T : Node
+        private static void CheckIsEmpty<T>(string nodeTypeName, T node) where T : Node
```
Comment (fm-117) [inline TypeCobol/Compiler/Diagnostics/CrossChecker.cs:978]: Well, the purpose is to check that it is _not_ empty I think.

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs [hunk 11]
```diff
@@ -970,12 +1007,46 @@ public static (SymbolType, Node) ResolveTargetSectionOrParagraph(Node callerNode
...
         {
-            Check("Paragraph", paragraph, paragraph.SymbolTable.GetParagraph(paragraph.Name));
+            //Get all paragraphs with the same name and having the same section name
+            var paragraphs = paragraph.SymbolTable.GetParagraphs(p => p.Name.Equals(paragraph.Name, StringComparison.OrdinalIgnoreCase) && p.SemanticData.Owner == paragraph.SemanticData.Owner).ToList();
+
+            //Paragraphs can't have the same name within the same section
+            if (paragraphs.Count > 1)
+            {
+                //Get the name of the scope to display in diagnostic message
+                var scope = paragraph.Parent.Name.Equals(String.Empty) ? paragraph.Parent.ID : paragraph.Parent.Name ;
```
Comment (fm-117) [inline TypeCobol/Compiler/Diagnostics/CrossChecker.cs:1038]: Use `string.IsNullOrEmpty(paragraph.Parent.Name)`

File: TypeCobol/Compiler/CodeModel/SymbolTable.cs (hunk 7 above)
Comment (rooksdo) [reply TypeCobol/Compiler/CodeModel/SymbolTable.cs:740]: parRef.NameLiteral.Value holds the value needed for the test as parRef.Name is actually the qualified name.

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs (hunk 9 above)
Comment (rooksdo) [reply TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: Done

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs (hunk 10 above)
Comment (rooksdo) [reply TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: Done

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs (hunk 11 above)
Comment (rooksdo) [reply TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: Done

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs (hunk 8 above)
Comment (rooksdo) [reply TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: Done

File: TypeCobol/Compiler/CodeModel/SymbolTable.cs (hunk 7 above)
Comment (fm-117) [reply TypeCobol/Compiler/CodeModel/SymbolTable.cs:740]: You're right `QualifiedSymbolReference` overrides the `Name` property.

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs [hunk 12]
```diff
@@ -910,19 +920,50 @@ public static (SymbolType, Node) ResolveTargetSectionOrParagraph(Node callerNode
...
+                            {
+                                //we're filtering out all paragraphs not declared in section scopeNode
+                                matchingParagraphs = paragraphs.Where(p => p.Parent == currentSection);
+                            }
+                            //Perform statement directly declared in the PROCEDURE DIVISION
+                            else
+                            {
+                                //we're filtering out all paragraphs that have a section
+                                matchingParagraphs = paragraphs.Where(p => p.Parent.SemanticData.Kind != Symbol.Kinds.Section);
+                            }
```
[the remark this answers is not in the document]
Comment (fm-117) [reply TypeCobol/Compiler/Diagnostics/CrossChecker.cs:954]: So does ths mean that we have to create a new 'Section' scope for SymbolTable or at least organize paragraphs by sections ?

[the remark this answers is not in the document]
Comment (smedilol) [reply TypeCobol/Compiler/Diagnostics/CrossChecker.cs:954]: No, you can pass argument "Section" to method GetParagraph.

File: TypeCobol.Test/Parser/Programs/Cobol85/ParagraphSection.rdzPGM.txt [hunk 13]
```diff
@@ -1,10 +1,37 @@
...
-Line 34[8,14] <37, Warning, General> - Warning: Paragraph 'Parag4' is empty
-Line 37[8,14] <37, Warning, General> - Warning: Paragraph 'Parag5' is empty
-Line 41[8,14] <37, Warning, General> - Warning: Paragraph 'Parag6' is empty
+Line 19[20,24] <30, Error, Semantics> - Semantic error: Ambiguous reference to paragraph PAR05 OffendingSymbol=[20,24:PAR05]<UserDefinedWord>
+Line 28[20,24] <30, Error, Semantics> - Semantic error: Ambiguous reference to paragraph PAR04 OffendingSymbol=[20,24:PAR04]<UserDefinedWord>
+Line 31[20,24] <30, Error, Semantics> - Semantic error: Ambiguous reference to procedure SEC05 OffendingSymbol=[20,24:SEC05]<UserDefinedWord>
+Line 37[20,24] <30, Error, Semantics> - Semantic error: Ambiguous reference to section SEC07 OffendingSymbol=[20,24:SEC07]<UserDefinedWord>
+Line 45[20,24] <30, Error, Semantics> - Semantic error: Ambiguous reference to paragraph PAR05 OffendingSymbol=[20,24:PAR05]<UserDefinedWord>
+Line 54[20,24] <30, Error, Semantics> - Semantic error: Ambiguous reference to paragraph PAR04 OffendingSymbol=[20,24:PAR04]<UserDefinedWord>
+Line 66[8,13] <27, Error, Syntax> - Syntax error : Paragraph 'PAR05' already declared in procedure-division
```
Comment (smedilol) [inline TypeCobol.Test/Parser/Programs/Cobol85/ParagraphSection.rdzPGM.txt:8]: Cobol allow you to define 2 paragraphs with the same name.
So this should not be an error but rather a warning.

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs [hunk 14]
```diff
@@ -24,6 +24,9 @@ public CrossCompleteChecker([NotNull]TypeCobolOptions compilerOptions)
 
         private readonly TypeCobolOptions _compilerOptions;
 
+        //Holds a reference to the last section node visited as to know in which current section we are
+        private Node _currentSection;
```
[the remark this answers is not in the document]
Comment (fm-117) [reply TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: done

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs (hunk 12 above)
[the remark this answers is not in the document]
Comment (fm-117) [reply TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: done

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs [hunk 15]
```diff
@@ -970,12 +1008,46 @@ public static (SymbolType, Node) ResolveTargetSectionOrParagraph(Node callerNode
...
+            if (sections.Count > 1)
+            {
+                DiagnosticUtils.AddError(section, $"Section \'{section.Name}\' already declared", MessageCode.Warning);
+            }
+
+            //Check if any paragraphs also have that name
+            var paragraphs = section.SymbolTable.GetParagraphs(p => p.Name.Equals(section.Name, StringComparison.OrdinalIgnoreCase)).ToList();
+            
+            //A section cannot have the same name as a paragraph
+            if (paragraphs.Count > 0)
```
[the remark this answers is not in the document]
Comment (fm-117) [reply TypeCobol/Compiler/Diagnostics/CrossChecker.cs:998]: done

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs [hunk 16]
```diff
@@ -970,12 +1008,46 @@ public static (SymbolType, Node) ResolveTargetSectionOrParagraph(Node callerNode
...
+                var scope = string.IsNullOrEmpty(paragraph.Parent.Name) ? paragraph.Parent.ID : paragraph.Parent.Name ;
+                DiagnosticUtils.AddError(paragraph, $"Paragraph \'{paragraph.Name}\' already declared in {scope}");
+            }
+
+            //Get all the sections with the same name as paragraph
+            var sections = paragraph.SymbolTable.GetSection(paragraph.Name);
+
+            //A paragraph cannot have the same name as a section
+            if(sections.Count > 0)
+                DiagnosticUtils.AddError(paragraph, $"Paragraph {paragraph.Name} is also declared as a section", MessageCode.SemanticTCErrorInParser);
```
[the remark this answers is not in the document]
Comment (fm-117) [reply TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: yes, done also

File: TypeCobol.Test/Parser/Programs/Cobol85/ParagraphSection.rdzPGM.txt (hunk 13 above)
Comment (fm-117) [reply TypeCobol.Test/Parser/Programs/Cobol85/ParagraphSection.rdzPGM.txt]: Changed to a Warning.
