### PR TITLE
WI #1459 Support when set to false / set to false

### LINKED ISSUE #1459: Cobol 6.2 : Support when set to false / set to false (without DFA)
# Support set to false
## Cobol
Support `when set to false` on level 88 variable and `set niv88 to false` statement.
See IBM Enterprise Cobol 6.2 for zOS language reference for specifications.

Correct Cobol example:
SetToFalseOk.rdz.cbl
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. SetToFalseOk.
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       SOURCE-COMPUTER. IBM-370
      *                WITH DEBUGGING MODE
                      .
       SPECIAL-NAMES.
           DECIMAL-POINT IS COMMA
           .
       DATA DIVISION.
       WORKING-STORAGE SECTION.

       01 Var1 pic X.
           88 Val1 value 'A' false 'B'.
           88 Val2 value 'B' false 'A'.
           88 Val3 value 'B' 'C' false IS 'A'.
           88 Val4 value 'C' when set to false is 'A'.
           88 Val5 value 'D' set false 'A'.
           88 Val6 value 'E' to false 'A'.
           88 Val7 value 'F' when false 'A'.
           88 Val8 value 'G' when to false 'A'.


       procedure division.
           set Val1 to true
           perform displayVar1AndVals

           set val2 to true
           perform displayVar1AndVals


           set Val1 to false
           perform displayVar1AndVals

           set Val2 to false
           perform displayVar1AndVals

           goback.
       displayVar1AndVals.
           evaluate true
              when Val1
                display "Val1 true, Var1=" Var1
              when Val2
                display "Val2 true, Var1=" Var1
           end-evaluate

           if(not Val1)
                display "Not Val1"
           else if (not Val2)
                display "Not Val2"
           end-if
           .
       END PROGRAM SetToFalseOk.
```

SetToFalseKO.rdz.cbl
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. SetToFalseKO.
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       SOURCE-COMPUTER. IBM-370
      *                WITH DEBUGGING MODE
                      .
       SPECIAL-NAMES.
           DECIMAL-POINT IS COMMA
           .
       DATA DIVISION.
       WORKING-STORAGE SECTION.
      
       01 VarA pic X.
           88 ValA-1 value 'A'.
           88 ValA-2 value 'B' false 'A'.
      *Ko No value
      *IBM compiler: "FALSE"was invalid in a level-88 item.
      *The level-88 item was discarded.
           88 ValA-3 false 'A'.
      *Same literal for value and false
      *No error from IBM compiler. Handle this with a quality tool.
           88 ValA-4 value 'A' false 'A'.
      
      *Some invalid syntax
        01 VarB pic X.
             88 ValB-3 value 'A' false.
             88 ValB-3 value 'A' is 'B'.
             88 ValB-3 value 'A' when set.
      
       procedure division.
      *Ko: no false clause defined for Val1
      *IBM compiler: A condition-name was specified in a"SET TO
      *FALSE" statement, but no"WHEN FALSE" value was defined for"VAR1".
      *The" SET"statement was discarded.
           set ValA-1 to false
      
      *As a level 88 must always have a value clause we don't
      *need to reproduce this error.
      *IBM compiler: An error was found in the definition of
      *condition-name "VALA-3".
      *The reference to this condition-name was discarded.
           set ValA-3 to true
      
           set ValA-4 to true
           set ValA-4 to false

      
           goback
           .
       END PROGRAM SetToFalseKO.
```

## TypeCobol
To simplify the codegen we must forbid a set to false that mix variable of type `bool` and level 88 with `false` clause.
Codegen can use `set to false` syntax. This will be done in #2534.
Otherwise except no change in codegen.

# Technical
## Cobol
- [ ] Check hardcoded test with level 88, DataCondition(Entry).
- [ ] move grammar of `setStatementForConditions` from `TypeCobolCodeElements.g4` to `CobolCodeElements.g4`
- [ ] Grammar for level 88 declaration
- [ ] Check where to store the false value in CodeElement
  - adding a `public Value FalseConditionValue { get; set; }` property in `DataConditionEntry`
- [ ] Remove limitation of set to false for Cobol in `TypeCobol.Compiler.Diagnostics.UnsupportedLanguageLevelFeaturesChecker.Check(SetStatementForConditions statement, CodeElementsParser.SetStatementForConditionsContext context)`
- [ ] There should be no change in `conditionalExpression` grammar
- [ ] When `set to false` is used, check that data has `false` clause
  - in CrossChecker on `Visit(SetStatement)`, add a part for checks related to `SetStatementForConditions` code element
- [ ] Bonus : replace hard coded test on Node with level 88 with test on `CodeElementType.DataConditionEntry`

## TypeCobol
- [ ] In `TypeCobolChecker` create a new check to forbid a `set to false` that mix variable of type `bool` and level 88 with `false` clause.
- [ ] Codegen : apply transformation of `set to false` only if receivers are of `type bool`. This can be bone by:
    - Set a flag in `TypeCobolChecker` when the previous check on `set to false` instruction is done
    - Adapt/create an `Attributes` (see Attributes class) to know if `receivers` are of type `Bool`. Only check the first receiver as all receiver must be of type Bool if the first is of type Bool.
    In `skeleton.xml` we could for example, write:
    `<condition node="TypeCobol.Compiler.Nodes.Set" isSetToFalse="yes" />`
    instead of:
    `<condition node="TypeCobol.Compiler.Nodes.Set" sender.type="BOOL" sender="FALSE"/>`

## DFA
NO DFA. It will be done in #2511.

## Quality rules
Note that we do not check compatibility between literals used in `VALUE` clause and the type of the parent definition. If we add this check, we'll have to check type compatibility for `FalseConditionValue` too.

# How to test automatically
Standard program test with Mix comparator.

### PR DESCRIPTION
**Pull request by efr15**
Fixes #1459 

Test case `tcSet` is modified because of removed check on `LanguageLevelChecker`: there is no more syntax error on `SET test1 TO FALSE`

### CODE REVIEW

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs [hunk 1]
```diff
@@ -150,9 +150,25 @@ public override bool Visit(Section section)
...
         {
-            SetStatementChecker.CheckStatement(setStatement);
+            if (set.StorageAreaWritesDataDefinition != null && set.CodeElement is SetStatementForConditions setConditions && setConditions.IsSendingValueFalse)
+            {
+                // Statement is a SET TO FALSE: we need to check that all conditions have been defined with a clause WHEN SET TO FALSE
+                foreach (var condition in setConditions.Conditions)
+                {
+                    if (condition.StorageArea != null)
+                    {
+                        set.StorageAreaWritesDataDefinition.TryGetValue(condition.StorageArea, out var dataCondition);
```
Comment (fm-117) [inline TypeCobol/Compiler/Diagnostics/CrossChecker.cs:162]: no test on return value of this `TryGetValue` ??? 👿
Ok this is written this way multiple times in the file and there is also `GetDataDefinitionFromStorageAreaDictionary` method which acts as a helper to do that. So I'm not sure anymore

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs [hunk 2]
```diff
@@ -150,9 +150,25 @@ public override bool Visit(Section section)
             return true;
         }
 
-        public override bool Visit(Set setStatement)
+        public override bool Visit(Set set)
         {
-            SetStatementChecker.CheckStatement(setStatement);
+            if (set.StorageAreaWritesDataDefinition != null && set.CodeElement is SetStatementForConditions setConditions && setConditions.IsSendingValueFalse)
```
Comment (fm-117) [inline TypeCobol/Compiler/Diagnostics/CrossChecker.cs:155]: Could this check be merged with the one added in `SetStatementChecker` to avoid iterating over conditions twice ?

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs [hunk 3]
```diff
@@ -652,6 +668,7 @@ public override bool Visit(DataDefinition dataDefinition)
 
             var commonDataDataDefinitionCodeElement = dataDefinitionEntry as CommonDataDescriptionAndDataRedefines;
 
+            var codeElementType = dataDefinitionEntry.Type;
```
Comment (fm-117) [inline TypeCobol/Compiler/Diagnostics/CrossChecker.cs:671]: Bonus: can be moved in inner scope.
Same thing for line 676 `var levelNumberValue` can be moved inside next `else` block

File: TypeCobol/Compiler/Diagnostics/TypeCobolChecker.cs [hunk 4]
```diff
@@ -6,6 +6,7 @@
 using TypeCobol.Compiler.Parser;
 using TypeCobol.Compiler.Parser.Generated;
 using TypeCobol.Compiler.Scanner;
+using static TypeCobol.Compiler.Nodes.Node;
```
Comment (fm-117) [inline TypeCobol/Compiler/Diagnostics/TypeCobolChecker.cs:9]: I'm no big fan of `using static` because it makes harder to read wich method comes from which class. As it is used only for the `Flag` enum, remove this using and prefix the Flag name with `Node.`

File: TypeCobol/Compiler/Diagnostics/TypeCobolChecker.cs [hunk 5]
```diff
@@ -885,6 +886,44 @@ public static void CheckStatement(Node node)
...
+            {
+                // Statement is a SET TO FALSE: check whether it mixes variables of type BOOL and Level 88
+                bool hasBool = false;
+                bool hasLevel88 = false;
+                string errorMessage = "The\"SET\"statement mixes variables of type BOOL and Level 88. This is not possible: please split it into 2 statements.";
+                foreach (var condition in setConditions.Conditions)
+                {
+                    if (condition.StorageArea != null)
+                    {
+                        node.StorageAreaWritesDataDefinition.TryGetValue(condition.StorageArea, out var dataCondition);
```
Comment (fm-117) [inline TypeCobol/Compiler/Diagnostics/TypeCobolChecker.cs:900]: Same remark. Ideally we should check the return value. But as it is used that way in other places...

File: TypeCobol/Compiler/Nodes/Attributes.cs [hunk 6]
```diff
@@ -56,6 +56,7 @@ public static class Attributes
             attributes["global"] = new GlobalAttribute();
             attributes["useglobalstoragevariable"] = new UseGlobalStorageVariableAttribute();
             attributes["sourceprogramhash"] = new SourceProgramHashAttribute();
+            attributes["isboolsettofalse"] = new IsBoolSetToFalseAttribute();
```
Comment (fm-117) [inline TypeCobol/Compiler/Nodes/Attributes.cs:59]: The name is not very clear, why not `istypecobolsettofalse` (and matching attribute and flag).

File: TypeCobol/Compiler/Parser/CodeElementBuilder/CobolCodeElementBuilder.cs [hunk 7]
```diff
@@ -1444,6 +1444,22 @@ private void EnterCommonDataDescriptionAndDataRedefines(CommonDataDescriptionAnd
...
+                {
+                    // TODO(?): handle strange case when FALSE context is set but equals to 'Missing FALSE'
+                    try
+                    {
+                        entry.FalseConditionValue = _cobolWordsBuilder.CreateValue(context.whenSetToFalse().value1());
+                    }
+                    catch (System.InvalidOperationException)
+                    {
+                        // Even if value1 context is set, value1 may be missing => crash in CreateValue
+                    }
```
Comment (fm-117) [inline TypeCobol/Compiler/Parser/CodeElementBuilder/CobolCodeElementBuilder.cs:1460]: Change `CreateValue` to return null. Builders should not crash, they build as much as they could, but they don't crash

**Review by fm-117 — CHANGES_REQUESTED** [review]

File: TypeCobol/Compiler/Diagnostics/TypeCobolChecker.cs (hunk 5 above)
Comment (smedilol) [reply TypeCobol/Compiler/Diagnostics/TypeCobolChecker.cs:900]: Yes we did the mistake in other places, but it's better to write new code correctly.
So can you check the return value of `TryGetValue` ?

File: TypeCobol/Compiler/Nodes/Attributes.cs (hunk 6 above)
Comment (smedilol) [reply TypeCobol/Compiler/Nodes/Attributes.cs:59]: +1 for name `istypecobolsettofalse`.

**Review by smedilol — CHANGES_REQUESTED** [review]

File: TypeCobol.Test/Parser/Programs/Cobol85/SetToFalse.Mix.txt [hunk 8]
```diff
@@ -0,0 +1,76 @@
...
+      ***************************************************************
+           set ok1 to false
+           set ok2 ok3 ok4 ok5 ok6 ok7 ok8 to false
+
+      ***************************************************************
+      * Expected error: clause WHEN SET TO FALSE is invalid/missing *
+      ***************************************************************
+
+      * OK for the 5 following conditions:
+Line 49[12,14] <27, Error, Syntax> - Syntax error : A condition-name was specified in a"SET TO FALSE"statement, but no"WHEN FALSE"value was defined for"ko3".The"SET"statement was discarded.
```
[the remark this answers is not in the document]
Comment (fm-117) [reply TypeCobol.Test/Parser/Programs/Cobol85/SetToFalse.Mix.txt:56]: And remove the part `The "SET" statement was discarded.` since it's not really meaningful.

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs (hunk 2 above)
Comment (efr15) [reply TypeCobol/Compiler/Diagnostics/CrossChecker.cs:155]: It is possible from a technical point of view.
But this check is related to Cobol and the one in `SetStatementChecker` is specific to TypeCobol.
As discussed it is better to keep them separate.

File: TypeCobol.Test/Parser/Programs/Cobol85/SetToFalse.Mix.txt [hunk 9]
```diff
@@ -0,0 +1,76 @@
...
+      * SET TO FALSE OK
+      ***************************************************************
+           set ok1 to false
+           set ok2 ok3 ok4 ok5 ok6 ok7 ok8 to false
+
+      ***************************************************************
+      * Expected error: clause WHEN SET TO FALSE is invalid/missing *
+      ***************************************************************
+
+      * OK for the 5 following conditions:
```
[the remark this answers is not in the document]
Comment (efr15) [reply TypeCobol.Test/Parser/Programs/Cobol85/SetToFalse.Mix.txt]: Comment changed: is it better now?

File: TypeCobol.Test/Parser/Programs/Cobol85/SetToFalse.Mix.txt [hunk 10]
```diff
@@ -0,0 +1,76 @@
...
+Line 50[12,14] <27, Error, Syntax> - Syntax error : A condition-name was specified in a"SET TO FALSE"statement, but no"WHEN FALSE"value was defined for"ko5".The"SET"statement was discarded.
+           set ko5 to false
+Line 51[12,14] <27, Error, Syntax> - Syntax error : A condition-name was specified in a"SET TO FALSE"statement, but no"WHEN FALSE"value was defined for"ko6".The"SET"statement was discarded.
+           set ko6 to false
+Line 52[12,14] <27, Error, Syntax> - Syntax error : A condition-name was specified in a"SET TO FALSE"statement, but no"WHEN FALSE"value was defined for"ko7".The"SET"statement was discarded.
+           set ko7 to false
+Line 53[12,14] <27, Error, Syntax> - Syntax error : A condition-name was specified in a"SET TO FALSE"statement, but no"WHEN FALSE"value was defined for"ko8".The"SET"statement was discarded.
+           set ko8 to false
+
+      * KO for the 3 following conditions:
```
[the remark this answers is not in the document]
Comment (efr15) [reply TypeCobol.Test/Parser/Programs/Cobol85/SetToFalse.Mix.txt]: Comment changed: is it better now?

File: TypeCobol.Test/Parser/Programs/Cobol85/SetToFalse.Mix.txt (hunk 8 above)
[the remark this answers is not in the document]
Comment (efr15) [reply TypeCobol.Test/Parser/Programs/Cobol85/SetToFalse.Mix.txt]: Done

File: TypeCobol.Test/Parser/Programs/TypeCobol/SetToFalse.Mix.txt [hunk 11]
```diff
@@ -0,0 +1,48 @@
...
+      *******************************************************
+         set VarBool-1 to false
+         set Var88-1 to false
+         set VarBool-1 VarBool-2 to false
+         set Var88-1 Var88-2 to false
+
+      *******************************************************
+      * SET TO FALSE KO because of mix type Bool + Level88
+      *******************************************************
+Line 33[10,49] <27, Error, Syntax> - Syntax error : The"SET"statement mixes variables of type BOOL and Level 88. This is not possible: please split it into 2 statements.
```
[the remark this answers is not in the document]
Comment (efr15) [reply TypeCobol.Test/Parser/Programs/TypeCobol/SetToFalse.Mix.txt]: Done

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs (hunk 3 above)
Comment (efr15) [reply TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: Done

File: TypeCobol/Compiler/CodeElements/Statement/SetStatement.cs [hunk 12]
```diff
@@ -353,6 +354,9 @@ public override bool VisitCodeElement(IASTVisitor astVisitor)
                 return variables;
             }
         }
+
+        /// <summary>Indicate whether the condition's value is defined and equals to FALSE</summary>
+        public bool IsSendingValueFalse => SendingValue != null && !SendingValue.Value;
```
[the remark this answers is not in the document]
Comment (efr15) [reply TypeCobol/Compiler/CodeElements/Statement/SetStatement.cs]: Done

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs (hunk 1 above)
Comment (efr15) [reply TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: `GetDataDefinitionFromStorageAreaDictionary` is indeed a good option.
However when used in a loop it will test in each call that dictionary is not null.
It is not necessary here.

So I keep `TryGetValue `and check its return value.

File: TypeCobol/Compiler/Diagnostics/TypeCobolChecker.cs (hunk 5 above)
Comment (efr15) [reply TypeCobol/Compiler/Diagnostics/TypeCobolChecker.cs]: Done

File: TypeCobol/Compiler/Nodes/Attributes.cs (hunk 6 above)
Comment (efr15) [reply TypeCobol/Compiler/Nodes/Attributes.cs]: Done

File: TypeCobol/Compiler/Parser/CodeElementBuilder/CobolCodeElementBuilder.cs (hunk 7 above)
Comment (efr15) [reply TypeCobol/Compiler/Parser/CodeElementBuilder/CobolCodeElementBuilder.cs]: Done

File: TypeCobol.Test/Parser/Programs/Cobol85/SetToFalse.Mix.txt [hunk 13]
```diff
@@ -0,0 +1,76 @@
...
+Line 27[32,34] <27, Error, Syntax> - Syntax error : missing FALSE at ''X''
+           88 ko4 value 'A' to 'X'.
+Line 28[34,36] <27, Error, Syntax> - Syntax error : mismatched input ''Y'' expecting {SET, FALSE, TO}
+           88 ko5 value 'A' when 'Y'.
+Line 29[34,35] <27, Error, Syntax> - Syntax error : mismatched input 'is' expecting {SET, FALSE, TO}
+           88 ko6 value 'A' when is 'Z'.
+Line 30[49,49] <27, Error, Syntax> - Syntax error : mismatched input '.' expecting {alphanumeric literal, numeric literal, figurative constant, keyword}
+           88 ko7 value 'A' when set to false is.
+      * Missing clause WHEN SET TO FALSE
+           88 ko8 value 'A'.
```
[the remark this answers is not in the document]
Comment (efr15) [reply TypeCobol.Test/Parser/Programs/Cobol85/SetToFalse.Mix.txt:41]: We don't expect an error in the declaration itself but SET this variable TO FALSE will fail because the clause WHEN SET TO FALSE is missing.
Comment changed: is it better now?

**Review by smedilol — APPROVED** [review]

File: TypeCobol.Test/Parser/Programs/Cobol85/SetToFalse.Mix.txt (hunk 13 above)
[the remark this answers is not in the document]
Comment (fm-117) [reply TypeCobol.Test/Parser/Programs/Cobol85/SetToFalse.Mix.txt:41]: yes

**Review by fm-117 — APPROVED** [review]
