### PR TITLE
WI #1200 Save SYNC alignment into a SyntaxProperty

### LINKED ISSUE #1200: Handle SYNC LEFT and RIGHT
**Describe the bug**
SYNC LEFT and SYNC RIGHT are allowed by our grammar but our CodeElement doesn't have the information.

**To Reproduce**
Cobol code that cause the bug : (if any)
```cobol
01 var1 pic X SYNC LEFT.
01 var2 pic X SYNC RIGHT.

TODO, I need a better test case
```

**Expected behavior**
CodeElementBuilder must use info about SYNC LEFT and RIGHT and put it in DataDescriptionEntry

### PR DESCRIPTION
**Pull request by fm-117**
Fixes #1200.

### CODE REVIEW

**Review by smedilol — DISMISSED** [review]

File: TypeCobol/Compiler/Diagnostics/TypeCobolChecker.cs [hunk 1]
```diff
@@ -535,15 +535,17 @@ private static void Check(Node node, [NotNull] FunctionCall call, [NotNull] IPro
...
                            string.Format(
                                "Function '{0}' expected parameter '{1}' {2} and received '{3}' {4}",
                                 call.FunctionName, expected.Name,
-                                expected.IsSynchronized ? "synchonized" : "not synchronized",
+                                expectedIsSynchronized ? "synchonized" : "not synchronized",
                                 callArgName ?? string.Format("position {0}", c + 1),
-                                actualDataDefinition.IsSynchronized ? "synchonized" : "not synchronized");
+                                actualIsSynchronized ? "synchonized" : "not synchronized");
                         DiagnosticUtils.AddError(node, m);
                     }
```
Comment (rooksdo) [inline TypeCobol/Compiler/Diagnostics/TypeCobolChecker.cs:551]: As discussed, it's a good idea to add an extra information regarding sync flags in the diagnostics :

- it will deliver more acute information
- we can then add a test to validate the PR

**Review by rooksdo — CHANGES_REQUESTED** [review]

File: TypeCobol/Compiler/Diagnostics/TypeCobolChecker.cs (hunk 1 above)
Comment (fm-117) [reply TypeCobol/Compiler/Diagnostics/TypeCobolChecker.cs:559]: See b2a09b3eb0592aa24286448eea0180cc57d9bbbf.

File: TypeCobol.Test/Parser/Programs/TypeCobol/ProcedureCall-ParamCompatibily.rdzMix.txt [hunk 2]
```diff
@@ -28,75 +30,93 @@
...
-           call proc3 input picNum10Sync 
+           call proc3  input picNum10Sync
+           call proc31 input picNum10SyncLeft
+           call proc32 input picNum10SyncRight
+           call proc3  input picNum10Sync
+           call proc31 input picNum10SyncLeft
+           call proc32 input picNum10SyncRight
+           call proc3  input picNum10Sync
+           call proc31 input picNum10SyncLeft
+           call proc32 input picNum10SyncRight
```
Comment (rooksdo) [inline TypeCobol.Test/Parser/Programs/TypeCobol/ProcedureCall-ParamCompatibily.rdzMix.txt:117]: I may be missing something, but it seems like the same test is repeated 3 times :
```cob
      *   Ok
           call proc3  input picNum10Sync
           call proc31 input picNum10SyncLeft
           call proc32 input picNum10SyncRight
```
As for error tests we should also have
```cob
      *   Ko
           call proc3  input picNum10SyncLeft
           call proc31 input picNum10SyncRight
           call proc32 input picNum10Sync
           call proc3  input picNum10SyncRight
           call proc31 input picNum10Sync
           call proc32 input picNum10SyncLeft
```

File: TypeCobol.Test/Parser/Programs/TypeCobol/ProcedureCall-ParamCompatibily.rdzSYM.txt [hunk 3]
```diff
@@ -116,6 +118,22 @@ LocalStorageData:
...
+  picNum10SyncLeft (.NET Type=VariableSymbol, Kind=Variable)
+  Flags: [LOCAL_STORAGE, Sync]
+  Owner: ProcedureCall-ParamCompatibily
+  Type:
+    (.NET Type=PictureType, Tag=Picture)
+    Picture: 9(10)
+  Level: 1
+  IsFiller: False
+  picNum10SyncRight (.NET Type=VariableSymbol, Kind=Variable)
+  Flags: [LOCAL_STORAGE, Sync]
```
Comment (rooksdo) [inline TypeCobol.Test/Parser/Programs/TypeCobol/ProcedureCall-ParamCompatibily.rdzSYM.txt:130]: @smedilol 
Should we store the information regarding Left/Right for Sync flag if specified?

**Review by rooksdo — CHANGES_REQUESTED** [review]

File: TypeCobol.Test/Parser/Programs/TypeCobol/ProcedureCall-ParamCompatibily.rdzSYM.txt (hunk 3 above)
Comment (smedilol) [reply TypeCobol.Test/Parser/Programs/TypeCobol/ProcedureCall-ParamCompatibily.rdzSYM.txt:130]: Yes we need this information to check our tests.

File: TypeCobol.Test/Parser/Programs/TypeCobol/ProcedureCall-ParamCompatibily.rdzMix.txt (hunk 2 above)
Comment (fm-117) [reply TypeCobol.Test/Parser/Programs/TypeCobol/ProcedureCall-ParamCompatibily.rdzMix.txt:117]: No ! Look at the definitions, `proc3`, `proc31` and `proc32` are different, they declare different parameters with either SYNC, SYNC LEFT or SYNC RIGHT so these are 3 different tests.

File: TypeCobol.Test/Parser/Programs/TypeCobol/ProcedureCall-ParamCompatibily.rdzSYM.txt (hunk 3 above)
Comment (fm-117) [reply TypeCobol.Test/Parser/Programs/TypeCobol/ProcedureCall-ParamCompatibily.rdzSYM.txt:130]: So after discussing with @sarterbe, he confirmed that `LEFT` or `RIGHT` has no impact. It is treated merely as documentation by the compiler but does not affect the runtime. Therefore it has no semantics.

Comment (smedilol) [reply TypeCobol.Test/Parser/Programs/TypeCobol/ProcedureCall-ParamCompatibily.rdzSYM.txt:130]: Ok, so it's ok with only `Sync`

File: TypeCobol.Test/Parser/Programs/TypeCobol/ProcedureCall-ParamCompatibily.rdzMix.txt (hunk 2 above)
Comment (rooksdo) [reply TypeCobol.Test/Parser/Programs/TypeCobol/ProcedureCall-ParamCompatibily.rdzMix.txt:117]: I think the same test (from line 88->90) is repeated again twice, that is from line 91->93 and again 94->96.

Comment (fm-117) [reply TypeCobol.Test/Parser/Programs/TypeCobol/ProcedureCall-ParamCompatibily.rdzMix.txt:117]: @rooksdo You're right ! Sorry I mixed up the combinations :man_facepalming:. Fixed with 2e6c1c04a671c2fcb3e38ab3bee786792a2bc939.

**Review by rooksdo — CHANGES_REQUESTED** [review]

File: TypeCobol.Test/Parser/Programs/TypeCobol/ProcedureCall-ParamCompatibily.rdzMix.txt [hunk 4]
```diff
@@ -28,75 +30,93 @@
...
       
       *    KO
-Line 35[12,38] <27, Error, Syntax> - Syntax error : Function 'proc1' expected parameter 'param1' with picture 9(10) and received 'picAlpha10' with picture X(10)
+Line 43[12,38] <27, Error, Syntax> - Syntax error : Function 'proc1' expected parameter 'param1' with picture 9(10) and received 'picAlpha10' with picture X(10)
            call proc1 input picAlpha10
       *OK
            call proc1 input picNum10
       *    KO
-Line 39[12,40] <27, Error, Syntax> - Syntax error : Function 'proc1' expected parameter 'param1' of usage  and received 'picNum10Comp' of usage Binary
+Line 47[12,40] <27, Error, Syntax> - Syntax error : Function 'proc1' expected parameter 'param1' of usage  and received 'picNum10Comp' of usage Binary
```
[the remark this answers is not in the document]
Comment (fm-117) [reply TypeCobol.Test/Parser/Programs/TypeCobol/ProcedureCall-ParamCompatibily.rdzMix.txt:48]: Maybe :see_no_evil:. But if so, it is not part of this issue, I haven't changed anything to the way diagnostics are created and this call does not use any SYNCed data or procedure param.

[the remark this answers is not in the document]
Comment (rooksdo) [reply TypeCobol.Test/Parser/Programs/TypeCobol/ProcedureCall-ParamCompatibily.rdzMix.txt:48]: Fair enough :)

**Review by rooksdo — APPROVED** [review]

**Review by smedilol — APPROVED** [review]
