### PR TITLE
WI #2520 Check variables used in EVALUATE / WHEN

### LINKED ISSUE #2520: Parser does not check conditions
**Describe the bug**
When using a variable in condition instead of a DataCondition (Level-88), the parser does not emit any diagnostic.

**To Reproduce**
(Type)Cobol code that cause the bug : (if any)
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. TCOMFL06.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 var1 PIC X.
          88 cond1 VALUE 'A'.
          88 cond1 VALUE 'B'.
       PROCEDURE DIVISION.
           IF (var1) THEN
              DISPLAY "This is definitely wrong"
           END-IF
           GOBACK
           .
       END PROGRAM TCOMFL06.
```

**Expected behavior**
Diagnostic expected at line 9 signaling an invalid condition.

**Technical**
New check to implement in CrossChecker. List all nodes that should be checked or find another way to factorize condition checks.

**How to test automatically**
Standard program parsing test.

### PR DESCRIPTION
**Pull request by efr15**
Fixes #2520

### CODE REVIEW

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs [hunk 1]
```diff
@@ -435,179 +435,210 @@ public override bool Visit(Search search)
...
+                        //else undefined reference
 
+                        return true;
+                    }
+                }
+            }
+            else if (when.Parent?.Parent is Evaluate evaluate) 
+            {
+                SelectionObject[] selectionObjects = when.CodeElement.SelectionObjects;
+                if (selectionObjects.Count() == 0)
```
Comment (fm-117) [inline TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: Avoid using LinQ `Count()` extension on arrays, use `Length` property instead

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs [hunk 2]
```diff
@@ -435,179 +435,210 @@ public override bool Visit(Search search)
...
+                {
+                    // Nothing in WHEN = nothing to do
                     return true;
                 }
+
+                SelectionSubject[] selectionSubjects = evaluate.CodeElement.SelectionSubjects;
+                if (selectionSubjects.Count() != selectionObjects.Count())
```
Comment (fm-117) [inline TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: Same remark

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs [hunk 3]
```diff
@@ -435,179 +435,210 @@ public override bool Visit(Search search)
...
+                {
+                    DiagnosticUtils.AddError(when, "The number of WHEN objects is not equal to the number of EVALUATE subjects");
```
Comment (fm-117) [inline TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: "The number of WHEN objects does not match the number of EVALUATE subjects"

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs [hunk 4]
```diff
@@ -435,179 +435,210 @@ public override bool Visit(Search search)
...
+                }
+                else
+                {
+                    // Check selection subject and object having the same ordinal position
+                    for (int index = 0; index < selectionSubjects.Count(); index++)
```
Comment (fm-117) [inline TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: use `Length`

File: TypeCobol.Test/Parser/Programs/Cobol85/EvaluateWhenCompatibility.PGM.txt [hunk 5]
```diff
@@ -0,0 +1,64 @@
+﻿--- Diagnostics ---
+Line 23[17,33] <27, Error, Syntax> - Syntax error : The object at position 0 in the "WHEN" phrase does not match the type of the corresponding subject in the "EVALUATE" statement
```
Comment (fm-117) [inline TypeCobol.Test/Parser/Programs/Cobol85/EvaluateWhenCompatibility.PGM.txt]: IBM compiler starts counting at 1 in its error message. So either modify the index reported in the message or better: use the names of the mismatching subjects/objects. that would always be clearer for the dev.

File: TypeCobol.Test/Parser/Programs/Cobol85/EvaluateWhenCompatibility.PGM.txt [hunk 6]
```diff
@@ -0,0 +1,64 @@
...
+Line 35[17,25] <27, Error, Syntax> - Syntax error : The object at position 0 in the "WHEN" phrase does not match the type of the corresponding subject in the "EVALUATE" statement
+Line 39[17,29] <27, Error, Syntax> - Syntax error : The object at position 0 in the "WHEN" phrase does not match the type of the corresponding subject in the "EVALUATE" statement
+Line 41[17,28] <27, Error, Syntax> - Syntax error : The object at position 0 in the "WHEN" phrase does not match the type of the corresponding subject in the "EVALUATE" statement
+Line 58[17,26] <27, Error, Syntax> - Syntax error : The object at position 0 in the "WHEN" phrase does not match the type of the corresponding subject in the "EVALUATE" statement
+Line 60[17,25] <27, Error, Syntax> - Syntax error : The object at position 0 in the "WHEN" phrase does not match the type of the corresponding subject in the "EVALUATE" statement
+Line 64[17,30] <27, Error, Syntax> - Syntax error : The object at position 0 in the "WHEN" phrase does not match the type of the corresponding subject in the "EVALUATE" statement
+Line 77[17,33] <27, Error, Syntax> - Syntax error : The literal A is compared to another literal A: this is not valid
```
Comment (fm-117) [inline TypeCobol.Test/Parser/Programs/Cobol85/EvaluateWhenCompatibility.PGM.txt]: Please add double quotes around literals for improved readability

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs [hunk 7]
```diff
@@ -1827,4 +1814,294 @@ private static DataDefinition GetDataDefinitionType(DataDefinition symbol, Symbo
...
+
+    // Specific Checker for Condition
+    static class ConditionChecker
+    {
+        // Structure gathering information about SelectionSubject (from EVALUATE) or SelectionObject (from WHEN)
+        private record SelectionInfo
+        {
+            // DataType computed from condition or expression
+            // Set to Unknown if condition or expression is not valid
+            public DataType DataType { get; init; }
```
Comment (fm-117) [inline TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: `init;` can be removed

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs [hunk 8]
```diff
@@ -1827,4 +1814,294 @@ private static DataDefinition GetDataDefinitionType(DataDefinition symbol, Symbo
...
+
+            // For numeric and alphanumeric values only
+            public string LiteralValue { get; init; }
```
Comment (fm-117) [inline TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: Same here

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs [hunk 9]
```diff
@@ -1827,4 +1814,294 @@ private static DataDefinition GetDataDefinitionType(DataDefinition symbol, Symbo
             }
         }
     }
+
+    // Specific Checker for Condition
+    static class ConditionChecker
+    {
+        // Structure gathering information about SelectionSubject (from EVALUATE) or SelectionObject (from WHEN)
+        private record SelectionInfo
```
Comment (fm-117) [inline TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: Optional: can be rewritten as `private record SelectionInfo(DataType DataType, string LiteralValue = null)` and removing the properties and constructors

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs [hunk 10]
```diff
@@ -1827,4 +1814,294 @@ private static DataDefinition GetDataDefinitionType(DataDefinition symbol, Symbo
...
+                LiteralValue = literalValue;
+            }
+
+            public SelectionInfo(DataType dataType) : this(dataType, null) { }
+
+            // TRUE for numeric and alphanumeric values only
+            public bool IsLiteral => LiteralValue != null;
+
+            /// <summary>
+            /// Determines whether the given object is conflicting with the current one by comparing their type.
```
Comment (fm-117) [inline TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: comparing their types

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs [hunk 11]
```diff
@@ -1827,4 +1814,294 @@ private static DataDefinition GetDataDefinitionType(DataDefinition symbol, Symbo
...
+            /// If both types are valid, a conflict occurs when one is Boolean and the other one not.
```
Comment (fm-117) [inline TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: the other isn't

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs [hunk 12]
```diff
@@ -1827,4 +1814,294 @@ private static DataDefinition GetDataDefinitionType(DataDefinition symbol, Symbo
...
+                        DiagnosticUtils.AddError(when, "The objects in the THRU phrase must be of the same data type");
+
+                        return (false, null, null);
+                    }
+                }
+
+                return (true, selectionObjectInfo, selectionObjectInfo2);
+            }
+
+            SelectionInfo GetSelectionInfo(Node node, BooleanValueOrExpression booleanComparisonVariable, VariableOrExpression alphanumericComparisonVariable)
```
Comment (fm-117) [inline TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: I would rather have this code as a private static method in `SelectionInfo` type along with two public `Create` methods, one accepting an `Evaluate` and a `SelectionSubject`, the other a `When` and a `SelectionObject`.

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs [hunk 13]
```diff
@@ -1827,4 +1814,294 @@ private static DataDefinition GetDataDefinitionType(DataDefinition symbol, Symbo
...
+
+                                    // Not valid (variable not referenced or mixed types)
+                                    return new SelectionInfo(DataType.Unknown);
+                                }
+
+                            default:
+                                // RelationCondition (for instance VAR1 = "A")
+                                return new SelectionInfo(DataType.Boolean);
+                        }
+                    }
```
Comment (fm-117) [inline TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: Why bother exploring the expression ? We could consider the DataType as boolean and let the other checkers decide whether the expression is correctly written. I'd like to avoid recursively checking every expression twice.

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs [hunk 14]
```diff
@@ -1827,4 +1814,294 @@ private static DataDefinition GetDataDefinitionType(DataDefinition symbol, Symbo
...
+                    if (selectionObjectInfo2 != null && selectionObjectInfo2.IsLiteral)
+                    {
+                        DiagnosticUtils.AddError(when, $"The literal {selectionObjectInfo2.LiteralValue} is compared to another literal {selectionSubjectInfo.LiteralValue}: this is not valid");
+                    }
+                }
+            }
+
+            (bool IsValid, SelectionInfo SelectionObjectInfo, SelectionInfo SelectionObjectInfo2) CheckWhen()
+            {
+                if (!CheckConditionalExpression(booleanComparisonVariable?.Expression, when, true))
```
Comment (fm-117) [inline TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: The `IsValid` and the new boolean return type of `CheckConditionalExpression` are used to avoid multiple diagnostics on same node. Is it required ? If it can be removed this would simplify the code.

**Review by fm-117 — CHANGES_REQUESTED** [review]

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs (hunk 13 above)
Comment (fm-117) [reply TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: Coud you test without the `case LogicalOperation` ? I agrre that we have to keep the first case so as to retrieve the actual DataType of the variable.

Comment (efr15) [reply TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: The case LogicalOperation is needed to handle valid syntax like `WHEN NOT VAR-ALPHA`.
In this case we have a `BooleanComparisonVariable `= `LogicalOperation `= {`Operator = NOT, LeftOperand = null, RightOperand = VAR-ALPHA`} and the result DataType should not be boolean.
You can see some examples of such syntax in:
https://github.com/TypeCobolTeam/TypeCobol/blob/9cce04a1906df1e34ff507d79542ec98ee56e008/TypeCobol.Test/ThirdParty/Nist/NC225A.cbl#L449-L450

**Review by Finou1404 — DISMISSED** [review]

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs (hunk 1 above)
Comment (efr15) [reply TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: Done

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs (hunk 2 above)
Comment (efr15) [reply TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: Done

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs (hunk 3 above)
Comment (efr15) [reply TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: Done

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs (hunk 4 above)
Comment (efr15) [reply TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: Done

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs (hunk 10 above)
Comment (efr15) [reply TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: Done

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs (hunk 11 above)
Comment (efr15) [reply TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: Done

File: TypeCobol.Test/Parser/Programs/Cobol85/EvaluateWhenCompatibility.PGM.txt (hunk 6 above)
Comment (efr15) [reply TypeCobol.Test/Parser/Programs/Cobol85/EvaluateWhenCompatibility.PGM.txt]: Done

File: TypeCobol.Test/Parser/Programs/Cobol85/EvaluateWhenCompatibility.PGM.txt (hunk 5 above)
Comment (efr15) [reply TypeCobol.Test/Parser/Programs/Cobol85/EvaluateWhenCompatibility.PGM.txt]: Done (IBM style)

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs (hunk 12 above)
Comment (efr15) [reply TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: Done. `Create `for `When `requires an additional parameter to distinguish  between `from `and `thru `expression of a range

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs (hunk 7 above)
Comment (efr15) [reply TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: Code removed

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs (hunk 8 above)
Comment (efr15) [reply TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: Code removed

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs (hunk 9 above)
Comment (efr15) [reply TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: Good! Done

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs (hunk 14 above)
Comment (efr15) [reply TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: Both are removed. No multiple diagnostics because not valid SelectionInfos are ignored in the type comparison.
There was a mix between null and Unknown for not valid SelectionInfo => now I always use Unknown.

Code is simpler but performance could be affected.
However, I think that in the nominal case, expressions should be simple (a variable or a literal), so this shouldn't be significant.

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs [hunk 15]
```diff
@@ -605,25 +605,25 @@ usedKey.Parent is DataDefinition parentUsedKey &&
...
                 else
                 {
                     // Check selection subject and object having the same ordinal position
-                    for (int index = 0; index < selectionSubjects.Count(); index++)
+                    for (int index = 0; index < selectionSubjects.Length; index++)
                     {
                         var selectionSubject = selectionSubjects[index];
                         var selectionObject = selectionObjects[index];
-                        ConditionChecker.CheckWhenStatement(evaluate, when, selectionSubject, selectionObject, index);
+                        ConditionChecker.CheckWhenStatement(evaluate, when, selectionSubject, selectionObject, index + 1);
```
Comment (fm-117) [inline TypeCobol/Compiler/Diagnostics/CrossChecker.cs:627]: Please add a comment explaining the `+ 1` on index.

**Review by fm-117 — CHANGES_REQUESTED** [review]
I think we should simplify the grammar using a single definition for `WHEN` code elements whether they appear in `EVALUATE` or `SEARCH`.
  - this should avoid odd cases where alphanumeric comparison variables/expressions are wrapped as `BooleanComparisonVariable`

We should also improve the checks performed on `ConditionalExpression` as we'll have multiple visits

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs [hunk 16]
```diff
@@ -1827,4 +1814,298 @@ private static DataDefinition GetDataDefinitionType(DataDefinition symbol, Symbo
...
+                }
+
+                // Variable
+                return GetSelectionInfoFromStorageArea(alphanumericComparisonVariable.StorageArea);
+
+                SelectionInfo GetSelectionInfoFromStorageArea(StorageArea storageArea)
+                {
+                    DataDefinition dataDefinition = node.GetDataDefinitionFromStorageAreaDictionary(storageArea, true);
+
+                    return new SelectionInfo(dataDefinition?.DataType ?? DataType.Unknown);
```
Comment (fm-117) [inline TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: `var dataType = dataDefinition?.DataType`;
return dataType != null ? new SelectionInfo(dataType) : Unknown;

**Review by fm-117 — CHANGES_REQUESTED** [review]

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs (hunk 15 above)
Comment (efr15) [reply TypeCobol/Compiler/Diagnostics/CrossChecker.cs:627]: Done

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs (hunk 16 above)
Comment (efr15) [reply TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: Done

**Review by fm-117 — DISMISSED** [review]

**Review by fm-117 — APPROVED** [review]
