### PR TITLE
WI #1622 Add unhandled exception handler.

### LINKED ISSUE #1622: Send notification for all logged exceptions
**Description**
Follow up to #518. 

Send a notification to TCOB taskforce for all logged exceptions. This generalizes the present behavior with CLI exceptions.
Thus all uncaught exceptions must be notified by LSP notification and by telemetry, from the LSP server.

### PR DESCRIPTION
**Pull request by mayanje**
A handler on Unhandled Exception has been added.
This feature will be testable using the following scenario.

- Issue https://github.com/TypeCobolTeam/TypeCobol/issues/1811 can be used for that purpose.
- In TypeCobol notification mail are only sent if the TypeCobol related version is a release version not a debug one.
- The current TypeCobol RDz Plugin does not send -t (Use statistics option) to the LSP server thus TFS issue 94607 must be fixed first for instance in develop branch and test RDz plugin develop version.

Fixes #1622

### CODE REVIEW

**Review by smedilol — APPROVED** [review]

File: TypeCobol.LanguageServer/JsonRPC/IRPCServer.cs [hunk 1]
```diff
@@ -29,5 +29,10 @@ public interface IRPCServer
         /// Write a trace in the server log file
         /// </summary>
         void WriteServerLog(string trace);
+
+        /// <summary>
+        /// An Unhandled Exception handler
+        /// </summary>
+        UnhandledExceptionEventHandler Handler { get; set; }
```
Comment (fm-117) [inline TypeCobol.LanguageServer/JsonRPC/IRPCServer.cs:36]: Maybe use an event instead of a delegate property ? It works but an event is more descriptive of what you want to achieve.
```csharp
event UnhandledExceptionEventHandler UnhandledException;
```

File: TypeCobol.LanguageServer/VsCodeProtocol/LanguageServer.cs [hunk 2]
```diff
@@ -41,15 +41,42 @@ public LanguageServer(IRPCServer rpcServer)
...
+        }
+
+        /// <summary>
+        /// Destructor.
+        /// </summary>
+        ~LanguageServer()
+        {
+            this.RpcServer.Handler -= UnhandledExceptionHandler;
+            AppDomain currentDomain = AppDomain.CurrentDomain;
+            currentDomain.UnhandledException -= UnhandledExceptionHandler;
```
Comment (fm-117) [inline TypeCobol.LanguageServer/VsCodeProtocol/LanguageServer.cs:59]: I don't think we need to use the `AppDomain.UnhandledException` event if we aready have our own logic for handling exceptions in the server object but we do have to ensure that this last chance handling is always safe so add a try-catch block around the `NotifyException` call in the handler.
Also why attempt to unregister the handler in a finalizer, the application is shutting down anyway.

**Review by fm-117 — CHANGES_REQUESTED** [review]

File: TypeCobol.LanguageServer/JsonRPC/IRPCServer.cs (hunk 1 above)
Comment (mayanje) [reply TypeCobol.LanguageServer/JsonRPC/IRPCServer.cs:36]: event is interresting if we sent events here we just use and handler for propagating already sent exceptions.

File: TypeCobol.LanguageServer/VsCodeProtocol/LanguageServer.cs (hunk 2 above)
Comment (mayanje) [reply TypeCobol.LanguageServer/VsCodeProtocol/LanguageServer.cs:59]: AppDomain.UnhandledException is interresting to capture all exceptions that we don't know yet.

Comment (mayanje) [reply TypeCobol.LanguageServer/VsCodeProtocol/LanguageServer.cs:59]: The destructor here to ensure safe programming.

File: TypeCobol.LanguageServer/JsonRPC/IRPCServer.cs (hunk 1 above)
Comment (fm-117) [reply TypeCobol.LanguageServer/JsonRPC/IRPCServer.cs:36]: Ok so the question is: which object shuld be responsible of the handling of those unhandled exceptions ?
If it is the IRPCServer instance itself then a method `void OnUnhandledException(Exception e)` in the interface is appropriate. If the handling should be done externally (and is optional) then an event is best.

Comment (mayanje) [reply TypeCobol.LanguageServer/JsonRPC/IRPCServer.cs:36]: If you mean that another one than LanguageServer can register itself to listen unhandled exception ok event mechanism shall be used, otherwise no use, only one handler shall be set.

Comment (fm-117) [reply TypeCobol.LanguageServer/JsonRPC/IRPCServer.cs:36]: No I mean a class different from the implementor of IRPCServer, which is the case here. LanguageServer handles the exceptions of JsonRPCServer.

Comment (mayanje) [reply TypeCobol.LanguageServer/JsonRPC/IRPCServer.cs:36]: First the fact is that class LanguageServer receives in its constructor an IRPCServer interface instance.
Declaring and even in the interface in IRPCServer, will make JsonRPCServer implementation provides add and remove method and then finally use a UnhandledExceptionEventHandler delegate instance.

So in this case event is the equivalent of the delegate UnhandledExceptionEventHandler, with less code using delegate.

File: TypeCobol.LanguageServer/VsCodeProtocol/LanguageServer.cs (hunk 2 above)
Comment (fm-117) [reply TypeCobol.LanguageServer/VsCodeProtocol/LanguageServer.cs:59]: Ok I think I see now, we have 2 kinds of scenarios: some exceptions are already handled but not properly notified (those are the ones in the various catch block of JsonRPCServer and we also have unpredictable exceptions (those can be handled with the AppDomain.UnhandledException event as a last resort. 

It would be best to remove the Handler property from IRPCServer interface and add a new parameter in JsonRPCServer constructor but it cannot currently easily be done. So ok to keep the property.

As for the destructor, I maintain my previous remark. There is no need to detach handling methods because in our current architecture, if LanguageServer dies, it means the whole process is exiting.

**Review by smedilol — APPROVED** [review]
For the desctructor, yes I agree that it's unuseful, but anyway it's working.

**Review by fm-117 — APPROVED** [review]

**Review by rooksdo — APPROVED** [review]
