### PR TITLE
2167 support procedure name in area a alternate solution

### LINKED ISSUE #2167: Support paragraph and section name that look like subtractions with no space
**Describe the bug**
**LINK WITH #1982**
In this issue we only focus on paragraph and section name.

**To Reproduce**
Cobol code that cause the bug : (if any)
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. MyPgm.
       data division.
       working-storage section.
      *Should be ok but outside the scope of this issue
       01 100-24X pic X.
      
       procedure division.
      *Should be ok but outside the scope of this issue
           initialize 100-24X
      
      *Ok
           perform 300-000-PAR1
      *Ok
           perform 300-000-SEC1
           goback.
      *Ok
       300-000-PAR1.
           exit.
      *Ok
       300-000-SEC1 section.
           exit.
       END PROGRAM MyPgm.
```

**Expected behavior**
No error for paragraph and section that contains number subtractions with no space

**Technical**
My ideas to handle this:
- In the scanner consider that characters without spaces are part of the same token if:
    - start at column 8
    - is not a keyword
    - is in procedure division
- After `perform` consider that all characters without spaces are part of the same token

### LINKED ISSUE #2258: INSERT doesn't accept range of numbers in its sequence-number-field
**Describe the bug**
Unlike DELETE, `INSERT` doesn't accept range of numbers in its sequence-number-field.

**To Reproduce**
Cobol code that cause the bug : (if any)
```cobol
       INSERT 000001-000005
```

**Expected behavior**
A diagnostic when a range is encountered.

**Technical**
See `CompilerDirectiveBuilder.EnterInsertCompilerStatement`.

**How to test automatically**
Existing test for INSERT in `TestCollection.CheckPreprocessor`.

### PR DESCRIPTION
**Pull request by smedilol**
I suggest an alternative solution to fix #2167.
Also I've seen that the limitation of #2167 is deliberate. It means we could handle all identifier that looks like a subtraction with no space #1982.

This PR also fixes #2258.

### CODE REVIEW

File: TypeCobol/Compiler/Scanner/Scanner.cs [hunk 1]
```diff
@@ -1445,9 +1446,53 @@ currentIndex < (lastIndex+1) && (line[currentIndex + 2] == '"' || line[currentIn
...
+                        return ScanCharacterString(startIndex);
+                    }
+
+                    //I use tokensLine.ScanState.AtBeginningOfSentence to match what is done by method ScanKeywordOrUserDefinedWord called by ScanCharacterString
+                    //
+                    //TODO check if the token is in area A
+                    //But beware, method ScanIsolatedToken in the Scanner use a Token with ColumnsLayout.FreeTextFormat. See TokensLine.CreateVirtualLineForInsertedToken(0, tokenText);
+                    //TODO create an issue for that
+                    //
+                    //Also ScanIsolatedToken receive a string which contains the text without the original spaces before the text. It means the new token generated is align to the left. The original column is lost.
```
Comment (fm-117) [inline TypeCobol/Compiler/Scanner/Scanner.cs:1480]: 'aligned'

File: TypeCobol/Compiler/Scanner/Scanner.cs [hunk 2]
```diff
@@ -1445,9 +1446,53 @@ currentIndex < (lastIndex+1) && (line[currentIndex + 2] == '"' || line[currentIn
...
+                        // Reset scanner state
+                        currentIndex = saveCurrentIndex;
+                        if (numericLiteralToken.TokenType == TokenType.InvalidToken)
+                        {
+                            tokensLine.ClearDiagnosticsForToken(numericLiteralToken);
+                        }
+                        //UserDefinedWord or PartialCobolWord
+                        return ScanCharacterString(startIndex);
+                    }
+                    //TODO this case should dissappear. This case only handles numericLiteralToken followed by a dash and (a letter or an underscore). E.g. "100-X"
```
Comment (fm-117) [inline TypeCobol/Compiler/Scanner/Scanner.cs:1494]: 'disappear'

**Review by fm-117 — CHANGES_REQUESTED** [review]

File: TypeCobol/Compiler/Scanner/Scanner.cs (hunk 2 above)
Comment (mayanje) [reply TypeCobol/Compiler/Scanner/Scanner.cs:1494]: With this PR the following code will fail:

```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. Pgm.
      
       PROCEDURE DIVISION.
           perform 300.
         300.
           exit.
       END PROGRAM Pgm.      
```

File: TypeCobol/Compiler/Scanner/Scanner.cs [hunk 3]
```diff
@@ -1445,9 +1446,53 @@ currentIndex < (lastIndex+1) && (line[currentIndex + 2] == '"' || line[currentIn
...
+                        return numericLiteralToken;
+                    }
+
+                    //TODO it's a basic code to handle #2167, but it seems easy to handle all UserDefinedWord with the form 123-456
+                    //Paragraph and section with name like "123" could also be handled this way
                     // 2. Then check to see if the next char would be valid inside a CobolWord
+                    bool nextCharIsDashFollowedByCobolChar = currentIndex < lastIndex && line[currentIndex] == '-' && CobolChar.IsCobolWordChar(line[currentIndex + 1]);
                     bool nextCharIsACobolWordChar = (currentIndex <= lastIndex) && CobolChar.IsCobolWordChar(line[currentIndex]);
-                    if(nextCharIsACobolWordChar && line[currentIndex] == '-')
+                    if (currentState.LastSignificantToken != null && (currentState.LastSignificantToken.TokenType == TokenType.PERFORM || currentState.LastSignificantToken.TokenType == TokenType.THRU || currentState.LastSignificantToken.TokenType == TokenType.THROUGH || currentState.LastSignificantToken.TokenType == TokenType.OF || currentState.LastSignificantToken.TokenType == TokenType.IN)
```
Comment (mayanje) [inline TypeCobol/Compiler/Scanner/Scanner.cs:1461]: So this is for COBOL only not TypeCobol, otherwise TokenType.QualifiedNameSeparator should be possible here.

Comment (smedilol) [reply TypeCobol/Compiler/Scanner/Scanner.cs:1461]: Yes I forgot TypeCobol.
But as discussed before, we'll now handle #1982, so I'll remove this test.

File: TypeCobol/Compiler/Scanner/Scanner.cs (hunk 2 above)
Comment (smedilol) [reply TypeCobol/Compiler/Scanner/Scanner.cs:1494]: Yes it fails, but `perform 300` is out of the scope of #2167 and even #1982.
I'll create an issue for this case and I also need to check if our code base use this syntax.

File: TypeCobol/Compiler/Scanner/Scanner.cs [hunk 4]
```diff
@@ -1423,9 +1423,10 @@ currentIndex < (lastIndex+1) && (line[currentIndex + 2] == '"' || line[currentIn
 
                 // LIMITATIONS :
                 // User defined words of the form 123E-4 or 123-4X are valid according to the spec but will not be supported 
-                // by this compiler. 
+                // by this compiler unless for paragraph and section and in perform statement.
```
[the remark this answers is not in the document]
Comment (smedilol) [reply TypeCobol/Compiler/Scanner/Scanner.cs]: Text removed with last commits.

File: TypeCobol/Compiler/Scanner/Scanner.cs [hunk 5]
```diff
@@ -1423,9 +1423,10 @@ currentIndex < (lastIndex+1) && (line[currentIndex + 2] == '"' || line[currentIn
...
                 // These cases are considered highly improbable, but we will have to check on a large body of existing programs.
                 // Purely numeric aragraph and section names are not supported.
+                // They
```
[the remark this answers is not in the document]
Comment (smedilol) [reply TypeCobol/Compiler/Scanner/Scanner.cs]: Text removed with last commits.

File: TypeCobol/Compiler/Scanner/Scanner.cs [hunk 6]
```diff
@@ -1445,9 +1446,53 @@ currentIndex < (lastIndex+1) && (line[currentIndex + 2] == '"' || line[currentIn
                     int saveCurrentIndex = currentIndex;
                     Token numericLiteralToken = ScanNumericLiteral(startIndex);
 
+                    //TODO It's a guess, it need to be tested
```
[the remark this answers is not in the document]
Comment (smedilol) [reply TypeCobol/Compiler/Scanner/Scanner.cs]: Text removed with last commits.

File: TypeCobol/Compiler/Scanner/Scanner.cs (hunk 1 above)
Comment (smedilol) [reply TypeCobol/Compiler/Scanner/Scanner.cs]: Text removed with last commits.

File: TypeCobol/Compiler/Scanner/Scanner.cs (hunk 3 above)
Comment (smedilol) [reply TypeCobol/Compiler/Scanner/Scanner.cs]: This code has been removed and is now generic for Cobol and TypeCobol.

File: TypeCobol.Test/Parser/Preprocessor/DirectiveResultFiles/Insert.txt [hunk 7]
```diff
@@ -17,8 +17,9 @@
 [24,29:000003]<IntegerLiteral>{3}
 
 -- Line 6 --
-*** DIRECTIVE INSERT 1 ([1,6:insert]<INSERT>[8,13:000001]<IntegerLiteral>{1}) ***
-[14,20:-000010]<IntegerLiteral>{-10}
+*** DIRECTIVE INVALID SYNTAX -> INSERT 0 ([1,6:insert]<INSERT>) ***
+[8,20:000001-000010]<UserDefinedWord>
+Line 6[8,20] <27, Error, Syntax> - Syntax error : mismatched input '000001-000010' expecting integer literal
```
Comment (fm-117) [inline TypeCobol.Test/Parser/Preprocessor/DirectiveResultFiles/Insert.txt:22]: Statement at line 6 seems syntactically correct. Is this a limitation introduced by this PR ?

File: TypeCobol.Test/Parser/Programs/Cobol85/SubtractionAsUserDefinedWord.rdzMix.txt [hunk 8]
```diff
@@ -0,0 +1,152 @@
...
+      *KO variable must contains at least one alphabetic char
+Line 9[12,18] <27, Error, Syntax> - Syntax error : Variable name must contain at least one alphabetic char.
+        01 400-500 pic 9.
+
+       procedure division.
+      *Should be KO. 400-500 is not a valid variable name because it
+      *   contains no alphabetic char
+      *   The parser will only report the error on the variable 
+      *   declaration.
+           compute a = 400-500
```
Comment (fm-117) [inline TypeCobol.Test/Parser/Programs/Cobol85/SubtractionAsUserDefinedWord.rdzMix.txt:17]: If it's currently ok for the parser, does it mean that it builds a compute statement and '400-500' becomes an arithmetic operation ?

File: TypeCobol.Test/Parser/Programs/Cobol85/SubtractionAsUserDefinedWord.rdzMix.txt [hunk 9]
```diff
@@ -0,0 +1,152 @@
...
+      *    procedure-name definition.
+      *    A blank was missing before character"X"in column 32.
+      *    A blank was assumed.
+Line 26[28,31] <27, Error, Syntax> - Syntax error : extraneous input '-200' expecting {separator, numeric literal, character string, symbol, statement starting keyword, keyword, Formalized Comments elements, Sql statement starting keyword}
+           compute a = 300 -200X-100X.
+           compute a = 300-200X - 100.
+           compute a = 300 - 200X-100X.
+      *KO  Expected a numeric data item or a numeric literal, but
+      *    found"300-100".  The"COMPUTE"statement was discarded.
+Line 31[12,30] <27, Error, Syntax> - Syntax error : Variable must contains at least one alphabetic char. For subtraction, please add spaces around minus operator: 300 - 100
```
Comment (fm-117) [inline TypeCobol.Test/Parser/Programs/Cobol85/SubtractionAsUserDefinedWord.rdzMix.txt:34]: The wording is a bit surprising. For a diagnostic message, i would expect something more formal like 'arithmetic operations require spaces around subtraction operator: 300 - 100'

File: TypeCobol.Test/Parser/Scanner/ResultFiles/UserDefinedWords.txt [hunk 10]
```diff
@@ -1,4 +1,4 @@
-﻿-- Line 1 --
+-- Line 1 --
```
Comment (fm-117) [inline TypeCobol.Test/Parser/Scanner/ResultFiles/UserDefinedWords.txt:1]: encoding change ?

File: TypeCobol/Compiler/CupCommon/CobolWordsTokenizer.cs [hunk 11]
```diff
@@ -271,7 +271,7 @@ public void EnterStopScanningModeIfNextNotToken(TokenType nextTokenType)
                 return;//Ignore if end of file
             Token nextToken = base.NextToken();
             base.PreviousToken();
-            if (nextToken != null && nextToken.TokenType != nextTokenType)
+            if (nextToken != null && nextTokenType.All(t=>t!=nextToken.TokenType))
```
Comment (fm-117) [inline TypeCobol/Compiler/CupCommon/CobolWordsTokenizer.cs:274]: Could you add spaces around '=>' ?

File: TypeCobol/Compiler/CupPreprocessor/CompilerDirectiveBuilder.cs [hunk 12]
```diff
@@ -241,41 +241,76 @@ public void EnterSequenceNumberField(List<Token> seqNumField)
...
 
-            bool isFirst = true;
-            int previous = -42;
-            foreach(Token integerLiteralToken in seqNumField)
-            {
-                System.Diagnostics.Debug.Assert(integerLiteralToken.TokenType == TokenType.IntegerLiteral);
-                int current = (int)((IntegerLiteralTokenValue)integerLiteralToken.LiteralValue).Number;
 
-                if (isFirst)
+            foreach(Token token in seqNumField)
```
Comment (fm-117) [inline TypeCobol/Compiler/CupPreprocessor/CompilerDirectiveBuilder.cs:245]: missing space after 'foreach'

File: TypeCobol/Compiler/CupPreprocessor/CompilerDirectiveBuilder.cs [hunk 13]
```diff
@@ -241,41 +241,76 @@ public void EnterSequenceNumberField(List<Token> seqNumField)
...
+                        if (int.TryParse(numbers[0], out var temp))
+                        {
+                            range.From = temp;
+                        }
+                        else
+                        {
+                            Diagnostic error = new Diagnostic(MessageCode.SyntaxErrorInParser, token.Position(), "Invalid value: " + numbers[0] + ". Excepted a positive integer.");
+                            CompilerDirective.AddDiagnostic(error);
+                            isOk = false;
+                        }
```
Comment (fm-117) [inline TypeCobol/Compiler/CupPreprocessor/CompilerDirectiveBuilder.cs:290]: Create a local function for this to factorize

File: TypeCobol/Compiler/Scanner/Scanner.cs [hunk 14]
```diff
@@ -1390,43 +1389,26 @@ currentIndex < (lastIndex+1) && (line[currentIndex + 2] == '"' || line[currentIn
...
-                // 123E-4 is a valid user defined word (for any type of name) AND a valid numeric literal (floating point format).
-                // 123-456 is a valid user defined word (fol section & paragraph names), AND it could be interpreted as two numeric literals,
-                //   NB: it is NOT a valid subtraction (minus must be preceded and followedf by space) but we would like to display a nice error 
-                //   message informing the user that these spaces are mandatory, because a subtraction was most likey intended in this case.
-                // 000010-000050 should be interpreted as a range of numbers (indicated by separating the two bounding numbers of the range 
-                //   by a hyphen) in sequence-number-fields of compiler directive statements (ex: DELETE).
-
+                // 000010-000050 is interpreted as a UserDefinedWord
+                //Depending on the context it could be
+                // - a range of numbers (for DELETE_CB)
```
Comment (fm-117) [inline TypeCobol/Compiler/Scanner/Scanner.cs:1394]: typo 'DELETE_CD'

File: TypeCobol/Compiler/Scanner/Scanner.cs [hunk 15]
```diff
@@ -1390,43 +1389,26 @@ currentIndex < (lastIndex+1) && (line[currentIndex + 2] == '"' || line[currentIn
...
+                //     - See sequence-number-fields of compiler directive statements
+                // - a paragraph name
+                //The scanner will then always match 000010-000050 as a UserDefinedWord.
+                //The check to be sure that a variable name contains at least alphabetic char
+                //must be done at CodeElement level.
```
Comment (fm-117) [inline TypeCobol/Compiler/Scanner/Scanner.cs:1399]: This is done in this PR right ? So the comment should be more affirmative: 'must be done' becomes 'is done'

File: TypeCobol/Compiler/Scanner/Scanner.cs [hunk 16]
```diff
@@ -1445,31 +1427,35 @@ currentIndex < (lastIndex+1) && (line[currentIndex + 2] == '"' || line[currentIn
                     int saveCurrentIndex = currentIndex;
                     Token numericLiteralToken = ScanNumericLiteral(startIndex);
 
-                    // 2. Then check to see if the next char would be valid inside a CobolWord
-                    bool nextCharIsACobolWordChar = (currentIndex <= lastIndex) && CobolChar.IsCobolWordChar(line[currentIndex]);
-                    if(nextCharIsACobolWordChar && line[currentIndex] == '-')
+
+                    // 2. a FloatingPointLiteral contains a character '.' or ',' which is invalid
+                    // in a UserDefinedWord or a keyword, so we can return this token directly.
+                    if (numericLiteralToken.TokenType == TokenType.FloatingPointLiteral)
```
Comment (fm-117) [inline TypeCobol/Compiler/Scanner/Scanner.cs:1433]: So this means that `ScanNumericLiteral` handles everything for FloatingPointLiteral ?

File: TypeCobol/Compiler/Text/CobolChar.cs [hunk 17]
```diff
@@ -22,6 +22,11 @@ public static bool IsCobolWordChar(char chr)
             return isCobolWordChar[(byte)chr];
         }
 
+        public static bool IsCobolAlphabeticChar(char chr)
+        {
+            return ('A' <= chr && chr <= 'Z') || ('a' <= chr && chr <= 'z');
```
Comment (fm-117) [inline TypeCobol/Compiler/Text/CobolChar.cs:27]: char.IsLetter ?

**Review by fm-117 — CHANGES_REQUESTED** [review]

File: TypeCobol.Test/Parser/Programs/Cobol85/SubtractionAsUserDefinedWord.rdzMix.txt (hunk 8 above)
Comment (smedilol) [reply TypeCobol.Test/Parser/Programs/Cobol85/SubtractionAsUserDefinedWord.rdzMix.txt:17]: No, it means `400-500` will be seen as a StorageArea.

File: TypeCobol/Compiler/Scanner/Scanner.cs (hunk 16 above)
Comment (smedilol) [reply TypeCobol/Compiler/Scanner/Scanner.cs:1433]: Yes

File: TypeCobol/Compiler/Text/CobolChar.cs (hunk 17 above)
Comment (smedilol) [reply TypeCobol/Compiler/Text/CobolChar.cs:27]: No because according to the doc https://docs.microsoft.com/fr-fr/dotnet/api/system.char.isletter?view=net-6.0#system-char-isletter(system-char) `IsLetter` is true for all Unicode letters. This includes `à`, `é` ...

File: TypeCobol.Test/Parser/Preprocessor/DirectiveResultFiles/Delete.txt [hunk 18]
```diff
@@ -29,20 +29,19 @@
 [14,14+:,]<CommaSeparator>
 
 -- Line 11 --
-*** DIRECTIVE DELETE 1->1 ([1,6:DELETE]<DELETE_CD>[8,13:000001]<IntegerLiteral>{1}) ***
-[14,14+:-]<MinusOperator>
+*** DIRECTIVE INVALID SYNTAX -> DELETE ([1,6:DELETE]<DELETE_CD>[8,14:000001-]<UserDefinedWord>) ***
+Line 11[8,14] <27, Error, Syntax> - Syntax error : Invalid value: . Excepted a positive integer.
```
[the remark this answers is not in the document]
Comment (smedilol) [reply TypeCobol.Test/Parser/Preprocessor/DirectiveResultFiles/Delete.txt]: Done in e705b29f87cea7244fae092d8bc7488e8de90876

File: TypeCobol.Test/Parser/Programs/Cobol85/SubtractionAsUserDefinedWord.rdzMix.txt (hunk 9 above)
Comment (smedilol) [reply TypeCobol.Test/Parser/Programs/Cobol85/SubtractionAsUserDefinedWord.rdzMix.txt]: Done in e705b29f87cea7244fae092d8bc7488e8de90876.
I choose `minus sign` instead of `subtraction operator` as it's the term used in the Cobol specs.
`Arithmetic operations requires spaces around minus sign: 300 - 100`

File: TypeCobol/Compiler/CupCommon/CobolWordsTokenizer.cs (hunk 11 above)
Comment (smedilol) [reply TypeCobol/Compiler/CupCommon/CobolWordsTokenizer.cs]: Done in e705b29f87cea7244fae092d8bc7488e8de90876

File: TypeCobol/Compiler/CupPreprocessor/CompilerDirectiveBuilder.cs (hunk 12 above)
Comment (smedilol) [reply TypeCobol/Compiler/CupPreprocessor/CompilerDirectiveBuilder.cs]: Done in e705b29f87cea7244fae092d8bc7488e8de90876

File: TypeCobol/Compiler/CupPreprocessor/CompilerDirectiveBuilder.cs (hunk 13 above)
Comment (smedilol) [reply TypeCobol/Compiler/CupPreprocessor/CompilerDirectiveBuilder.cs]: Done in e705b29f87cea7244fae092d8bc7488e8de90876

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs [hunk 19]
```diff
@@ -863,17 +864,23 @@ public static DataDefinition CheckVariable(Node node, StorageArea storageArea, b
...
             var found = foundQualified.Select(v => v.Value);
 
             var foundCount = found.Count();
 
             if (foundCount == 0)
             {
+                var plainUri = uri.ToString();
+                //Helper diagnostic for subtraction between numeric written without spaces around minus operator.
+                //Only do this diagnostic if the variable contains no alpha, because otherwise the most standard use case is simply an undefined variable.
+                if (plainUri.All(c=>Char.IsDigit(c) || c=='-'))
```
[the remark this answers is not in the document]
Comment (smedilol) [reply TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: Yes good remark, I've add new test to handle that.
Done in e705b29f87cea7244fae092d8bc7488e8de90876.
I've also seen unnecessary code that I changed in this commit. I can separate that in another PR if needed.

File: TypeCobol/Compiler/Scanner/Scanner.cs (hunk 14 above)
Comment (smedilol) [reply TypeCobol/Compiler/Scanner/Scanner.cs]: Done in e705b29f87cea7244fae092d8bc7488e8de90876

File: TypeCobol/Compiler/Scanner/Scanner.cs (hunk 15 above)
Comment (smedilol) [reply TypeCobol/Compiler/Scanner/Scanner.cs]: Done in e705b29f87cea7244fae092d8bc7488e8de90876

File: TypeCobol/Compiler/CupPreprocessor/CompilerDirectiveBuilder.cs [hunk 20]
```diff
@@ -241,41 +241,73 @@ public void EnterSequenceNumberField(List<Token> seqNumField)
...
+                        {
+                            range.From = temp;
+                            if (TryParseIntOrAddDiagnostic(numbers[1], out temp))
+                            {
+                                range.To = temp;
+                                deleteDirective.SequenceNumberRangesList.Add(range);
+                            }
+                        } //else ignore values
+
+                        bool TryParseIntOrAddDiagnostic(string invalidInteger, out int result)
```
Comment (fm-117) [inline TypeCobol/Compiler/CupPreprocessor/CompilerDirectiveBuilder.cs:287]: 'invalidInteger' ? It may be a valid integer text otherwise the method is pointless. Do you mean 'integerText' or 'numberText' ?

**Review by fm-117 — DISMISSED** [review]

File: TypeCobol.Test/Parser/Programs/Cobol85/SubtractionAsUserDefinedWord.rdzMix.txt (hunk 9 above)
Comment (fm-117) [reply TypeCobol.Test/Parser/Programs/Cobol85/SubtractionAsUserDefinedWord.rdzMix.txt]: 'require' with no 's'

File: TypeCobol/Compiler/Scanner/MultilineScanState.cs [hunk 21]
```diff
@@ -371,8 +372,18 @@ private void AdjustPreviousTokenPropertiesBasedOnCurrentToken(Token newToken)
...
+                    //DELETE is for Cobol statement
+                    //Scanner cannot differentiate these 2 DELETE keywords 
+
+                    //DELETE_CD is valid only if followed by an integer or a range of number.
+                    //A range of number is scanned as an UserDefinedWord
+                    //A range of number contains only numeric character or char '-'
                     case TokenType.DELETE:
-                        if (newToken.TokenType == TokenType.IntegerLiteral)
+                        if (newToken.TokenType == TokenType.IntegerLiteral
+                            || (newToken.TokenType == TokenType.UserDefinedWord && newToken.Text.All(c=>Char.IsDigit(c) || c=='-')))
```
Comment (fm-117) [inline TypeCobol/Compiler/Scanner/MultilineScanState.cs:386]: missing spaces around '=>' and '=='

File: TypeCobol/Compiler/CupPreprocessor/CompilerDirectiveBuilder.cs [hunk 22]
```diff
@@ -241,41 +241,73 @@ public void EnterSequenceNumberField(List<Token> seqNumField)
...
+                {
+                    Diagnostic error = new Diagnostic(MessageCode.SyntaxErrorInParser, token.Position(),
+                        $"Unexpected token: ${token} of type ${token.TokenType}");
+                    CompilerDirective.AddDiagnostic(error);
+                }
+
+                void AddInvalidIntegerDiagnostic(string invalidInteger)
+                {
+                    Diagnostic error = new Diagnostic(MessageCode.SyntaxErrorInParser, token.Position(),
+                        "Invalid value: " + invalidInteger + ". Expected a positive integer.");
```
[the remark this answers is not in the document]
Comment (smedilol) [reply TypeCobol/Compiler/CupPreprocessor/CompilerDirectiveBuilder.cs]: Done in 77275cd8b6d33d153ae576f927f10f78b8e9591b

File: TypeCobol/Compiler/Scanner/MultilineScanState.cs (hunk 21 above)
Comment (smedilol) [reply TypeCobol/Compiler/Scanner/MultilineScanState.cs]: Done in 77275cd8b6d33d153ae576f927f10f78b8e9591b

File: TypeCobol.Test/Parser/Programs/Cobol85/SubtractionAsUserDefinedWord.rdzMix.txt (hunk 9 above)
Comment (smedilol) [reply TypeCobol.Test/Parser/Programs/Cobol85/SubtractionAsUserDefinedWord.rdzMix.txt]: Done in 77275cd8b6d33d153ae576f927f10f78b8e9591b

**Review by fm-117 — APPROVED** [review]
