### PR TITLE
WI #2372 Improve accuracy of performance counters

### LINKED ISSUE #2372: Performance measure of our parser steps are not accurate
**Describe the bug**
See calls to `TypeCobol.Compiler.CompilationDocument.PerfStatsForCompilationStep.OnStartRefresh`, `TypeCobol.Compiler.CompilationDocument.PerfStatsForCompilationStep.OnStopRefresh`, `TypeCobol.Compiler.CompilationDocument.PerfStatsForParsingStep.OnStartRefreshParsingStep`, `TypeCobol.Compiler.CompilationDocument.PerfStatsForParsingStep.OnStopRefreshParsingStep`.

**Expected behavior**
Call to these methods should be done at the beginning/end of each method in `CompilationUnit/Document`.

**Technical**
Will be edited by a team member.
Implementation details with the chosen solution.

**How to test automatically**
Check the difference in our performance tests.

### PR DESCRIPTION
**Pull request by fm-117**
Fixes #2372.

### CODE REVIEW

File: TypeCobol/Compiler/CompilationDocument.cs [hunk 1]
```diff
@@ -643,9 +650,6 @@ public void RefreshProcessedTokensDocumentSnapshot()
                 // Start perf measurement
                 var perfStatsForParserInvocation = PerfStatsForPreprocessor.OnStartRefreshParsingStep();
```
Comment (smedilol) [inline TypeCobol/Compiler/CompilationDocument.cs:651]: This must be called at the beginning of the method.
Method `GetReducedAndOrderedChangesInNewerVersion` use iterator on the `ImmutableList` of Lines and it may be slow.

File: TypeCobol/Compiler/CompilationUnit.cs [hunk 2]
```diff
@@ -86,9 +89,6 @@ public void RefreshCodeElementsDocumentSnapshot()
                 // Start perf measurement
                 var perfStatsForParserInvocation = PerfStatsForCodeElementsParser.OnStartRefreshParsingStep();
```
Comment (smedilol) [inline TypeCobol/Compiler/CompilationUnit.cs:90]: This must be called at the beginning of the method.

File: TypeCobol/Compiler/CompilationDocument.cs [hunk 3]
```diff
@@ -541,6 +538,13 @@ public void UpdateTokensLines(System.Action onVersion = null)
                 PerfStatsForScanner.OnStopRefresh();
             }
 
+            if (scanAllDocumentLines)
```
Comment (smedilol) [inline TypeCobol/Compiler/CompilationDocument.cs:541]: Why move this code here ?

**Review by smedilol — CHANGES_REQUESTED** [review]

File: TypeCobol/Compiler/CompilationDocument.cs (hunk 3 above)
Comment (fm-117) [reply TypeCobol/Compiler/CompilationDocument.cs:541]: This code sends an event, it should be out of the `lock` statement.

File: TypeCobol/Compiler/CompilationDocument.cs (hunk 1 above)
Comment (fm-117) [reply TypeCobol/Compiler/CompilationDocument.cs]: ok done

File: TypeCobol/Compiler/CompilationUnit.cs (hunk 2 above)
Comment (fm-117) [reply TypeCobol/Compiler/CompilationUnit.cs]: changed

**Review by smedilol — APPROVED** [review]
