### PR TITLE
1440 improve level number detection in scanner

### LINKED ISSUE #1440: Completion on half written words
**Describe the bug**
The completion doesn't work fine when the type we try to complete is half written and the node not properly ended.

**To Reproduce**
(Type)Cobol code that cause the bug : (if any)
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. Callee.
      
       DATA DIVISION.
       working-storage section.
      
       01 STR.
           05 DATA1 PIC X.
           05 DATA2 TYPE B
           05 FILLER PIC X.
      
       PROCEDURE DIVISION.
      
       END PROGRAM Callee.
```
Try to complete variable DATA2 to "Bool".
When the B is written and we call autocompletion, it won't find anything. Yet, when nothing is written and call autocomplete, it gives all the possibilities.
After first analysis, there is no node associated to the line "05 DATA2 TYPE B"

**Expected behavior**
Autocompletion should return the compatible types.

### LINKED ISSUE #1655: Clean up csprojs after #1627
Continuation of #1627, some configurations (`OutputPath`) have been left out in `CSCup.csproj` and `CSCupRuntime.csproj` and should be removed.

### PR DESCRIPTION
**Pull request by fm-117**
Fixes #1440.
Fixes #1655.

### CODE REVIEW

File: TypeCobol/Compiler/Scanner/Scanner.cs [hunk 1]
```diff
@@ -1537,8 +1537,54 @@ private Token ScanNumericLiteral(int startIndex)
...
+                                token.CorrectType(TokenType.LevelNumber);
+                            }
+
+                            //This method is here to help recognize LevelNumbers when PeriodSeparator has been forgotten at the end of previous data definition.
+                            bool GuessIfCurrentTokenIsLevelNumber()
+                            {
+                                var lastSignificantToken = tokensLine.ScanState.LastSignificantToken;
+                                var beforeLastSignificantToken = tokensLine.ScanState.BeforeLastSignificantToken;
+
+                                bool currentTokenIsAtBeginningOfNewLine = token.Line == lastSignificantToken.Line + 1;
```
Comment (smedilol) [inline TypeCobol/Compiler/Scanner/Scanner.cs]: What if there is an empty line between   tokenand lastSignificantToken?

Comment (fm-117) [reply TypeCobol/Compiler/Scanner/Scanner.cs]: Good catch ! Fixed in latest commit.

File: TypeCobol/Compiler/Scanner/Scanner.cs [hunk 2]
```diff
@@ -1537,8 +1537,54 @@ private Token ScanNumericLiteral(int startIndex)
...
+                                bool currentTokenIsBeforeAreaB = token.Column < 12;
```
[the remark this answers is not in the document]
Comment (fm-117) [reply TypeCobol/Compiler/Scanner/Scanner.cs]: Issue #1666 has been created to deal with this kind of problem globally.
