### PR TITLE
WI #1690 index not referenced

### LINKED ISSUE #1690: Unexpected compile error for "INDEXED BY on redefined WORKING STORAGE area
A table defined in WORKING-STORAGE, that is REDEFINING another WORKING-STORAGE AREA, with "INDEXED BY" generates an error message of type 
"Syntax error : Symbol XXX is not referenced" for each statement on PROCEDURE DIVISION that references this INDEX

There was no DataDefinition/DataDescription for this INDEX.

This code compiles fines on z/OS compiler.

**To Reproduce**

1. Create an entry like this in working-storage section:

`05  W-ACTION                 PIC XX.
    05  W-RESULT                  PIC XX.
    05  W003-REQUESTS.
        10  W003-ACTION01-N               PIC 9.
        10  W003-ACTION02-N               PIC 9.
        10  W003-ACTION25-N               PIC X.
    05  W003-REQUESTS-CHAR          REDEFINES W003-REQUESTS
             OCCURS 3 TIMES INDEXED BY W003-IDX
                                          PIC X.

2. In procedure,:

PERFORM EA000-XX
        VARYING W003-INDX FROM CH-1 BY CH-1
            UNTIL W003-INDX GREATER THAN CH-NUM-REQ

**Expected behavior**
Have the appropriated DataDefinition/DataDescription created for this Index and no error messages relate to this on referenced statements.
```

### PR DESCRIPTION
**Pull request by rooksdo**
Closes #1690

### CODE REVIEW

File: TypeCobol/Compiler/CupParser/NodeBuilder/ProgramClassBuilder.cs [hunk 1]
```diff
@@ -523,11 +512,28 @@ public virtual void StartDataRedefinesEntry(DataRedefinesEntry entry)
...
 
+            //Add all index to symbol table
+            AddIndexToSymbolTableAll(entry, symbolTable);
+            
             Dispatcher.StartDataRedefinesEntry(entry);
 
             CheckIfItsTyped(node, node.CodeElement);
         }
 
+        public virtual void AddIndexToSymbolTableAll(CommonDataDescriptionAndDataRedefines entry, SymbolTable symbolTable)
```
Comment (smedilol) [inline TypeCobol/Compiler/CupParser/NodeBuilder/ProgramClassBuilder.cs]: As this method add Index to SymbolTable but also to the AST, I'd rather rename it CreateIndexAndAddToSymbolTable

Comment (rooksdo) [reply TypeCobol/Compiler/CupParser/NodeBuilder/ProgramClassBuilder.cs]: Done.
