### PR TITLE
WI #2356 Ensure "literal not correctly delimited" diagnostic is reported for continuation lines

### LINKED ISSUE #2356: Scanner diagnostics on continuation line are not reported
**Describe the bug**
Diagnostics added on a continuation line and not associated with a specific token are not reported.

**To Reproduce**
(Type)Cobol code that cause the bug : (if any)
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID.     MyPgm.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 Var1 pic X(08).
       PROCEDURE DIVISION.
      *    Error reported:
      *    "Syntax error: Literal is not correctly delimited"
           move
              "a  to Var1

      *    Error not repoted
           move
      -       "a  to Var1

           goback
           .
       end program MyPgm.
```

**Expected behavior**
Error reported correctly on continuation line.

**Technical**
In Scanner, see comment:
`// Then attribute each token and diagnostic to its corresponding tokens line`
We report diagnostics associated with tokens but not diagnostics associated with the `virtualContinuationTokensLine`.

**How to test automatically**
Standard pgm test.

### PR DESCRIPTION
**Pull request by fm-117**
Fixes #2356 

### About this PR:
The problem resides in the `TokensLine.AddDiagnostic` overload accepting direct positioning of diagnostic instead of token positioning. Diagnostics created using direct positioning cannot be copied from the virtual line onto the real line.

Out of the 19 usages of this 'unsafe' method:
- 8 are applied onto a real continuation line so we won't risk losing diags
- 6 are related to multiline or formalized comments which are TypeCobol specific
- 4 are potentially applied on virtual lines and then lost but do not actually concern virtual lines (indicator checks, max line size, both of which are non relevant in FreeFormat, this may evolve considering #2217 and #2357)
- the remaining usage is for "Literal not correctly delimited" and has been updated in this PR

### CODE REVIEW

**Comment by smedilol** [comment]
On top of this PR, isn't it possible to copy diagnostics on the virtual line into the original line.
I mean something like this in the method `void InitLine()`:
```C#
             originalLine.Diagnostics.AddRange(virtualContinuationTokensLine.Diagnostics);
```

File: TypeCobol/Compiler/Scanner/Scanner.cs [hunk 1]
```diff
@@ -1050,46 +1060,29 @@ public override Token GetTokenStartingFrom(int startIndex)
                         return new Token(TokenType.MultiplyOperator, startIndex, startIndex, tokensLine);
                     }
                 case '%':
-                    if (line.Length >= currentIndex + 2 && line[currentIndex + 1] == '>' && line[currentIndex + 2] == '>')
```
Comment (smedilol) [inline TypeCobol/Compiler/Scanner/Scanner.cs:1053]: This code is not useful anymore ?

Comment (fm-117) [reply TypeCobol/Compiler/Scanner/Scanner.cs:1053]: Yes and bugged.
The diagnostics for `WrongFormalizedCommentMarckupPosition` and `WrongMultilineCommentMarckupPosition` are created elsewhere:

https://github.com/TypeCobolTeam/TypeCobol/blob/ee6b01617bc4155372a9429b7c786729e4f7ebbd/TypeCobol/Compiler/Scanner/Scanner.cs#L874-L883

https://github.com/TypeCobolTeam/TypeCobol/blob/ee6b01617bc4155372a9429b7c786729e4f7ebbd/TypeCobol/Compiler/Scanner/Scanner.cs#L916-L925

And it does not concern starting tags but closing ones (and the check on index value is wrong too).

**Review by smedilol — APPROVED** [review]
