### PR TITLE
WI #1869 Remove IASTAnalyzer, use QualityAnalyzer concept instead

### LINKED ISSUE #1869: Add mechanism for external analyzers to check compiler-directing statements
### Description

Here are the following compiler-directing statements that we would like to check by an external analyzer :

-     ENTER, READY or RESET TRACE, and SERVICE RELOAD
-     Extended source library control (BASIS, DELETE, and INSERT statements)
-     Source text manipulation (COPY and REPLACE statements)
-     Exception handling and label handling (USE statement)
-     Controlling compiler listings (*CONTROL, *CBL, EJECT, TITLE, SKIP1, SKIP2, and SKIP3 statements)
-     Specifying compiler options (CBL and PROCESS statements)
-     Specifying COBOL exception handling procedures (USE statements)

@Todo cobol samples

### PR DESCRIPTION
**Pull request by fm-117**
Fixes #1869.

### CODE REVIEW

File: TypeCobol/Compiler/Parser/ProgramClassDocument.cs [hunk 1]
```diff
@@ -34,7 +34,7 @@ public ProgramClassDocument(TemporarySemanticDocument previousStepSnapshot, int
         /// <summary>
         /// Snapshot of the code elements document which was used to compute the current step
         /// </summary>
-        public IDocumentSnapshot<ICodeElementsLine> PreviousStepSnapshot { get; private set; }
+        public TemporarySemanticDocument PreviousStepSnapshot { get; private set; }
```
Comment (smedilol) [inline TypeCobol/Compiler/Parser/ProgramClassDocument.cs:37]: I think other `PreviousStepSnapshot` properties can in TemporarySemanticDocument , CodeElementsDocument, ... can use the most derived type to avoid cast in CompilationUnit.

**Review by smedilol — CHANGES_REQUESTED** [review]

File: TypeCobol/Compiler/Parser/ProgramClassDocument.cs (hunk 1 above)
Comment (fm-117) [reply TypeCobol/Compiler/Parser/ProgramClassDocument.cs:37]: With current code no, because this property is defined by `INextStepDocumentSnapshot<T>` as an `IDocumentSnapshot<T>`. C# does not allow (yet) override of inherited method return types. As for `ProgramClassDocument`, it does not implement `INextStepDocumentSnapshot` so I was ablet to change property type without impact.

**Review by smedilol — APPROVED** [review]

File: TypeCobol/Compiler/Parser/ProgramClassDocument.cs (hunk 1 above)
Comment (smedilol) [reply TypeCobol/Compiler/Parser/ProgramClassDocument.cs:37]: Ok.

**Review by rooksdo — APPROVED** [review]

**Review by mayanje — APPROVED** [review]

**Review by delevoye — APPROVED** [review]
