### PR TITLE
WI #2520 Check USAGE compatibility between EVALUATE and WHEN

### LINKED ISSUE #2520: Parser does not check conditions
**Describe the bug**
When using a variable in condition instead of a DataCondition (Level-88), the parser does not emit any diagnostic.

**To Reproduce**
(Type)Cobol code that cause the bug : (if any)
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. TCOMFL06.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 var1 PIC X.
          88 cond1 VALUE 'A'.
          88 cond1 VALUE 'B'.
       PROCEDURE DIVISION.
           IF (var1) THEN
              DISPLAY "This is definitely wrong"
           END-IF
           GOBACK
           .
       END PROGRAM TCOMFL06.
```

**Expected behavior**
Diagnostic expected at line 9 signaling an invalid condition.

**Technical**
New check to implement in CrossChecker. List all nodes that should be checked or find another way to factorize condition checks.

**How to test automatically**
Standard program parsing test.

### PR DESCRIPTION
**Pull request by efr15**
Fixes #2520

There is an issue with USAGE OBJECT REFERENCE.  The diagnostic below is wrong:
`Line 23[11,30] <27, Error, Syntax> - Syntax error : A group item cannot be empty. Add children, picture or valid usage (INDEX, COMP-1, COMP-2, POINTER, POINTER-32, PROCEDURE-POINTER or FUNCTION-POINTER). OffendingSymbol=[11,30:VAR-OBJECT-REFERENCE]
`
OBJECT REFERENCE should be part of the "stand alone" usages (see new issue created #2836)

### CODE REVIEW

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs [hunk 1]
```diff
@@ -1821,10 +1821,11 @@ static class ConditionChecker
     {
         // Structure gathering information about SelectionSubject (from EVALUATE) or SelectionObject (from WHEN):
         // DataType is computed from condition or expression and set to Unknown if not valid
+        // Usage is retrieved from the data definition (if relevant) or set to None
```
Comment (fm-117) [inline TypeCobol/Compiler/Diagnostics/CrossChecker.cs:1824]: set to None or `null` ? The signature uses a nullable type but apparently it can be removed.

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs [hunk 2]
```diff
@@ -1840,6 +1841,49 @@ public bool HasConflictingType(SelectionInfo other)
...
+            /// <returns>true if conflict</returns>
+            public bool HasConflictingUsage(SelectionInfo other)
+            {
+                var usage = Usage ?? DataUsage.None;
+                var otherUsage = other?.Usage ?? DataUsage.None;
+
+                // None and UTF-8 (which is not managed, see #2504) are ignored
+                if (otherUsage is DataUsage.None or DataUsage.UTF8) return false;
+
+                return usage switch
```
Comment (fm-117) [inline TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: Maybe testing equality of both usages before the switch will simplify a bit, removing the identity cases from the switch ?

**Review by fm-117 — CHANGES_REQUESTED** [review]

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs (hunk 1 above)
Comment (efr15) [reply TypeCobol/Compiler/Diagnostics/CrossChecker.cs:1824]: nullable removed

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs (hunk 2 above)
Comment (efr15) [reply TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: Done

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs [hunk 3]
```diff
@@ -1821,10 +1821,11 @@ static class ConditionChecker
     {
         // Structure gathering information about SelectionSubject (from EVALUATE) or SelectionObject (from WHEN):
         // DataType is computed from condition or expression and set to Unknown if not valid
+        // Usage is retrieved from the data definition (if relevant) or set to None
         // LiteralValue is only relevant for numeric and alphanumeric values
-        private record SelectionInfo(DataType DataType, string LiteralValue = null)
+        private record SelectionInfo(DataType DataType, DataUsage Usage, string LiteralValue = null)
```
Comment (fm-117) [inline TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: Optional: as most of the usages have the value `None` for Usage property, you can add a default value. Use the named parameter syntax for the cases where you have to pass a value for the literal without an Usage.

**Review by fm-117 — APPROVED** [review]

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs (hunk 3 above)
Comment (efr15) [reply TypeCobol/Compiler/Diagnostics/CrossChecker.cs]: Done

**Review by fm-117 — APPROVED** [review]

**Review by fm-117 — APPROVED** [review]

**Review by Finou1404 — APPROVED** [review]
