### PR TITLE
WI #2600 Fix NullReferenceException in Workspace.CollectDataLayoutNodes

### LINKED ISSUE #2600: NullReferenceException in Workspace.CollectDataLayoutNodes
**Describe the bug**
A `NullReferenceException` may be thrown by `Workspace.CollectDataLayoutNodes` method.

**To Reproduce**
No source code to reproduce.

**Expected behavior**
No exception.

**Technical**
See
https://github.com/TypeCobolTeam/TypeCobol/blob/c1fdd30b2ef12a68a93d2e5ea205dd19212702fd/TypeCobol.LanguageServer/Workspace.cs#L1103
This line should be protected against null values.

**How to test automatically**
TODO

### PR DESCRIPTION
**Pull request by efr15**
Fixes #2600

To reproduce the crash in a Cobol program: remove the . after IDENTIFICATION DIVISION

### CODE REVIEW

File: TypeCobol.LanguageServer/Workspace.cs [hunk 1]
```diff
@@ -1100,7 +1100,7 @@ static object GetEnd(long start, long length)
         private List<Tuple<int, DataDefinition, int>> CollectDataLayoutNodes(CompilationUnit compilationUnit)
         {
             var dataLayoutNodes = new List<Tuple<int, DataDefinition, int>>();
-            Node dataDivision = compilationUnit.TemporaryProgramClassDocumentSnapshot.Root.MainProgram.GetChildren<DataDivision>().FirstOrDefault();
+            Node dataDivision = compilationUnit?.TemporaryProgramClassDocumentSnapshot?.Root?.MainProgram?.GetChildren<DataDivision>()?.FirstOrDefault();
```
Comment (fm-117) [inline TypeCobol.LanguageServer/Workspace.cs:1103]: `compilationUnit`, `Root` and the result of `GetChildren<>` cannot be `null`. `TemporaryProgramClassDocumentSnapshot` should not be null either as we force node rebuilding. 

I'm ok to keep it like this safe approach but this will be changed if we move forward with the `#nullable` contexts.

**Review by fm-117 — APPROVED** [review]
