### PR TITLE
WI #2733 Fix InsertVariableDisplay mechanism to correctly align text following insertion point

### LINKED ISSUE #2733: InsertVariableDisplay does not correctly handle dots after statement
**Describe the bug**
When generating DISPLAY statements with `InsertVariableStatement` refactoring, the generated code may break Cobol program structure by inserting dots or existing statements in the columns 1-6 instead of AreaB.

**To Reproduce**
This is a ready-to-use `InsertVariableStatement` unit test
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. TCOMFL06.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 var1 PIC X(200).
       PROCEDURE DIVISION.
           DISPLAY "end of pgm".
       END PROGRAM TCOMFL06.
-------------------------------------------------------------------------------------------------
TypeCobol.LanguageServer.Commands.InsertVariableDisplay.InsertVariableDisplayRefactoringProcessor
-------------------------------------------------------------------------------------------------
[
    {
        "textDocument": { "uri": "file:/test.expected.cbl" },
        "position": { "line": 6, "character": 11 }
    },
    false,
    {
        "vm": 1, "idx": 0, "ch": [
            {
                "vm": 0, "name": "var1"
            }
        ]
    }
]
-------------------------------------------------------------------------------------------------
refactoring.label=Debug instructions successfully generated.
refactoring.source=
       IDENTIFICATION DIVISION.
       PROGRAM-ID. TCOMFL06.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 var1 PIC X(200).
       PROCEDURE DIVISION.
           DISPLAY "end of pgm"
      *<DBG>InsertVariableDisplay 1959/09/18 11:09 TESTUSER
      D    DISPLAY 'var1 <' var1 '>'
      *</DBG>
           .
       END PROGRAM TCOMFL06.
```

**Expected behavior**
See the test above. Code following the targeted statement will be moved but ultimately it should be written in an Area where it is allowed (instead of landing in column 1).

**Technical**
See how to handle the last line break in `CobolStringBuilder` ?

### PR DESCRIPTION
**Pull request by fm-117**
Fixes #2733

### CODE REVIEW

File: TypeCobol.LanguageServer/Commands/InsertVariableDisplay/InsertVariableDisplayRefactoringProcessor.cs [hunk 1]
```diff
@@ -147,19 +147,52 @@ private static GeneratedRoot GenerateDisplayStatements(DataSection dataSection,
...
         {
             Debug.Assert(node.CodeElement != null);
-            int line = node.CodeElement.Line;
-            int character = 0;
-            return TextEdit.Insert(new Position() { line = line, character = character }, code + Environment.NewLine);
+            int line = node.CodeElement.Line; // On same line and inserted text ends with a line break
+            string newText = code + Environment.NewLine;
+            int character = 0; // At beginning of the line, except when CodeElement is not the first
+
+            var firstToken = node.CodeElement.ConsumedTokens.FirstOrDefault();
```
Comment (efr15) [inline TypeCobol.LanguageServer/Commands/InsertVariableDisplay/InsertVariableDisplayRefactoringProcessor.cs:154]: Rename `firstToken `into `insertionToken `?

File: TypeCobol.LanguageServer/Commands/InsertVariableDisplay/InsertVariableDisplayRefactoringProcessor.cs [hunk 2]
```diff
@@ -147,19 +147,52 @@ private static GeneratedRoot GenerateDisplayStatements(DataSection dataSection,
...
         {
             Debug.Assert(node.CodeElement != null);
-            int line = node.CodeElement.LineEnd;
-            int character = node.CodeElement.StopIndex + 1;
-            return TextEdit.Insert(new Position() { line = line, character = character }, Environment.NewLine + code);
+            int line = node.CodeElement.LineEnd; // On same line and inserted text starts with a line break:
+            string newText = Environment.NewLine + code;
+            int character = node.CodeElement.StopIndex + 1; // At CodeElement end
+
+            var lastToken = node.CodeElement.ConsumedTokens.LastOrDefault();
```
Comment (efr15) [inline TypeCobol.LanguageServer/Commands/InsertVariableDisplay/InsertVariableDisplayRefactoringProcessor.cs:178]: Rename `lastToken `into `insertionToken `?

File: TypeCobol.LanguageServer/Commands/InsertVariableDisplay/InsertVariableDisplayRefactoringProcessor.cs (hunk 1 above)
Comment (fm-117) [reply TypeCobol.LanguageServer/Commands/InsertVariableDisplay/InsertVariableDisplayRefactoringProcessor.cs]: Done

File: TypeCobol.LanguageServer/Commands/InsertVariableDisplay/InsertVariableDisplayRefactoringProcessor.cs (hunk 2 above)
Comment (fm-117) [reply TypeCobol.LanguageServer/Commands/InsertVariableDisplay/InsertVariableDisplayRefactoringProcessor.cs]: and done

**Review by efr15 — APPROVED** [review]
