### PR TITLE
WI #1847 secure external analyzers

### LINKED ISSUE #1847: Improve parser security towards external analyzers
Following #1825.

The goal of this issue is to add defense mechanism (i.e. `try-catch` blocks) against exceptions thrown by external code analyzers.
While some steps are safe, not every external call is secured, check exceptions:
- at dynamic load
- when creating SyntaxDrivenAnalyzers / ASTAnalyzers
- during code analysis itself
  - Node phase
  - QualityCheck step

### PR DESCRIPTION
**Pull request by delevoye**
Closes #1847 

This PR does not handle the case of exceptions occuring in the SyntaxDrivenAnalyzers.
Removing this analyzer is possible and it will correct this part, see issue #1955.

### CODE REVIEW

File: TypeCobol/Analysis/AnalyzerProviderLoader.cs [hunk 1]
```diff
@@ -17,19 +19,28 @@ public static class AnalyzerProviderLoader
...
-                var provider = LoadProvider(assemblyFilePath);
-                compositeAnalyzerProvider.AddProvider(provider);
+                try
+                {
+                    var provider = LoadProvider(assemblyFilePath);
+                    compositeAnalyzerProvider.AddProvider(provider);
+                }
+                catch (Exception exception)
+                {
+                    File.AppendAllText(logFilePath, $"Failed to load analyzer provider on path {assemblyFilePath}\n{exception.Message}\n{exception}");
```
Comment (fm-117) [inline TypeCobol/Analysis/AnalyzerProviderLoader.cs:36]: Use `Environment.NewLine` instead of `\n` or use `File.AppendAllLines` to let the framework determine the newline separator. As for the error message, I would rather have

"Failed to load analyzer provider from path [path]."
"[exception.GetType().FullName] has been thrown."
"[exception.Message]"

Note: using `exception` in interpolated string will call its `ToString` method which usually return the exception type name but it may be redefined.

File: TypeCobol/Compiler/CompilationUnit.cs [hunk 2]
```diff
@@ -286,7 +286,17 @@ public void RefreshCodeAnalysisDocumentSnapshot()
...
                     Dictionary<string, object> results = new Dictionary<string, object>();
-                    var analyzers = _analyzerProvider?.CreateQualityAnalyzers(CompilerOptions);
+                    IQualityAnalyzer[] analyzers = null;
+                    try
+                    {
+                        analyzers = _analyzerProvider?.CreateQualityAnalyzers(CompilerOptions);
+                    }
+                    catch (Exception exception)
+                    {
+                        var diagnostic = new Diagnostic(MessageCode.AnalyzerFailure, Diagnostic.Position.Default, $"Error while creating quality analyzers with provider : {_analyzerProvider}", exception.Message, exception);
```
Comment (fm-117) [inline TypeCobol/Compiler/CompilationUnit.cs:296]: `_analyzerProvider` may be null here. I think you should create a local function `TryCreateQualityAnalyzers` and start with a code like `if (_analyzerProvider != null && TryCreateQualityAnalyzers(out var analyzers)` and then continue with the analysis itself.

File: TypeCobol/Analysis/AnalyzerProviderLoader.cs [hunk 3]
```diff
@@ -17,19 +19,28 @@ public static class AnalyzerProviderLoader
...
+                }
             }
         }
 
         /// <summary>
         /// Look for a suitable type into the assembly given and instantiate a new IAnalyzerProvider from it.
+        /// <remarks>Caller must catch potential exceptions.</remarks>
```
Comment (fm-117) [inline TypeCobol/Analysis/AnalyzerProviderLoader.cs:43]: Absolutely ! We can even emphasize this by renaming the method to `UnsafeLoadProvider` ?

File: TypeCobol/Analysis/AnalyzerProvider.cs [hunk 4]
```diff
@@ -70,14 +70,22 @@ private TAnalyzer[] Concat<TAnalyzer>(TAnalyzer[] fromBase, Func<IAnalyzerProvid
...
+                        var analyzers = selector(analyzerProvider);
+                        result.AddRange(analyzers);
+                    }
+                    catch (Exception e)
+                    {
+                        Console.WriteLine(e);
+                        throw;
+                    }
                 }
+
```
Comment (fm-117) [inline TypeCobol/Analysis/AnalyzerProvider.cs:88]: In fact, we don't have to change the `CompositeAnalyzerProvider`, we must secure the code at 3 locations:
- Load
- Create
- Call to analyzer itself

For load operations, it's ok with what you've done: the unsafe load is already try-catch protected and the `AddCustomProviders` is now safe.
For call to analyzer we are missing the protection on the call to `GetResult` for syntax-driven analyzers
For the create part, you secured the quality analyzer case in CompilationUnit.cs but we need to do the same for syntax-driven. So I would like you to reset `CompositeAnalyzerProvider` to its original state and add 2 try-catch blocks in `ProduceTemporarySemanticDocument` to secure the creation and result collection phases.

**Review by fm-117 — CHANGES_REQUESTED** [review]

**Review by fm-117 — CHANGES_REQUESTED** [review]

File: TypeCobol/Analysis/AnalyzerProviderLoader.cs (hunk 1 above)
Comment (delevoye) [reply TypeCobol/Analysis/AnalyzerProviderLoader.cs]: Message has been updated as suggested.

File: TypeCobol/Analysis/AnalyzerProviderLoader.cs (hunk 3 above)
Comment (delevoye) [reply TypeCobol/Analysis/AnalyzerProviderLoader.cs:43]: That's a good idea !

File: TypeCobol/Compiler/Parser/ProgramClassParserStep.cs [hunk 5]
```diff
@@ -129,7 +129,15 @@ public static void PrepareCupParser()
...
-                    diagnostics.AddRange(customAnalyzer.Diagnostics);
+                    try
+                    {
+                        diagnostics.AddRange(customAnalyzer.Diagnostics);
+                    }
+                    catch (Exception exception)
+                    {
+                        var diagnostic = new Diagnostic(MessageCode.AnalyzerFailure, Diagnostic.Position.Default, customAnalyzers.GetType().FullName, exception.Message, exception);
+                        diagnostics.Add(diagnostic);
+                    }
```
[the remark this answers is not in the document]
Comment (delevoye) [reply TypeCobol/Compiler/Parser/ProgramClassParserStep.cs]: See d5b452bb6b22a64724bdcdfe1d92251aeb60c83a.

File: TypeCobol.Analysis.Test/CfgTestUtils.cs [hunk 6]
```diff
@@ -49,7 +49,7 @@ static CfgTestUtils()
 
             void AddAnalyzerProvider(CfgBuildingMode mode)
             {
-                var analyzerProvider = new AnalyzerProvider();
+                var analyzerProvider = new AnalyzerProvider(str => throw new Exception(str));
```
[the remark this answers is not in the document]
Comment (delevoye) [reply TypeCobol.Analysis.Test/CfgTestUtils.cs]: See d5b452bb6b22a64724bdcdfe1d92251aeb60c83a.

File: CLI/src/CLI.cs [hunk 7]
```diff
@@ -122,11 +122,11 @@ private ReturnCode Compile()
             var rootSymbolTable = LoadIntrinsicsAndDependencies();
 
             //Add analyzers
-            var analyzerProvider = new CompositeAnalyzerProvider();
+            var analyzerProvider = new CompositeAnalyzerProvider(str => File.AppendAllText(_configuration.LogFile ?? TypeCobolConfiguration.DefaultLogFileName, str));
             var reports = RegisterAnalyzers(analyzerProvider);
 
             //Add external analyzers
-            analyzerProvider.AddCustomProviders(_configuration.CustomAnalyzerFiles);
+            analyzerProvider.AddCustomProviders(_configuration.CustomAnalyzerFiles, _configuration.LogFile ?? TypeCobolConfiguration.DefaultLogFileName);
```
[the remark this answers is not in the document]
Comment (delevoye) [reply CLI/src/CLI.cs]: See d5b452bb6b22a64724bdcdfe1d92251aeb60c83a.

File: TypeCobol/Analysis/AnalyzerProvider.cs [hunk 8]
```diff
@@ -15,21 +16,62 @@ public class AnalyzerProvider : IAnalyzerProvider
...
+                            syntaxDrivenAnalyzers.Add(sda);
+                        }
+                    }
+                    catch (Exception exception)
+                    {
+                        Logger($"Failed to create syntax driven analyzers from activator {sdaActivator.Method}.{Environment.NewLine}{exception.GetType().FullName} has been thrown.{Environment.NewLine}{exception.Message}");
+                    }
+                }
+            }
+            return syntaxDrivenAnalyzers.ToArray();
```
[the remark this answers is not in the document]
Comment (delevoye) [reply TypeCobol/Analysis/AnalyzerProvider.cs]: See f20f266b6c7f7d0ab495426694ff8214697e6a38.

File: TypeCobol/Analysis/AnalyzerProvider.cs [hunk 9]
```diff
@@ -15,21 +16,62 @@ public class AnalyzerProvider : IAnalyzerProvider
...
+            Logger = logger;
+        }
 
         public virtual ISyntaxDrivenAnalyzer[] CreateSyntaxDrivenAnalyzers(TypeCobolOptions options, TextSourceInfo textSourceInfo)
         {
-            return _sdaActivators?
-                .Select(sdaActivator => sdaActivator(options, textSourceInfo))
-                .Where(sda => sda != null)
-                .ToArray();
+            if (_sdaActivators == null) return new ISyntaxDrivenAnalyzer[]{};
```
[the remark this answers is not in the document]
Comment (delevoye) [reply TypeCobol/Analysis/AnalyzerProvider.cs]: See f20f266b6c7f7d0ab495426694ff8214697e6a38.

File: TypeCobol/Analysis/AnalyzerProvider.cs [hunk 10]
```diff
@@ -15,21 +16,62 @@ public class AnalyzerProvider : IAnalyzerProvider
...
+            var syntaxDrivenAnalyzers = new List<ISyntaxDrivenAnalyzer>();
+            foreach (var sdaActivator in _sdaActivators)
+            {
+                if (sdaActivator != null)
```
[the remark this answers is not in the document]
Comment (delevoye) [reply TypeCobol/Analysis/AnalyzerProvider.cs]: See f20f266b6c7f7d0ab495426694ff8214697e6a38.

File: TypeCobol/Compiler/CompilationUnit.cs [hunk 11]
```diff
@@ -228,8 +228,18 @@ public void ProduceTemporarySemanticDocument()
...
+                    Diagnostic exceptionDiagnostic = null;
+                    try
+                    {
+                        customAnalyzers = _analyzerProvider?.CreateSyntaxDrivenAnalyzers(CompilerOptions, TextSourceInfo);
+                    }
+                    catch (Exception exception)
+                    {
+                        Debug.Assert(_analyzerProvider != null);
+                        // Create a diagnostic to register it later when possible
+                        exceptionDiagnostic = new Diagnostic(MessageCode.AnalyzerFailure, Diagnostic.Position.Default, _analyzerProvider.GetType().FullName, exception.Message, exception);
```
[the remark this answers is not in the document]
Comment (delevoye) [reply TypeCobol/Compiler/CompilationUnit.cs]: See f20f266b6c7f7d0ab495426694ff8214697e6a38.

File: TypeCobol/Compiler/CompilationUnit.cs [hunk 12]
```diff
@@ -321,6 +347,26 @@ public void RefreshCodeAnalysisDocumentSnapshot()
...
+                        {
+                            try
+                            {
+                                createdAnalyzers = _analyzerProvider.CreateQualityAnalyzers(CompilerOptions);
+                                return true; // Analyzers have been created
+                            }
+                            catch (Exception exception)
+                            {
+                                var diagnostic = new Diagnostic(MessageCode.AnalyzerFailure, Diagnostic.Position.Default, $"Error while creating quality analyzers with provider : {_analyzerProvider.GetType().FullName}", exception.Message, exception);
+                                diagnostics.Add(diagnostic);
```
[the remark this answers is not in the document]
Comment (delevoye) [reply TypeCobol/Compiler/CompilationUnit.cs]: See f20f266b6c7f7d0ab495426694ff8214697e6a38.

File: TypeCobol/Analysis/AnalyzerProvider.cs [hunk 13]
```diff
@@ -10,103 +12,177 @@ namespace TypeCobol.Analysis
     /// <summary>
     /// IAnalyzerProvider default implementation. Can be used directly by adding activation delegates
     /// with the appropriate AddActivator method or by subclassing it.
+    /// It can also be used to allow composition of multiple providers into one.
+    /// This ensures that the creation of IAnalyzers won't interrupt the parsing.
```
Comment (fm-117) [inline TypeCobol/Analysis/AnalyzerProvider.cs:16]: 'This class also ensures', it's not related to the previous sentence about composition of providers.

File: TypeCobol/Analysis/AnalyzerProvider.cs [hunk 14]
```diff
@@ -10,103 +12,177 @@ namespace TypeCobol.Analysis
...
     /// </summary>
-    public class AnalyzerProvider : IAnalyzerProvider
+    public class AnalyzerProviderWrapper : IAnalyzerProvider
     {
+        /// <summary>
+        /// Method used to log exceptions.
+        /// <remarks>Should not be used directly, use the accessor Logger instead.</remarks>
+        /// </summary>
+        [NotNull]
```
Comment (fm-117) [inline TypeCobol/Analysis/AnalyzerProvider.cs:24]: The `[NotNull]` attribute should be placed on the protected property but not here.

File: TypeCobol/Analysis/AnalyzerProvider.cs [hunk 15]
```diff
@@ -10,103 +12,177 @@ namespace TypeCobol.Analysis
...
+        private Action<string> _logger = DoNothing;
+
+        /// <summary>
+        /// Method used to log exceptions.
+        /// </summary>
+        protected Action<string> Logger
+        {
+            get => _logger;
+            private set => _logger = value ?? DoNothing;
```
Comment (fm-117) [inline TypeCobol/Analysis/AnalyzerProvider.cs:33]: - the setter should be protected to let inheritors have a public parameterless constructor and later set the logger
- could you add parentheses around the assigned value: `set => _logger = (value ?? DoNothing);` it is unclear in the current form.

File: TypeCobol/Analysis/AnalyzerProvider.cs [hunk 16]
```diff
@@ -10,103 +12,177 @@ namespace TypeCobol.Analysis
...
     /// </summary>
-    public class AnalyzerProvider : IAnalyzerProvider
+    public class AnalyzerProviderWrapper : IAnalyzerProvider
     {
+        /// <summary>
+        /// Method used to log exceptions.
+        /// <remarks>Should not be used directly, use the accessor Logger instead.</remarks>
+        /// </summary>
+        [NotNull]
+        private Action<string> _logger = DoNothing;
```
Comment (fm-117) [inline TypeCobol/Analysis/AnalyzerProvider.cs:25]: No need to assign here, it is done in constructor.

File: TypeCobol/Analysis/AnalyzerProvider.cs [hunk 17]
```diff
@@ -10,103 +12,177 @@ namespace TypeCobol.Analysis
...
         /// <summary>
-        /// Add an activation delegate to produce a new instance of ISyntaxDrivenAnalyzer.
+        /// Create analyzers of the given type from providers and catch exceptions thrown.
+        /// <remarks>If the creation of an analyzer fails, it will fail the creation of all analyzers for this particular provider but not for the others.</remarks>
         /// </summary>
-        /// <param name="activator">Non-null Func delegate to create a new ISyntaxDrivenAnalyzer.</param>
-        public void AddActivator([NotNull] Func<TypeCobolOptions, TextSourceInfo, ISyntaxDrivenAnalyzer> activator)
+        /// <typeparam name="TAnalyzer">Type of IAnalyzer created.</typeparam>
+        /// <param name="createAnalyzers">Function to create analyzers from a provider.</param>
+        /// <returns>Non-null list of created analyzers. Might be empty and can contain null values.</returns>
```
Comment (fm-117) [inline TypeCobol/Analysis/AnalyzerProvider.cs:70]: But the first instruction returns `null`...

File: TypeCobol/Analysis/AnalyzerProvider.cs [hunk 18]
```diff
@@ -10,103 +12,177 @@ namespace TypeCobol.Analysis
...
         }
 
         /// <summary>
         /// Add an analyzer provider to this one.
         /// </summary>
         /// <param name="provider">Instance of IAnalyzerProvider.</param>
-        public void AddProvider(IAnalyzerProvider provider)
+        public void AddProvider([NotNull] IAnalyzerProvider provider)
         {
+            Debug.Assert(provider != null);
```
Comment (fm-117) [inline TypeCobol/Analysis/AnalyzerProvider.cs:174]: Either remove this assertion or add it for the 2 other AddActivator methods to improve consistency.

File: TypeCobol/Compiler/CompilationUnit.cs [hunk 19]
```diff
@@ -35,8 +34,16 @@ public class CompilationUnit : CompilationDocument
...
             PerfStatsForCodeQualityCheck = new PerfStatsForCompilationStep(CompilationStep.CodeQualityCheck);
+            if (analyzerProvider != null)
+            {
+                if (!(analyzerProvider is AnalyzerProviderWrapper analyzerProviderWrapper))
+                {
+                    analyzerProviderWrapper = new AnalyzerProviderWrapper();
+                    analyzerProviderWrapper.AddProvider(analyzerProvider);
+                }
+                _analyzerProvider = analyzerProviderWrapper;
+            }
```
Comment (fm-117) [inline TypeCobol/Compiler/CompilationUnit.cs:45]: It's correct but I think it would be clearer that way:
```csharp
if (analyzerProvider is AnalyzerProviderWrapper analyzerProviderWrapper)
{
    _analyzerProvider = analyzerProviderWrapper;
}
else if (analyzerProvider != null)
{
    _analyzerProvider = new AnalyzerProviderWrapper();
    _analyzerProvider.AddProvider(analyzerProvider);
}
else
{
    _analyzerProvider = null;
}
```

It's more verbose but it makes the possible values for the field more apparent.

In fact I wonder if we should allow `null` for the field. An empty wrapper could be used.

**Review by fm-117 — CHANGES_REQUESTED** [review]

**Review by fm-117 — CHANGES_REQUESTED** [review]
I'll let you change the CompilationUnit part and add comment in the wrapper class if needed, the rest is ok.

File: TypeCobol/Analysis/AnalyzerProvider.cs (hunk 18 above)
Comment (delevoye) [reply TypeCobol/Analysis/AnalyzerProvider.cs]: Assertion removed as the methods have the `[NonNull]` annotation.

File: TypeCobol/Compiler/CompilationUnit.cs (hunk 19 above)
Comment (delevoye) [reply TypeCobol/Compiler/CompilationUnit.cs]: The initialization is now more verbose.
Concerning allowing or not the value `null`, I think keeping it `null` stays in the spirit of the parser which is to have null instead of empty object.

**Review by fm-117 — APPROVED** [review]
