### PR TITLE
2246 integrate whenever statement

### LINKED ISSUE #2246: WHENEVER
Description

The [Whenever](https://www.ibm.com/docs/en/db2-for-zos/12?topic=statements-whenever) statement statement specifies the host language statement to be executed when a specified exception condition occurs.

This implies:

- To write the ANTLR grammar
- To write the CUP grammar
- Building the Whenever Statement CodeElement
- Building the Whenever Node
- Creating the corresponding Sql Object
- Making corresponding CodeElement, Node and SqlObject classes visitable
- Write test unit

### PR DESCRIPTION
**Pull request by laabidiHend**
Fixes #2246

### CODE REVIEW

File: TypeCobol/Compiler/Sql/CodeElements/Statements/WhenEverStatement.cs [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+    }
+    public enum NextStatementType
+    {
+        Continue,
+        Goto
+    }
+
+    public class WhenEverStatement : SqlStatementElement
+    {
+        public SymbolReference HostLabel { get; }
```
[the remark this answers is not in the document]
Comment (smedilol) [reply TypeCobol/Compiler/Sql/CodeElements/Statements/WhenEverStatement.cs:19]: After discussion : no, there is no need.
See grammar of Expression: https://www.ibm.com/docs/en/db2-for-zos/12?topic=elements-expressions

[the remark this answers is not in the document]
Comment (fm-117) [reply TypeCobol/Compiler/Sql/CodeElements/Statements/WhenEverStatement.cs:19]: HostLabel does not qualify as an expression in SQL, I think this is specific to this statement and not reusable in other contexts.

File: TypeCobol.Test/Parser/Programs/Cobol85/ExecSql/ExecSqlWithWhenEverStatement.rdzSQL.txt [hunk 2]
```diff
@@ -0,0 +1,20 @@
+﻿--- Diagnostics ---
+Line 10[14,21] <27, Error, Syntax> - Syntax error : mismatched input 'END-EXEC' expecting {':', user defined word} RuleStack=codeElement>whenEverStatement>sqlGotoHostLabel,  OffendingSymbol=[14,21:END-EXEC]<END_EXEC>
+
+--- Sql Statements ---
+line 6: WhenEverStatement
+- ExceptionCondition = Sqlerror
+- NextStatementType = Goto
+- HostLabel = ENDDATA
```
Comment (fm-117) [inline TypeCobol.Test/Parser/Programs/Cobol85/ExecSql/ExecSqlWithWhenEverStatement.rdzSQL.txt:8]: I wanted name changes, see [my remark](https://github.com/TypeCobolTeam/TypeCobol/issues/2246#issuecomment-1148476563) in issue.

File: TypeCobol/Compiler/Parser/CodeElementBuilder/CobolCodeElementBuilder.cs [hunk 3]
```diff
@@ -2280,5 +2280,10 @@ public override void EnterTruncateStatement([NotNull] CodeElementsParser.Truncat
             Context = context;
             CodeElement = _sqlCodeElementBuilder.CreateTruncateStatement(context);
         }
-    }
+        public override void EnterWhenEverStatement([NotNull] CodeElementsParser.WhenEverStatementContext context)
+        {
+            Context = context;
+            CodeElement = _sqlCodeElementBuilder.CreateWhenEverStatement(context);
+        }
+	}
```
Comment (fm-117) [inline TypeCobol/Compiler/Parser/CodeElementBuilder/CobolCodeElementBuilder.cs:2288]: indent (but this file uses mixed indent so i know it's complicated to catch all errrors at first sight)

File: TypeCobol/Compiler/Sql/CodeElements/Statements/WhenEverStatement.cs [hunk 4]
```diff
@@ -0,0 +1,36 @@
+﻿using TypeCobol.Compiler.CodeElements;
+
+namespace TypeCobol.Compiler.Sql.CodeElements.Statements
+{
+    public enum ExceptionConditionType
+    {
+        NotFound,
+        Sqlerror,
+        Sqlwarning
```
Comment (fm-117) [inline TypeCobol/Compiler/Sql/CodeElements/Statements/WhenEverStatement.cs:9]: SqlError, SqlWarning

**Review by fm-117 — CHANGES_REQUESTED** [review]

File: TypeCobol/Compiler/Sql/CodeElements/SqlCodeElementBuilder.cs [hunk 5]
```diff
@@ -283,5 +283,51 @@ private DatetimeConstant CreateDatetimeConstant(CodeElementsParser.Datetime_cons
...
+                        ParseTreeUtils.GetFirstToken(context.SQL_CONTINUE()));
+                }
+                else if (context.sqlGotoHostLabel() != null)
+                {
+                    nextStatementType = new SyntaxProperty<NextStatementType>(NextStatementType.Goto,
+                        ParseTreeUtils.GetFirstToken(context.sqlGotoHostLabel()));
+                    if (context.sqlGotoHostLabel().hostLabel != null)
+                    {
+                        hostLabel = new SymbolReference(
+                            new AlphanumericValue(context.sqlGotoHostLabel().hostLabel as Token),
```
[the remark this answers is not in the document]
Comment (laabidiHend) [reply TypeCobol/Compiler/Sql/CodeElements/SqlCodeElementBuilder.cs:322]: This will cause an error " context.sqlGotoHostLabel().hostLabel" is an IToken and not IParserTree node.

File: TypeCobol.Test/Utils/Comparator.cs [hunk 6]
```diff
@@ -533,6 +533,15 @@ public override bool Visit(TruncateStatement truncateStatement)
 
                 return true;
             }
+
+            public override bool Visit(WhenEverStatement whenEverStatement)
+            {
+                _writer.WriteLine($"line {whenEverStatement.Line}: {nameof(WhenEverStatement)}");
+                DumpObject(nameof(whenEverStatement.ExceptionCondition), whenEverStatement.ExceptionCondition);
+                DumpObject(nameof(whenEverStatement.BranchingType), whenEverStatement.BranchingType);
+                DumpObject(nameof(whenEverStatement.TargetSectionOrParagraph), whenEverStatement.TargetSectionOrParagraph);
```
Comment (fm-117) [inline TypeCobol.Test/Utils/Comparator.cs:542]: Now that i read it, could you merge the 2 methods `DumpObject`  and `DumpSqlObject` into a single one ?

File: TypeCobol/Compiler/CodeElements/StatementElement.cs [hunk 7]
```diff
@@ -134,7 +134,8 @@ public enum StatementType
         SelectStatement,
         RollbackStatement,
         TruncateStatement,
-        LockTableStatement
+        LockTableStatement,
+        WhenEverStatement
```
Comment (fm-117) [inline TypeCobol/Compiler/CodeElements/StatementElement.cs:138]: After the merge, the order is not the same in both enums `CodeElementType`  and `StatementType`. While it's not important, I'd like to have the same order to simplify reading. Could you change that please ?

File: TypeCobol/Compiler/Sql/CodeElements/SqlCodeElementBuilder.cs (hunk 5 above)
[the remark this answers is not in the document]
Comment (fm-117) [reply TypeCobol/Compiler/Sql/CodeElements/SqlCodeElementBuilder.cs:322]: Replace with direct cast.

**Review by fm-117 — CHANGES_REQUESTED** [review]

File: TypeCobol.Test/Utils/Comparator.cs [hunk 8]
```diff
@@ -484,35 +484,34 @@ public ASTVisitor(StringBuilder builder)
                 _writer = new StringWriter(builder);
             }
 
-            private void DumpSqlObject(string name, SqlObject sqlObject)
+            private void DumpObject(string name, SqlObject sqlObject, object @object)
```
Comment (fm-117) [inline TypeCobol.Test/Utils/Comparator.cs:487]: No. I had something in mind similar to `DumpProperty`.

```csharp
private void DumpProperty(string name, object value)
{
    _writer.Write($"- {name} = ");
    if (value == null)
    {
        _writer.WriteLine("<NULL>");
    }
    else if (value is SqlObject sqlObject)
    {
        sqlObject.Dump(_writer, 1);
    }
    else
    {
        _writer.WriteLine(value.ToString());
    }
}
```

**Review by fm-117 — CHANGES_REQUESTED** [review]

**Review by fm-117 — APPROVED** [review]
