### PR TITLE
WI #2306 Protect against NullReferenceException when reading NameLiteral property

### LINKED ISSUE #2306: NullPointerException in DiagnosticUtils.AddError(Node node, String message, SymbolReference symbol, MessageCode code)
**Describe the bug**
NullPointerException in DiagnosticUtils.AddError(Node node, String message, SymbolReference symbol, MessageCode code)    
```
   à TypeCobol.Compiler.Parser.DiagnosticUtils.AddError(Node node, String message, SymbolReference symbol, MessageCode code)    à TypeCobol.Compiler.Diagnostics.RedefinesChecker.OnNode(DataRedefines redefinesNode)    à TypeCobol.Compiler.Diagnostics.CrossCompleteChecker.Visit(DataRedefines dataRedefines)    à TypeCobol.Compiler.Nodes.DataRedefines.VisitNode(IASTVisitor astVisitor)    à TypeCobol.Compiler.Nodes.Node.AcceptASTVisitor(IASTVisitor astVisitor)    à TypeCobol.Compiler.Nodes.Node.VisitChildrens(IASTVisitor astVisitor, Boolean continueVisit, IEnumerable`1 childrenNodes)    à TypeCobol.Compiler.Nodes.Node.AcceptASTVisitor(IASTVisitor astVisitor)    à TypeCobol.Compiler.Nodes.Node.VisitChildrens(IASTVisitor astVisitor, Boolean continueVisit, IEnumerable`1 childrenNodes)    à TypeCobol.Compiler.Nodes.Node.AcceptASTVisitor(IASTVisitor astVisitor)    à TypeCobol.Compiler.Nodes.Node.VisitChildrens(IASTVisitor astVisitor, Boolean continueVisit, IEnumerable`1 childrenNodes)    à TypeCobol.Compiler.Nodes.Node.AcceptASTVisitor(IASTVisitor astVisitor)    à TypeCobol.Compiler.Nodes.Node.VisitChildrens(IASTVisitor astVisitor, Boolean continueVisit, IEnumerable`1 childrenNodes)    à TypeCobol.Compiler.Nodes.Node.AcceptASTVisitor(IASTVisitor astVisitor)    à TypeCobol.Compiler.Nodes.Node.VisitChildrens(IASTVisitor astVisitor, Boolean continueVisit, IEnumerable`1 childrenNodes)    à TypeCobol.Compiler.Nodes.Node.AcceptASTVisitor(IASTVisitor astVisitor)    à TypeCobol.Compiler.Nodes.Node.VisitChildrens(IASTVisitor astVisitor, Boolean continueVisit, IEnumerable`1 childrenNodes)    à TypeCobol.Compiler.Nodes.Node.AcceptASTVisitor(IASTVisitor astVisitor)    à TypeCobol.Compiler.Nodes.Node.VisitChildrens(IASTVisitor astVisitor, Boolean continueVisit, IEnumerable`1 childrenNodes)    à TypeCobol.Compiler.Nodes.Node.AcceptASTVisitor(IASTVisitor astVisitor)    à TypeCobol.Compiler.Parser.ProgramClassParserStep.CrossCheckPrograms(SourceFile root, TemporarySemanticDocument temporarySemanticDocument, TypeCobolOptions compilerOptions)    à TypeCobol.Compiler.CompilationUnit.RefreshProgramClassDocumentSnapshot()    à TypeCobol.LanguageServer.Workspace.<RefreshSyntaxTree>g__RefreshNodes|93_0(<>c__DisplayClass93_0& )    à TypeCobol.LanguageServer.Workspace.RefreshSyntaxTree(FileCompiler fileCompiler, SyntaxTreeRefreshLevel refreshLevel)    à TypeCobol.LanguageServer.Workspace.<>c__DisplayClass91_0.<TimerEvent>g__Refresh|0()    à TypeCobol.LanguageServer.TypeCobolServerHost.MessageHandler(IMessageHandler messageHandler, TypeCobolServer typeCobolServer)
```

symbol.NameLiteral is null ?

**To Reproduce**
No idea about the source code used.
```cobol

```

**Expected behavior**
No exception.

**Technical**
Will be edited by a team member.
Implementation details with the chosen solution.

**How to test automatically**
Will be edited by a team member.
Only if our current automated tests doesn't handle this.

### PR DESCRIPTION
**Pull request by fm-117**
Fixes #2306

The `NullReferenceException` regularly observed in the `AddError` method when checking `REDEFINES` may be caused by:
- either the `NameLiteral` being `null`
- or the `Token` of the `NameLiteral` being `null`.

This PR aims at fixing unsafe uses of `SymbolInformation.NameLiteral`.

### CODE REVIEW

File: TypeCobol/Compiler/Parser/CodeElementBuilder/CobolExpressionsBuilder.cs [hunk 1]
```diff
@@ -240,13 +239,21 @@ internal StorageArea CreateLinageCounterSpecialRegister(CodeElementsParser.Linag
...
             }
-            if (specialRegister.SymbolReference != null) {
-                CobolWordsBuilder.symbolInformationForTokens[specialRegister.SymbolReference.NameLiteral.Token] = specialRegister.SymbolReference;
+
+            var specialRegisterReference = specialRegister.SymbolReference;
+            var specialRegisterReferenceToken = specialRegisterReference?.NameLiteral?.Token;
+            if (specialRegisterReferenceToken != null)
+            {
+                CobolWordsBuilder.symbolInformationForTokens[specialRegisterReferenceToken] = specialRegisterReference;
             }
```
Comment (efr15) [inline TypeCobol/Compiler/Parser/CodeElementBuilder/CobolExpressionsBuilder.cs:255]: This code is repeated 3 times.
It could be factorized in a methode AddToSymbolInformation with this code:

```
        private void AddToSymbolInformation(SymbolDefinition specialRegisterName, SymbolReference specialRegisterReference)
        {
            var specialRegisterNameToken = specialRegisterName?.NameLiteral?.Token;
            if (specialRegisterNameToken != null)
            {
                CobolWordsBuilder.symbolInformationForTokens[specialRegisterNameToken] = specialRegisterName;
            }

            var specialRegisterReferenceToken = specialRegisterReference?.NameLiteral?.Token;
            if (specialRegisterReferenceToken != null)
            {
                CobolWordsBuilder.symbolInformationForTokens[specialRegisterReferenceToken] = specialRegisterReference;
            }
        }
```

Calll it like this;
`AddToSymbolInformation(specialRegister.DataDescriptionEntry?.DataName, specialRegister.SymbolReference);`

File: TypeCobol/Compiler/Parser/CodeElementBuilder/CobolWordsBuilder.cs [hunk 2]
```diff
@@ -803,7 +807,13 @@ internal SymbolReference CreateIndexNameReference(CodeElementsParser.QualifiedIn
...
             var reference = CreateQualifiedSymbolReference(new SymbolReference(headLiteral, SymbolType.IndexName), new SymbolReference(CreateAlphanumericValue(tail[0]), SymbolType.IndexName), false);
             for (int c = 1; c < tail.Length; c++) reference = CreateQualifiedSymbolReference(reference, new SymbolReference(CreateAlphanumericValue(tail[c]), SymbolType.IndexName), false);
-            symbolInformationForTokens[reference.NameLiteral.Token] = reference;
+
+            var token = reference.NameLiteral?.Token;
+            if (token != null)
+            {
+                symbolInformationForTokens[token] = reference;
+            }
+
```
Comment (efr15) [inline TypeCobol/Compiler/Parser/CodeElementBuilder/CobolWordsBuilder.cs:816]: This code is repeated 4 times. Similar factorization with method:
```
        private void AddToSymbolInformation(SymbolReference reference)
        {
            var token = reference.NameLiteral?.Token;
            if (token != null)
            {
                symbolInformationForTokens[token] = reference;
            }
        }
```

**Review by efr15 — CHANGES_REQUESTED** [review]

File: TypeCobol/Compiler/Parser/CodeElementBuilder/CobolExpressionsBuilder.cs (hunk 1 above)
Comment (fm-117) [reply TypeCobol/Compiler/Parser/CodeElementBuilder/CobolExpressionsBuilder.cs:255]: Yes ! This is much cleaner.

File: TypeCobol/Compiler/Parser/CodeElementBuilder/CobolWordsBuilder.cs (hunk 2 above)
Comment (fm-117) [reply TypeCobol/Compiler/Parser/CodeElementBuilder/CobolWordsBuilder.cs:816]: done

**Review by efr15 — APPROVED** [review]
