### PR TITLE
1808 report missing copies all levels ptd rebase

### LINKED ISSUE #1808: Complete the missing copies list with all levels of inclusion
**Only the first level of missing copies is displayed**
When a program references a copy that contains another copy, if the embedded copy is missing it won't display in the missing copy list.

**How to reproduce**
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. DVZZMFT0.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       COPY COPY1.
       PROCEDURE DIVISION.
           DISPLAY final-var OF group3 OF group2 OF group1
           GOBACK
           .
       END PROGRAM DVZZMFT0.    
```
COPY1
```cob
 01 group1.
       COPY COPY2.
```
COPY2
```cob
    05 group2.
          COPY COPY3.
```
COPY3
```cob
       10 group3.
                15 final-var PIC X.
```

**Expected result**
Missing copys at all levels of inclusion should be listed in the Missing Copies list.

### PR DESCRIPTION
**Pull request by fm-117**
Fixes #1808.
Rebase version of #1815.

### CODE REVIEW

**Review by smedilol — APPROVED** [review]

File: TypeCobol/Compiler/Diagnostics/DiagnosticMessage.cs [hunk 1]
```diff
@@ -52,12 +52,16 @@ internal DiagnosticMessage(Category category, int code, Severity severity, strin
...
 
-        public static IList<DiagnosticMessage> GetFromCode { get; private set; }
+        private static readonly Dictionary<MessageCode, DiagnosticMessage> _predefinedMessages;
+        public static DiagnosticMessage GetFromCode(MessageCode code)
+        {
+            System.Diagnostics.Debug.Assert(_predefinedMessages.ContainsKey(code));
+            return _predefinedMessages[code];
+        }
 
         static DiagnosticMessage()
```
Comment (mayanje) [inline TypeCobol/Compiler/Diagnostics/DiagnosticMessage.cs:62]: I think is time to make this static constructor thread safe, because I think that the first thread that will create a diagnostic will execute this code, but if will filling _predefinedMessages another thread creates a diagnostic there will be a concurrent access here, for instance LSR and Analyzers can be in differents threads, but's ok if it is same thread that run analyzers in the QualityCheck step. No other thread should create a diagnostics outside the compiler thread steps.

Comment (fm-117) [reply TypeCobol/Compiler/Diagnostics/DiagnosticMessage.cs:62]: Well, we're in luck then because static constructors are thread-safe in .NET. I could not find the doc reference but this is discussed [here](https://github.com/dotnet/docs/issues/10243). Basically first thread that needs to use the type will run the static constructor and other threads are on hold until the type is properly initialized.

Comment (mayanje) [reply TypeCobol/Compiler/Diagnostics/DiagnosticMessage.cs:62]: Ok so that's good.

**Review by mayanje — APPROVED** [review]
