### PR TITLE
WI #1642 Fix generating code for a variable of typedef using copy for…

### LINKED ISSUE #1642: Wrong generated code with Typedef using COPY
**Describe the bug**
In some cases Codegen will duplicate data definitions.

**To Reproduce**
Consider a copybook `TESTCPY.cpy`  and a main file `Client.tcbl`.

`TESTCPY.cpy`
```cobol
             10 varA-1 pic X.
             10 varA-2 pic X.
                15 varB-1 pic X.
             10 varA-3 pic X.
```

`Client.tcbl`
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. Client.
       data division.
       working-storage section.
       01 MyType typedef strict public.
          05  Data. COPY TESTCPY.
       01 myVar type MyType.
       PROCEDURE DIVISION.
           GOBACK.
       END PROGRAM Client.
```

The generated code will then contain in linkage section :
```cobol
       01 myVar.
           02 Data.
          05  Data. COPY TESTCPY.
```

**Expected behavior**
Same generation but without duplicated "Data".

Expected (Type)Cobol code : 
```cobol
       01 myVar.
           02 Data.
          COPY TESTCPY.
```

**Note** : the problem does not appear when the copy instruction is on separate line.

### PR DESCRIPTION
**Pull request by LANOYDO**
… data group; COPY in same line.
```cobol

       01 MyType typedef strict public.
          05  Data. COPY TESTCPY.
       01 myVar type MyType.
```
Fixes #1642.

### CODE REVIEW

File: Codegen/src/Nodes/TypedDataNode.cs [hunk 1]
```diff
@@ -986,7 +986,23 @@ public static List<ITextLine> InsertChildren(ColumnsLayout? layout, List<string>
                 {
                     if (child.IsFlagSet(Flag.IsTypedefCopyNode))
                     {
-                        lines.AddRange(child.Lines);
+                        var linesContent = child.CodeElement.SourceText.Split(new string[] { System.Environment.NewLine }, System.StringSplitOptions.None);                        //Indent the line according to its declaration
+                        foreach (string line in linesContent)
+                        {
+                            //Only the line containing copy can be badly indented. 
+                            string lineText;
+                            if (line.IndexOf("COPY", StringComparison.OrdinalIgnoreCase) >= 0)
```
Comment (smedilol) [inline Codegen/src/Nodes/TypedDataNode.cs]: Does it works with this kind of code:
```cobol
       01 MyType2 typedef strict public.
           05  MyData value "COPY". COPY TESTCPY.  
```

Comment (LANOYDO) [reply Codegen/src/Nodes/TypedDataNode.cs]: comlete TestTypeDefCopy with these statements.
https://github.com/TypeCobolTeam/TypeCobol/pull/1648/commits/37d27ab498b4f125c1de0768948140b5bc0232a0

File: Codegen/src/Nodes/TypedDataNode.cs [hunk 2]
```diff
@@ -986,7 +986,23 @@ public static List<ITextLine> InsertChildren(ColumnsLayout? layout, List<string>
...
+                            {
+                                //Indent this line with the same indentation than the declaring line.
+                                lineText = child.Lines.First().Text.GetIndent() + line.Trim();
+                            }
+                            else
+                            {
+                                //Otherwise generate the other lines as is, with a little extra for the columns 1-7
+                                lineText = new string(' ', 7) + line.TrimEnd();
+                            }
+                            lines.Add(new CobolTextLine(new TextLineSnapshot(-1, lineText, null), ColumnsLayout.CobolReferenceFormat));
```
Comment (fm-117) [inline Codegen/src/Nodes/TypedDataNode.cs]: This is a duplicate from `SignaturesGenerator.GenerateLinesForChildren`, could you look for a solution to factorize this code ?

**Comment by rooksdo** [comment]
Fixes #1642

File: CLI/test/CLITest.cs [hunk 3]
```diff
@@ -189,6 +189,16 @@ public void TestReplacingSyntaxOption()
             CLITestHelper.Test("return_code_4", ReturnCode.Warning);//1
         }
 
+        /// <summary>
+        /// Test Various Return Code that can be returned by the CLI
+        /// (with CLI arguments well formed, for bad argument test see TestArgumentsErrors())
+        /// </summary>
```
[the remark this answers is not in the document]
Comment (LANOYDO) [reply CLI/test/CLITest.cs]: done
https://github.com/TypeCobolTeam/TypeCobol/pull/1648/commits/d7ca7bdc7a90be21557826268a1c128e2a1b40e7

File: Codegen/src/Nodes/TypedDataNode.cs (hunk 2 above)
Comment (LANOYDO) [reply Codegen/src/Nodes/TypedDataNode.cs]: done
https://github.com/TypeCobolTeam/TypeCobol/pull/1648/commits/d7ca7bdc7a90be21557826268a1c128e2a1b40e7

File: CLI/test/CLITest.cs [hunk 4]
```diff
@@ -189,6 +189,16 @@ public void TestReplacingSyntaxOption()
             CLITestHelper.Test("return_code_4", ReturnCode.Warning);//1
         }
 
+        /// <summary>
+        /// Try parsing with copy is inside a typedef.
```
Comment (fm-117) [inline CLI/test/CLITest.cs]: 'when copy is inside a typedef' ? or 'with copy inside a typedef'

File: Codegen/src/GeneratorHelper.cs [hunk 5]
```diff
@@ -99,5 +101,35 @@ public static string ComputeIndexHashName(string qualified_name, Node sourceNode
             return hashName;
         }
 
+        /// <summary>
+        /// Return the list of indented lines of copy node declaration
+        /// </summary>
+        /// <param name="copyNode">Node copy</param>
+        /// <returns>The list of ITextLines.</returns>
+        public static List<ITextLine> GetCopyLines(Node copyNode)
```
Comment (fm-117) [inline Codegen/src/GeneratorHelper.cs]: - can be refactored into a deferred enumeration method (and also an extension method if you like)
- I think the input parameter can be more strictly typed as `LinearCopyNode`

File: CLI/test/CLITest.cs (hunk 4 above)
Comment (LANOYDO) [reply CLI/test/CLITest.cs]: modified: with copy inside a typedef.
https://github.com/TypeCobolTeam/TypeCobol/pull/1648/commits/31338d478e73bd6e55f1aca16dd21ebabd1e9eff

File: Codegen/src/GeneratorHelper.cs (hunk 5 above)
Comment (LANOYDO) [reply Codegen/src/GeneratorHelper.cs]: Now, it's a deferred enumeration method of the class LinearCopyNode.
https://github.com/TypeCobolTeam/TypeCobol/pull/1648/commits/31338d478e73bd6e55f1aca16dd21ebabd1e9eff

File: Codegen/src/GeneratorHelper.cs [hunk 6]
```diff
@@ -100,4 +100,4 @@ public static string ComputeIndexHashName(string qualified_name, Node sourceNode
         }
 
     }
-}
+}
```
Comment (fm-117) [inline Codegen/src/GeneratorHelper.cs]: No need to change the file.

File: Codegen/src/Generators/LinearNodeSourceCodeMapper.cs [hunk 7]
```diff
@@ -263,6 +261,30 @@ internal class LinearCopyNode : LinearTokensNode
             public LinearCopyNode(CodeElement CodeElement) : base(CodeElement)
             {
             }
+
+            /// <summary>
+            /// Return the indented lines of copy node declaration
+            /// </summary>
+            public IEnumerable<ITextLine> GetCopyLines()
```
Comment (fm-117) [inline Codegen/src/Generators/LinearNodeSourceCodeMapper.cs]: At first I thought it was better to have a method instead of a property but here we can override the `Lines` property from `Node`. This would allow to keep `TypedDataNode.cs` untouched.

Comment (LANOYDO) [reply Codegen/src/Generators/LinearNodeSourceCodeMapper.cs]: Changed to property
https://github.com/TypeCobolTeam/TypeCobol/pull/1648/commits/c148777c31d93bcbf91b96ae92881f3f876a21d9

File: Codegen/src/GeneratorHelper.cs (hunk 6 above)
Comment (LANOYDO) [reply Codegen/src/GeneratorHelper.cs]: done
https://github.com/TypeCobolTeam/TypeCobol/pull/1648/commits/c148777c31d93bcbf91b96ae92881f3f876a21d9

File: Codegen/src/Nodes/TypedDataNode.cs [hunk 8]
```diff
@@ -986,7 +987,7 @@ public static List<ITextLine> InsertChildren(ColumnsLayout? layout, List<string>
                 {
                     if (child.IsFlagSet(Flag.IsTypedefCopyNode))
                     {
-                        lines.AddRange(child.Lines);
+                        lines.AddRange((child as LinearNodeSourceCodeMapper.LinearCopyNode).Lines);
```
Comment (fm-117) [inline Codegen/src/Nodes/TypedDataNode.cs]: No need to cast here, polymorphism for the win !

File: Codegen/src/Generators/LinearNodeSourceCodeMapper.cs [hunk 9]
```diff
@@ -6,15 +6,14 @@
 using System.Linq;
 using System.Runtime.CompilerServices;
```
Comment (fm-117) [inline Codegen/src/Generators/LinearNodeSourceCodeMapper.cs]: This directive may be deleted too ?

Comment (LANOYDO) [reply Codegen/src/Generators/LinearNodeSourceCodeMapper.cs]: done
https://github.com/TypeCobolTeam/TypeCobol/pull/1648/commits/e087d9212c17eba494fe8cca891e34783e2e4570

File: Codegen/src/Nodes/TypedDataNode.cs (hunk 8 above)
Comment (LANOYDO) [reply Codegen/src/Nodes/TypedDataNode.cs]: It's right; done.
https://github.com/TypeCobolTeam/TypeCobol/pull/1648/commits/e087d9212c17eba494fe8cca891e34783e2e4570
