### PR TITLE
WI 960 ForbidSyncClauseWithStrictType

### LINKED ISSUE #960: Forbird SYNC clause with Strict Type
It seems that Cobol 2002 type comparison is more complicated that what we implemented:

> Two typed items are of the same type when:
> - The items are described with TYPE clauses that reference equivalent type declarations; or
> - The items are described as subordinate items in equivalent type declarations, starting at the same relative byte position and having the same length in bytes.
> 
> 
> Two type declarations are considered equivalent when they have the same type-name, and for each 
> elementary item in one type declaration there is a corresponding elementary item in the other type 
> declaration, starting at the same relative byte position and having the same length in bytes. 
> Each pair of corresponding elementary items shall have the same BLANK WHEN ZERO, DYNAMIC LENGTH, JUSTIFIED, PICTURE, SIGN, SYNCHRONIZED, and USAGE clauses, with the following exceptions:
> 1) Currency symbols match if and only if the corresponding currency strings are the same.
> 2) Period picture symbols match if and only if the DECIMAL-POINT IS COMMA clause is in effect for both or for
> neither of these type declarations. Comma picture symbols match if and only if the DECIMAL-POINT IS
> COMMA clause is in effect for both or for neither of these type declarations.
> 
> Additionally, locale specifications in the PICTURE clauses match if and only if:
> - both specify the same SIZE phrase in the LOCALE phrase of the PICTURE clause, and
> - both specify the LOCALE phrase without a locale-name or both specify the LOCALE phrase with the same
> external identification, where the external identification is the external-locale-name or literal value
> associated with a locale-name in the LOCALE clause of the SPECIAL-NAMES paragraph.
> 

> NOTE:  When two typed items are defined in the same source element, the above rules mean that either both items are described with the same TYPE clause or both items are described as the same subordinate item in the same type declaration.

As we only check type name:
For Scrict type which is our own definition we need to forbid Sync clause to ensure type really match at runtime.

- [ ] Forbid SYNC in a Typedef
   -Already done at the typedef level (d1686a4) but not for data under the typedef.
- [ ] A strictly typed variable cannot be SYNC
  - SYNC can be define at a parent level.

### PR DESCRIPTION
**Pull request by rooksdo**
Rebase of PR #1729.

Closes #960

### CODE REVIEW

**Comment by smedilol** [comment]
Commit message is not correct, it should be something like:
`WI #960 Forbid sync clause with strict type`

File: TypeCobol/Compiler/Domain/ProgramSymbolTableBuilder.cs [hunk 1]
```diff
@@ -246,6 +246,74 @@ public override void EndLinkageSection()
             CurrentDataDivisionSection = null;
         }
 
+        /// <summary>
+        /// Resolve in the current program linkage section, the given parameter.
+        /// </summary>
+        /// <param name="p">The parameter to resolve.</param>
+        /// <returns>The resolved variable if any, null otherwise</returns>
+        private VariableSymbol ResolveUsingParameter(CallTargetParameter p)
```
Comment (smedilol) [inline TypeCobol/Compiler/Domain/ProgramSymbolTableBuilder.cs:254]: This code has been removed from develop branch. It must be removed as weel here.

File: TypeCobol/Compiler/Domain/ProgramSymbolTableBuilder.cs [hunk 2]
```diff
@@ -246,6 +246,74 @@ public override void EndLinkageSection()
...
+            }
+
+            return null;
+        }
+
+        /// <summary>
+        /// Starting a Program PROCEDURE DIVISION => Collect all parameters.
+        /// </summary>
+        /// <param name="header"></param>
+        public override void StartProcedureDivision(ProcedureDivisionHeader header)
```
Comment (smedilol) [inline TypeCobol/Compiler/Domain/ProgramSymbolTableBuilder.cs:289]: Same remarks here, this method must be removed.

File: TypeCobol/Compiler/Symbols/Builtins.cs [hunk 3]
```diff
@@ -58,18 +59,22 @@ static Builtins()
 
             Boolean = new TypedefSymbol(string.Intern("Bool"));
             Boolean.Type = new TypedefType(Boolean, new Type(Type.Tags.Boolean));
+            Boolean.Type.SetFlag(Symbol.Flags.Strong, true, false);
```
Comment (smedilol) [inline TypeCobol/Compiler/Symbols/Builtins.cs:62]: For me these types (Bool, Date, Currency and String) are pure TypeCobol types and therefore are Strict.

Comment (fm-117) [reply TypeCobol/Compiler/Symbols/Builtins.cs:62]: They are marked as Strong in their TypeDefinition counterparts, that's why we applied the Strong flag here.

File: TypeCobol/Compiler/Symbols/Builtins.cs [hunk 4]
```diff
@@ -1,4 +1,5 @@
-﻿using TypeCobol.Compiler.Types;
+﻿using TypeCobol.Compiler.CodeElements;
```
Comment (fm-117) [inline TypeCobol/Compiler/Symbols/Builtins.cs:1]: This first using is useless, it may have been added involuntarily. Please remove it.

File: TypeCobol/Compiler/Domain/ProgramSymbolTableBuilder.cs (hunk 1 above)
Comment (rooksdo) [reply TypeCobol/Compiler/Domain/ProgramSymbolTableBuilder.cs]: Done

File: TypeCobol/Compiler/Domain/ProgramSymbolTableBuilder.cs (hunk 2 above)
Comment (rooksdo) [reply TypeCobol/Compiler/Domain/ProgramSymbolTableBuilder.cs]: Done

File: TypeCobol/Compiler/Symbols/Builtins.cs (hunk 3 above)
Comment (rooksdo) [reply TypeCobol/Compiler/Symbols/Builtins.cs:61]: I agree with @fm-117

File: TypeCobol/Compiler/Symbols/Builtins.cs (hunk 4 above)
Comment (rooksdo) [reply TypeCobol/Compiler/Symbols/Builtins.cs]: Done.

File: TypeCobol/Compiler/Symbols/Builtins.cs (hunk 3 above)
Comment (smedilol) [reply TypeCobol/Compiler/Symbols/Builtins.cs:61]: Ok

File: TypeCobol/Compiler/Diagnostics/CrossChecker.cs [hunk 5]
```diff
@@ -389,6 +389,29 @@ public override bool Visit(DataDefinition dataDefinition)
...
+                //Variable inside Typedef => check if parent typedef is marked Strict
+                else if (dataDefinition.SemanticData.NearestParent(Symbol.Kinds.Typedef).HasFlag(Symbol.Flags.Strict))
+                {
+                    DiagnosticUtils.AddError(dataDefinition, $"{dataDefinition.Name} is part of a declaration using Sync clause in Strict Type definition {dataDefinition.ParentTypeDefinition?.Name}.");
+                }
+
+            }
+            //Check if variable of user defined Strict Type is declared or has a parent declared with Sync clause (flag is inherited so no need to iterate through parents)
+            else if (dataDefinition.SemanticData.HasFlag(Symbol.Flags.HasATypedefType) && 
+                dataDefinition.TypeDefinition?.RestrictionLevel == RestrictionLevel.STRICT &&
```
Comment (fm-117) [inline TypeCobol/Compiler/Diagnostics/CrossChecker.cs:410]: Actually we could use SemanticDomain here too : `dataDefinition.TypeDefinition.SemanticData.HasFlag(Strict)`
