### PR TITLE
1752 handle copy replacing with 4colon ol

### LINKED ISSUE #1752: Handle copy replacing with ==::==
**Describe the bug**
Our parser cannot use standard Cobol Copy with a replacing clause containing string `::`.
```cobol
       01  xxxENT. COPY YxxxENT REPLACING ==::== BY ====. 
```
YxxxENT contains:
```cobol
           05  xxxENT::-FCT01.
               10 xxxENT::-FCT01-Var1            PIC X(05).
```

The parser interpret `::` as TypeCobol operator but inside a replacing clause (Pseudo text), this operator should be considered as plain text.

**Expected behavior**
No error.
The expanded source is:
```cobol
       01  xxxENT. 
           05  xxxENT-FCT01.
               10 xxxENT-FCT01-Var1            PIC X(05).
```

**Technical**
See Scanner class and use property `IsInsidePseudoText` of the ScanState to inhibit creation of token `::` inside pseudo text.

### PR DESCRIPTION
**Pull request by mayanje**
Fixes #1752

### CODE REVIEW

File: TypeCobol/Compiler/Preprocessor/ReplaceTokensLinesIterator.cs [hunk 1]
```diff
@@ -264,10 +264,13 @@ public Token NextToken()
...
                         if (currentPosition.ReplaceOperations != null)
                         {
-                            foreach (ReplaceOperation replaceOperation in currentPosition.ReplaceOperations)
+                            for(int i = 0; i < currentPosition.ReplaceOperations.Count; i++)
                             {
+                                ReplaceOperation replaceOperation = currentPosition.ReplaceOperations[i];
                                 status = TryAndReplace(nextToken, replaceOperation);
-                                if (status.replacedToken != null) return status.replacedToken;
+                                if (status.replacedToken != null)
+                                    return ApplyRemainingReplaces(i + 1, status, currentPosition.ReplaceOperations);
```
Comment (smedilol) [inline TypeCobol/Compiler/Preprocessor/ReplaceTokensLinesIterator.cs:272]: Why not let the enclosing loop continue till all replace have been done ?
I mean, what you have done in ApplyRemainingReplaces could be done right here.

File: TypeCobol.Test/Parser/Scanner/ResultFiles/PseudoText.txt [hunk 2]
```diff
@@ -22,7 +22,6 @@
 [10,11:= ]<EqualOperator>
 [12,13:==]<PseudoTextDelimiter>
 [14,15:= ]<EqualOperator>
-Line 0[12,13] <15, Error, Tokens> - Invalid character found after pseudo-text delimiter == : expecting space, comma, semicolon or period
```
Comment (smedilol) [inline TypeCobol.Test/Parser/Scanner/ResultFiles/PseudoText.txt:25]: This is not an error anymore ? It doesn't seems related to the issue.

File: Codegen/test/resources/input/TypeCobol/CopyReplace4Colon/CopyReplace4Colon7.rdz.cbl [hunk 3]
```diff
@@ -0,0 +1,13 @@
+       IDENTIFICATION division.
```
Comment (smedilol) [inline Codegen/test/resources/input/TypeCobol/CopyReplace4Colon/CopyReplace4Colon7.rdz.cbl:1]: We also need test on the parser project. Can you move this one to TypeCobol.Test project ?

File: Codegen/test/resources/input/TypeCobol/CopyReplace4Colon/YxxxENT [hunk 4]
```diff
@@ -0,0 +1,2 @@
+﻿           05  xxxENT::-FCT01.
```
Comment (smedilol) [inline Codegen/test/resources/input/TypeCobol/CopyReplace4Colon/YxxxENT:1]: File without extension and with same content as YxxxENT.cpy

File: Codegen/test/resources/input/TypeCobol/CopyReplace4Colon/CopyReplace4Colon.rdz.cbl [hunk 5]
```diff
@@ -0,0 +1,10 @@
+﻿       IDENTIFICATION DIVISION.
```
Comment (smedilol) [inline Codegen/test/resources/input/TypeCobol/CopyReplace4Colon/CopyReplace4Colon.rdz.cbl:1]: This test, CopyReplace4Colon4.rdz.cbl and CopyReplace4Colon6.rdz.cbl are almost identical.
Can you merge them into a single one.

**Review by smedilol — CHANGES_REQUESTED** [review]

File: Codegen/test/resources/input/TypeCobol/CopyReplace4Colon/YxxxENT (hunk 4 above)
Comment (mayanje) [reply Codegen/test/resources/input/TypeCobol/CopyReplace4Colon/YxxxENT:1]: I thought that you asked me to YxxxENT without extension!

File: TypeCobol.Test/Parser/Scanner/ResultFiles/PseudoText.txt (hunk 2 above)
Comment (mayanje) [reply TypeCobol.Test/Parser/Scanner/ResultFiles/PseudoText.txt:25]: Hum... this is what I missed to reinterpret the case, IBM Cobol Language Reference v5.1 page 542, I think you are right, but this diagnostic was generated in case of empty placeholder. I must figure out now how to regenerate it, ok...

File: TypeCobol/Compiler/Preprocessor/ReplaceTokensLinesIterator.cs (hunk 1 above)
Comment (mayanje) [reply TypeCobol/Compiler/Preprocessor/ReplaceTokensLinesIterator.cs:272]: Not exactly the behavior is slightly different..

File: Codegen/test/resources/input/TypeCobol/CopyReplace4Colon/CopyReplace4Colon7.rdz.cbl (hunk 3 above)
Comment (mayanje) [reply Codegen/test/resources/input/TypeCobol/CopyReplace4Colon/CopyReplace4Colon7.rdz.cbl:1]: ok, I will

File: Codegen/test/resources/input/TypeCobol/CopyReplace4Colon/CopyReplace4Colon.rdz.cbl (hunk 5 above)
Comment (mayanje) [reply Codegen/test/resources/input/TypeCobol/CopyReplace4Colon/CopyReplace4Colon.rdz.cbl:1]: Ok I will

File: Codegen/test/resources/input/TypeCobol/CopyReplace4Colon/YxxxENT (hunk 4 above)
Comment (mayanje) [reply Codegen/test/resources/input/TypeCobol/CopyReplace4Colon/YxxxENT]: done 973c01a

**Comment by mayanje** [comment]
Sorry I made a mistake with my last commit the target issue should be #1752 rather than #1252

File: Codegen/test/resources/input/TypeCobol/CopyReplace4Colon/CopyReplace4Colon.rdz.cbl (hunk 5 above)
Comment (mayanje) [reply Codegen/test/resources/input/TypeCobol/CopyReplace4Colon/CopyReplace4Colon.rdz.cbl:1]: Done by 
1434b65  with the mistake on the target issue

File: Codegen/test/resources/input/TypeCobol/CopyReplace4Colon/CopyReplace4Colon7.rdz.cbl (hunk 3 above)
Comment (mayanje) [reply Codegen/test/resources/input/TypeCobol/CopyReplace4Colon/CopyReplace4Colon7.rdz.cbl]: done by 
1434b65

File: TypeCobol.Test/Parser/Scanner/ResultFiles/PseudoText.txt (hunk 2 above)
Comment (mayanje) [reply TypeCobol.Test/Parser/Scanner/ResultFiles/PseudoText.txt]: done by 790bc13

File: TypeCobol/Compiler/Scanner/Scanner.cs [hunk 6]
```diff
@@ -2291,7 +2301,7 @@ private Token ScanUntilDelimiter(int startIndex, TokenType tokenType, string del
         /// <summary>
         /// Look for pattern ':' (cobol word chars)+ ':'
         /// </summary>
-        private bool CheckForPartialCobolWordPattern(int startIndex, out int patternEndIndex)
+        private bool CheckForPartialCobolWordPattern(MultilineScanState currentState, int startIndex, out int patternEndIndex)
```
Comment (fm-117) [inline TypeCobol/Compiler/Scanner/Scanner.cs:2304]: the state can be read directly by the method using the instance field `tokensLine` so the new parameter is not required.

**Review by fm-117 — CHANGES_REQUESTED** [review]

File: TypeCobol.Test/Parser/Programs/Cobol85/CopyReplace4Colon.rdzPGM.txt [hunk 7]
```diff
@@ -0,0 +1,15 @@
...
+
+--- Program ---
+PROGRAM: DVZS0OSM common:False initial:False recursive:False
+ author: ? written: ? compiled: ? installation: ? security: ?
+--- Intrinsic
+-- TYPES -------
+  BOOL:BOOL
+  DATE:DATE
+  CURRENCY:CURRENCY
+  STRING:STRING
```
[the remark this answers is not in the document]
Comment (mayanje) [reply TypeCobol.Test/Parser/Programs/Cobol85/CopyReplace4Colon.rdzPGM.txt:15]: Yep you are right

File: TypeCobol/Compiler/Scanner/Scanner.cs [hunk 8]
```diff
@@ -1141,12 +1145,16 @@ public Token GetNextToken()
...
                             }
 
                             delimiterToken = new Token(TokenType.PseudoTextDelimiter, startIndex, startIndex + 1, usesVirtualSpaceAtEndOfLine, tokensLine);
                             if (!(followingChar == ' ' || followingChar == ',' || followingChar == ';' || followingChar == '.'))
                             {
-                                tokensLine.AddDiagnostic(MessageCode.InvalidCharAfterPseudoTextDelimiter, delimiterToken);
+                                if (followingChar != '=' || followingChar2 != '=')
+                                {//If not an empty placeholder this is an error.
+                                    tokensLine.AddDiagnostic(MessageCode.InvalidCharAfterPseudoTextDelimiter, delimiterToken);
+                                }
```
[the remark this answers is not in the document]
Comment (mayanje) [reply TypeCobol/Compiler/Scanner/Scanner.cs:1157]: This is necessary here in case of ====

[the remark this answers is not in the document]
Comment (smedilol) [reply TypeCobol/Compiler/Scanner/Scanner.cs:1157]: Do we have test for this?

File: TypeCobol/Compiler/Preprocessor/ReplaceTokensLinesIterator.cs (hunk 1 above)
Comment (mayanje) [reply TypeCobol/Compiler/Preprocessor/ReplaceTokensLinesIterator.cs:272]: No there is also the return of the lastReplacedToken

File: TypeCobol/Compiler/Directives/TypeCobolOptions.cs [hunk 9]
```diff
@@ -33,6 +33,15 @@ public bool UseEuroInformationLegacyReplacingSyntax
             set { _useEuroInformationLegacyReplacingSyntax = value; }
         }
 
+        /// <summary>
+        /// Are these Options used for parsing a Copy.
+        /// </summary>
+        public bool AreForCopyParsing
```
[the remark this answers is not in the document]
Comment (mayanje) [reply TypeCobol/Compiler/Directives/TypeCobolOptions.cs:39]: Where this option is used is so far away, and will add such parameter to many methods.

File: TypeCobol/Compiler/Scanner/Scanner.cs (hunk 8 above)
[the remark this answers is not in the document]
Comment (mayanje) [reply TypeCobol/Compiler/Scanner/Scanner.cs:1157]: Yes PseudoText.txt and TestTokenTypes.CheckPseudoText();

File: TypeCobol/Compiler/CompilationDocument.cs [hunk 10]
```diff
@@ -54,11 +54,23 @@ public class CompilationDocument
...
 
         public List<CopyDirective> MissingCopies { get; set; }
+        /// <summary>
+        /// Is this Compilation Document for a Copy.
+        /// </summary>
+        internal bool IsForCopy
+        {
+            get;
+            set;
+        }
```
[the remark this answers is not in the document]
Comment (mayanje) [reply TypeCobol/Compiler/CompilationDocument.cs:64]: There is so many parameters in constructors, I prefer to let FileCompiler set this specific and contextual option.

[the remark this answers is not in the document]
Comment (mayanje) [reply TypeCobol/Compiler/CompilationDocument.cs:64]: This is also the case for CustomSymbols

File: TypeCobol/Compiler/Scanner/Scanner.cs (hunk 6 above)
Comment (mayanje) [reply TypeCobol/Compiler/Scanner/Scanner.cs:2304]: ok

File: TypeCobol/Compiler/CompilationDocument.cs (hunk 10 above)
[the remark this answers is not in the document]
Comment (smedilol) [reply TypeCobol/Compiler/CompilationDocument.cs:64]: As the CompilationDocument is always for Copy and CompilationUnit is always for Program, you can simplify with:
internal virtual bool IsForCopy => true;

And override it CompilationUnit.

File: TypeCobol/Compiler/Scanner/Scanner.cs (hunk 8 above)
[the remark this answers is not in the document]
Comment (smedilol) [reply TypeCobol/Compiler/Scanner/Scanner.cs:1157]: I don't see any changes in this test in this PR.
Can you test for the new condition ?

**Review by smedilol — CHANGES_REQUESTED** [review]

File: Codegen/test/resources/output/TypeCobol/CopyReplace4Colon/CopyReplace4Colon6.rdz.cbl [hunk 11]
```diff
@@ -0,0 +1,11 @@
...
+       PROGRAM-ID. CPYRPL4C.
+      
+       ENVIRONMENT DIVISION.
+       DATA DIVISION.
+       WORKING-STORAGE SECTION.
+       01 xxxENT2. COPY YxxxENT REPLACING ==::== BY ====.
+       01 xxxENT3. COPY YxxxENT REPLACING ==::== BY ==S==.
+       PROCEDURE DIVISION.
+           MOVE 'A' TO xxxENTS-FCT01-Var1.
+       END PROGRAM CPYRPL4C.
```
Comment (rooksdo) [inline Codegen/test/resources/output/TypeCobol/CopyReplace4Colon/CopyReplace4Colon6.rdz.cbl]: Not much, but for this test we could simply use the following working-storage
```cob 
01 xxxENT. COPY YxxxENT REPLACING ==::== BY ==S==.
```

**Review by rooksdo — APPROVED** [review]

File: TypeCobol/Compiler/Scanner/Scanner.cs (hunk 8 above)
[the remark this answers is not in the document]
Comment (fm-117) [reply TypeCobol/Compiler/Scanner/Scanner.cs:1157]: As I understand the code, we are reading the two following chars after the _closing_ pseudo-text delimiter so this is wrong. Let's consider this code

```cobol
COPY YAAACPY REPLACING ==== BY ====.
```

For the first pseudo-text, `followingChar` would be ` ` (space) and followingChar2 would be `B` (from the BY keyword) and for the second pseudo-text we would get `.` for followingChar and probably `\n` for followingChar2 (I haven't tested)

**Review by fm-117 — CHANGES_REQUESTED** [review]

File: TypeCobol/Compiler/Preprocessor/ReplaceTokensLinesIterator.cs (hunk 1 above)
Comment (smedilol) [reply TypeCobol/Compiler/Preprocessor/ReplaceTokensLinesIterator.cs:272]: Yes we agree that there are slight differences, but still it's possible to factorize it.

File: Codegen/test/resources/output/TypeCobol/CopyReplace4Colon/CopyReplace4Colon6.rdz.cbl (hunk 11 above)
Comment (mayanje) [reply Codegen/test/resources/output/TypeCobol/CopyReplace4Colon/CopyReplace4Colon6.rdz.cbl]: The goal here is to test multiple COPY inclusion.

File: TypeCobol/Compiler/Directives/TypeCobolOptions.cs (hunk 9 above)
[the remark this answers is not in the document]
Comment (smedilol) [reply TypeCobol/Compiler/Directives/TypeCobolOptions.cs:39]: I agree too that AreForCopyParsing is not really an option.
When you parse a copy, you don't have the choice to parse it as a program.
It would better to store this information in something more technical / not part of public API.

For TextSourceInfo, I don't know. Because when this object is instantiated, you don't know if it's a copy yet.

Other solutions:
Scanner : Add a property? Convert static method to instance methods ?
TypeCobolOptions : at least change the visibility to internal and make it a read-only property.

[the remark this answers is not in the document]
Comment (fm-117) [reply TypeCobol/Compiler/Directives/TypeCobolOptions.cs:39]: > For TextSourceInfo, I don't know. Because when this object is instantiated, you don't know if it's a copy yet.

Checking the usages show that the TextSourceInfo constructor is (indirectly) called by Workspace and FileCompiler. In Workspace, we can safely assume that it is a program, in FileCompiler we have the `isCopyFile` info. Rest of usages are in tests.

I agree that the internal + readonly could be a quick workaround.

File: TypeCobol/Compiler/Preprocessor/ReplaceTokensLinesIterator.cs (hunk 1 above)
Comment (mayanje) [reply TypeCobol/Compiler/Preprocessor/ReplaceTokensLinesIterator.cs:272]: No, there's a return value here, depending on a continuation.

File: TypeCobol.Test/Parser/Programs/Cobol85/CopyReplace4Colon.rdzPGM.txt (hunk 7 above)
[the remark this answers is not in the document]
Comment (mayanje) [reply TypeCobol.Test/Parser/Programs/Cobol85/CopyReplace4Colon.rdzPGM.txt]: @semdilol request this test to be here.

File: TypeCobol/Compiler/CompilationDocument.cs [hunk 12]
```diff
@@ -54,11 +54,23 @@ public class CompilationDocument
...
 
         /// <summary>
         /// Issue #315
         /// </summary>
-        private MultilineScanState initialScanStateForCopy;
+        public MultilineScanState InitialScanStateForCopy
+        {
+            get;
+            set;
+        }
```
[the remark this answers is not in the document]
Comment (mayanje) [reply TypeCobol/Compiler/CompilationDocument.cs]: ok done

File: TypeCobol/Compiler/CompilationUnit.cs [hunk 13]
```diff
@@ -3,11 +3,13 @@
 using System.Text;
```
[the remark this answers is not in the document]
Comment (mayanje) [reply TypeCobol/Compiler/CompilationUnit.cs]: ok removed.

File: TypeCobol/Compiler/CupPreprocessor/CompilerDirectiveBuilder.cs [hunk 14]
```diff
@@ -157,22 +157,32 @@ public virtual void EnterCopyCompilerStatement(TypeCobol.Compiler.Scanner.Token
...
                 {
                     // Get relevant tokens
                     List<Token> relevantTokens = copyReplacingOperands.Item1;
                     List<Token> replaceTokens = copyReplacingOperands.Item2;
-                    BuildReplaceOperation(copy.ReplaceOperations, ref comparisonToken, ref followingComparisonTokens,
-                        ref replacementToken, ref replacementTokens, false, relevantTokens);
+                    if (!BuildReplaceOperation(copy.ReplaceOperations, ref comparisonToken, ref followingComparisonTokens,
+                        ref replacementToken, ref replacementTokens, false, relevantTokens))
+                    {
+                        if (!bReported)
```
[the remark this answers is not in the document]
Comment (mayanje) [reply TypeCobol/Compiler/CupPreprocessor/CompilerDirectiveBuilder.cs:169]: The target location is given by QualifiedTextName instance, so single diagnostics for it is enough, and if relevantTokens are empty we have no relevant tokens.

File: TypeCobol.Test/Parser/Programs/Cobol85/CopyReplace4ColonErr.rdz.cbl [hunk 15]
```diff
@@ -0,0 +1,10 @@
+﻿       IDENTIFICATION DIVISION.
+       PROGRAM-ID. CPYRPL4C.
+      
+       ENVIRONMENT DIVISION.
+       DATA DIVISION.
+       WORKING-STORAGE SECTION.
+       01  xxxENT. COPY YxxxENT REPLACING ==== BY ====.
```
Comment (smedilol) [inline TypeCobol.Test/Parser/Programs/Cobol85/CopyReplace4ColonErr.rdz.cbl:7]: Copy YxxxENT is missing

**Review by smedilol — CHANGES_REQUESTED** [review]

File: TypeCobol.Test/Parser/Programs/Cobol85/CopyReplace4Colon.rdzPGM.txt (hunk 7 above)
[the remark this answers is not in the document]
Comment (smedilol) [reply TypeCobol.Test/Parser/Programs/Cobol85/CopyReplace4Colon.rdzPGM.txt]: Copy is not missing anymore, so I think we can close this remark.

File: TypeCobol/Compiler/Directives/TypeCobolOptions.cs (hunk 9 above)
[the remark this answers is not in the document]
Comment (mayanje) [reply TypeCobol/Compiler/Directives/TypeCobolOptions.cs:39]: @smedilol , @fm-117 Ok what about using the InitialScanStateForCopy and add new Flag InsideCopy to MultilineScanState. and to propagate this flag.

File: TypeCobol/Compiler/Scanner/Scanner.cs (hunk 8 above)
[the remark this answers is not in the document]
Comment (mayanje) [reply TypeCobol/Compiler/Scanner/Scanner.cs:1157]: The new condition is for keeping the diagnostics in PseudoText.txt and TestTokenTypes.CheckPseudoText() tests, otherwise the diagnostics will not be generated. This test is not for the BY but for the condition _if (tokensLine.ScanState.InsidePseudoText)_
thus it is applyed inside a placeholder.

File: TypeCobol/Compiler/Scanner/Scanner.cs (hunk 6 above)
Comment (mayanje) [reply TypeCobol/Compiler/Scanner/Scanner.cs]: done

**Review by smedilol — CHANGES_REQUESTED** [review]

File: TypeCobol/Compiler/Directives/TypeCobolOptions.cs (hunk 9 above)
[the remark this answers is not in the document]
Comment (smedilol) [reply TypeCobol/Compiler/Directives/TypeCobolOptions.cs:39]: @mayanje @fm-117 Yes, it seems a good option. And if solution listed in #428 it will also works with new method Scanner. ScanIsolatedTokenInGivenContext.

File: TypeCobol/Compiler/Scanner/Scanner.cs (hunk 8 above)
[the remark this answers is not in the document]
Comment (mayanje) [reply TypeCobol/Compiler/Scanner/Scanner.cs:1157]: Ok, I made a mistkake using smedilol method this if is useless.

File: Codegen/test/resources/input/TypeCobol/CopyReplace4Colon/CopyReplace4Colon2.rdz.cbl [hunk 16]
```diff
@@ -0,0 +1,11 @@
+﻿       IDENTIFICATION DIVISION.
```
Comment (smedilol) [inline Codegen/test/resources/input/TypeCobol/CopyReplace4Colon/CopyReplace4Colon2.rdz.cbl:1]: Test CopyReplace4Colon2.rdz.cbl  is included in test CopyReplace4Colon**3**.rdz.cbl and can be removed.

File: Codegen/test/resources/input/TypeCobol/CopyReplace4Colon/CopyReplace4Colon.rdz.cbl (hunk 5 above)
Comment (smedilol) [inline Codegen/test/resources/input/TypeCobol/CopyReplace4Colon/CopyReplace4Colon.rdz.cbl:1]: Test CopyReplace4Colon.rdz.cbl  is included in CopyReplace4Colon**4**.rdz.cbl  and can be removed.

File: Codegen/test/resources/input/TypeCobol/CopyReplace4Colon/CopyReplace4Colon5.rdz.cbl [hunk 17]
```diff
@@ -0,0 +1,13 @@
...
+       PROGRAM-ID. CPYRPL4C.
+      
+       ENVIRONMENT DIVISION.
+       DATA DIVISION.
+       WORKING-STORAGE SECTION.
+       01  xxxENT. COPY YxxxENT REPLACING ==::== BY ====.
+       01  xxxENT2. COPY YxxxENT2 REPLACING ==::== BY ====.
+       PROCEDURE DIVISION.
+           MOVE 'A' TO xxxENT-FCT01-Var1 OF xxxENT.
+           MOVE 'A' TO xxxENT2-FCT01-Var1.
```
Comment (smedilol) [inline Codegen/test/resources/input/TypeCobol/CopyReplace4Colon/CopyReplace4Colon5.rdz.cbl:11]: These lines:
```cobol
01  xxxENT2. COPY YxxxENT2 REPLACING ==::== BY ====.
MOVE 'A' TO xxxENT2-FCT01-Var1.
```
could be merged into test CopyReplace4Colon3.rdz.cbl, so this test 5 can be removed.

**Review by smedilol — CHANGES_REQUESTED** [review]

File: Codegen/test/resources/input/TypeCobol/CopyReplace4Colon/CopyReplace4Colon2.rdz.cbl (hunk 16 above)
Comment (mayanje) [reply Codegen/test/resources/input/TypeCobol/CopyReplace4Colon/CopyReplace4Colon2.rdz.cbl:1]: These tests are here to test nested COPY inclusion at depth 2 and 3

File: Codegen/test/resources/input/TypeCobol/CopyReplace4Colon/CopyReplace4Colon.rdz.cbl (hunk 5 above)
Comment (mayanje) [reply Codegen/test/resources/input/TypeCobol/CopyReplace4Colon/CopyReplace4Colon.rdz.cbl:1]: Tests CopyReplace4Colon4.rdz.cbl is here to test multiple COPY inclusion in a same file.

File: Codegen/test/resources/input/TypeCobol/CopyReplace4Colon/CopyReplace4Colon5.rdz.cbl (hunk 17 above)
Comment (mayanje) [reply Codegen/test/resources/input/TypeCobol/CopyReplace4Colon/CopyReplace4Colon5.rdz.cbl:11]: This test is not only intended to test MOVE 'A' TO xxxENT2-FCT01-Var1.
But also to test COPY inclusion sequence.

File: TypeCobol/Compiler/Scanner/Scanner.cs [hunk 18]
```diff
@@ -2304,10 +2308,18 @@ private bool CheckForPartialCobolWordPattern(int startIndex, out int patternEndI
             { }
 
             // no legal cobol word chars found 
-            if (index == startIndex + 1 && !CobolChar.IsCobolWordChar(line[index])) return false;
+            //if (index == startIndex + 1 && !CobolChar.IsCobolWordChar(line[index])) return false;
+            if (index == startIndex + 1 && !CobolChar.IsCobolWordChar(line[index]))
+            {
+                //Empty partialCobolWord are only allowed inside pseudo text and copy
+                if (!(currentState.InsidePseudoText || (this.compilerOptions != null && currentState.InsideCopy)))
```
[the remark this answers is not in the document]
Comment (mayanje) [reply TypeCobol/Compiler/Scanner/Scanner.cs]: ok done

File: TypeCobol/Compiler/CompilationDocument.cs (hunk 10 above)
[the remark this answers is not in the document]
Comment (mayanje) [reply TypeCobol/Compiler/CompilationDocument.cs]: No longer needed

File: TypeCobol/Compiler/Directives/TypeCobolOptions.cs (hunk 9 above)
[the remark this answers is not in the document]
Comment (mayanje) [reply TypeCobol/Compiler/Directives/TypeCobolOptions.cs]: done

File: TypeCobol.Test/Parser/Programs/Cobol85/CopyReplace4ColonErr.rdz.cbl (hunk 15 above)
Comment (mayanje) [reply TypeCobol.Test/Parser/Programs/Cobol85/CopyReplace4ColonErr.rdz.cbl:7]: ok done

File: TypeCobol/Compiler/Scanner/Scanner.cs [hunk 19]
```diff
@@ -1132,6 +1135,7 @@ public Token GetNextToken()
                         {
                             // get the immediately following char
                             char followingChar;
+                            char followingChar2 = '\0';
```
[the remark this answers is not in the document]
Comment (mayanje) [reply TypeCobol/Compiler/Scanner/Scanner.cs]: done

File: TypeCobol/Compiler/Scanner/Scanner.cs [hunk 20]
```diff
@@ -959,7 +959,10 @@ public Token GetNextToken()
                 case ':':
                     // -- TypeCobol specific syntax --
                     // QualifiedNameSeparator => qualifierName::qualifiedName
-                    if (currentIndex < lastIndex && line[currentIndex + 1] == ':')
+                    //if (currentIndex < lastIndex && line[currentIndex + 1] == ':')
+                    if (!currentState.InsidePseudoText //No QualifiedNameSeparator allowed in pseudoText
+                        && (this.compilerOptions != null && !currentState.InsideCopy) //No QualifiedNameSeparator allowed in COPY
```
[the remark this answers is not in the document]
Comment (mayanje) [reply TypeCobol/Compiler/Scanner/Scanner.cs]: done

File: TypeCobol/Compiler/Scanner/Scanner.cs [hunk 21]
```diff
@@ -2304,10 +2306,18 @@ private bool CheckForPartialCobolWordPattern(int startIndex, out int patternEndI
             { }
 
             // no legal cobol word chars found 
-            if (index == startIndex + 1 && !CobolChar.IsCobolWordChar(line[index])) return false;
+            //if (index == startIndex + 1 && !CobolChar.IsCobolWordChar(line[index])) return false;
```
Comment (smedilol) [inline TypeCobol/Compiler/Scanner/Scanner.cs:2309]: Can you remove this comment ?

**Review by smedilol — CHANGES_REQUESTED** [review]

File: TypeCobol/Compiler/Scanner/Scanner.cs (hunk 21 above)
Comment (mayanje) [reply TypeCobol/Compiler/Scanner/Scanner.cs]: ok, done

File: TypeCobol/Compiler/Scanner/MultilineScanState.cs [hunk 22]
```diff
@@ -141,6 +146,7 @@ public MultilineScanState Clone()
             MultilineScanState clone = new MultilineScanState(InsideDataDivision, InsideProcedureDivision, InsidePseudoText, InsideSymbolicCharacterDefinitions,
                 InsideFormalizedComment, InsideMultilineComments, InsideParamsField, 
                 DecimalPointIsComma, WithDebuggingMode, EncodingForAlphanumericLiterals);
+            clone.InsideCopy = this.InsideCopy;
```
Comment (fm-117) [inline TypeCobol/Compiler/Scanner/MultilineScanState.cs:149]: No new constructor parameter ?

Comment (mayanje) [reply TypeCobol/Compiler/Scanner/MultilineScanState.cs:149]: Yes this property is explicitly set in CompilationDocuemnt.

File: Codegen/test/resources/input/TypeCobol/CopyReplace4Colon/CopyReplace4Colon.rdz.cbl (hunk 5 above)
Comment (smedilol) [reply Codegen/test/resources/input/TypeCobol/CopyReplace4Colon/CopyReplace4Colon.rdz.cbl:1]: Yes I understand that. 
My point is that test CopyReplace4Colon.rdz.cbl is useless as CopyReplace4Colon4.rdz.cbl already cover it.
Also the test for multiple COPY inclusion must be moved into TypeCobol.Test.
Here we are in a codegen test, so it assumes the parser already works as expected with `==::==`.
This test is only here to test the behavior of codegen.

**Review by smedilol — CHANGES_REQUESTED** [review]

File: Codegen/test/resources/input/TypeCobol/CopyReplace4Colon/CopyReplace4Colon.rdz.cbl (hunk 5 above)
Comment (mayanje) [reply Codegen/test/resources/input/TypeCobol/CopyReplace4Colon/CopyReplace4Colon.rdz.cbl:1]: ok done https://github.com/TypeCobolTeam/TypeCobol/pull/1794/commits/4e0e1991fafc22e6a3291dbf91d2194ba9924e5e

File: TypeCobol/Compiler/Preprocessor/ReplaceTokensLinesIterator.cs (hunk 1 above)
Comment (mayanje) [reply TypeCobol/Compiler/Preprocessor/ReplaceTokensLinesIterator.cs]: ok done in  041d2e1

**Review by smedilol — APPROVED** [review]

File: TypeCobol/Compiler/FileCompiler.cs [hunk 23]
```diff
@@ -184,7 +184,7 @@ public class FileCompiler
             // 3. Prepare the data structures used by the different steps of the compiler
             if (isCopyFile)
             {
-                CompilationResultsForCopy = new CompilationDocument(TextDocument.Source, TextDocument.Lines, compilerOptions, documentProvider, scanState, copyTextNameVariations);
+                CompilationResultsForCopy = new CompilationDocument(TextDocument.Source, TextDocument.Lines, compilerOptions, documentProvider, scanState, copyTextNameVariations);
```
Comment (fm-117) [inline TypeCobol/Compiler/FileCompiler.cs:187]: Unneeded whitespace

**Review by fm-117 — APPROVED** [review]

File: TypeCobol.Test/Parser/Programs/Cobol85/CopyReplace4ColonMultiCopy.rdzPGM.txt [hunk 24]
```diff
@@ -0,0 +1,20 @@
...
+-- DATA --------
+  xxxENT:Alphanumeric
+  xxxENT-FCT01:Alphanumeric
+  xxxENT-FCT01:Alphanumeric
+  xxxENT-FCT01-Var1:Alphanumeric
+  xxxENT-FCT01-Var1:Alphanumeric
+  xxxENT2:Alphanumeric
+  xxxENT2-FCT01:Alphanumeric
+  xxxENT2-FCT01-Var1:Alphanumeric
+  xxxENT1:Alphanumeric
```
Comment (rooksdo) [inline TypeCobol.Test/Parser/Programs/Cobol85/CopyReplace4ColonMultiCopy.rdzPGM.txt:14]: Not sure I understand how these variables are sorted but they are all there.

File: TypeCobol.Test/Parser/Programs/Cobol85/CopyReplace4Colon.rdz.cbl [hunk 25]
```diff
@@ -0,0 +1,13 @@
...
+       working-storage section.
+       COPY YDVZOSM replacing ==::== by ====
+                                         ==:MDVZOSM:== by ==MDVZOSM==.
+       COPY YDVZOSM replacing ==::== by ==2==
+                                         ==:MDVZOSM:== by ==Foo==.
+       procedure division.
+           move 'A' to MDVZOSM-A
+           move 'A' to Foo-A2
+           .
+       end program DVZS0OSM.
```
[the remark this answers is not in the document]
Comment (mayanje) [reply TypeCobol.Test/Parser/Programs/Cobol85/CopyReplace4Colon.rdz.cbl:13]: done in ba16d41

File: TypeCobol.Test/Parser/Programs/Cobol85/YDVZOSM.cpy [hunk 26]
```diff
@@ -0,0 +1,2 @@
+﻿       01  :MDVZOSM:-A::.
+           05 :MDVZOSM:-A::-Var0 pic X.
```
[the remark this answers is not in the document]
Comment (mayanje) [reply TypeCobol.Test/Parser/Programs/Cobol85/YDVZOSM.cpy]: done in ba16d41

File: TypeCobol.Test/Parser/Programs/Cobol85/CopyReplace4ColonMultiCopy.rdzPGM.txt (hunk 24 above)
Comment (mayanje) [reply TypeCobol.Test/Parser/Programs/Cobol85/CopyReplace4ColonMultiCopy.rdzPGM.txt:14]: Nothing to say

File: TypeCobol/Compiler/FileCompiler.cs (hunk 23 above)
Comment (mayanje) [reply TypeCobol/Compiler/FileCompiler.cs]: done in 25c29f9

**Review by fm-117 — APPROVED** [review]

**Review by smedilol — APPROVED** [review]

**Review by rooksdo — APPROVED** [review]
